//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class GDCoreDataMetadata, NSNumber, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface _GDCoreDataFileNode : NSManagedObject
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
- (id)parentsSet;
- (id)childrenSet;
- (void)setPrimitiveRootValue:(_Bool)arg1;
- (_Bool)primitiveRootValue;
@property _Bool rootValue;
- (void)setPrimitiveChildrenAreUnknownValue:(_Bool)arg1;
- (_Bool)primitiveChildrenAreUnknownValue;
@property _Bool childrenAreUnknownValue;
- (id)objectID;

// Remaining properties
@property(retain, nonatomic) NSSet *children; // @dynamic children;
@property(retain, nonatomic) NSNumber *childrenAreUnknown; // @dynamic childrenAreUnknown;
@property(retain, nonatomic) GDCoreDataMetadata *metadata; // @dynamic metadata;
@property(retain, nonatomic) NSSet *parents; // @dynamic parents;
@property(retain, nonatomic) NSNumber *root; // @dynamic root;
@property(retain, nonatomic) NSString *urlString; // @dynamic urlString;

@end

