//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class GDCoreDataFileNode, NSData, NSString;

__attribute__((visibility("hidden")))
@interface _GDCoreDataMetadata : NSManagedObject
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
- (id)objectID;

// Remaining properties
@property(retain, nonatomic) GDCoreDataFileNode *fileNode; // @dynamic fileNode;
@property(retain, nonatomic) NSData *jsonData; // @dynamic jsonData;
@property(retain, nonatomic) NSString *metadataClassName; // @dynamic metadataClassName;

@end

