//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

#import "UITextFieldDelegate.h"

@class GDRemoteFileServiceSession, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface AccountPropertiesViewController : TGThemeTableViewController <UITextFieldDelegate>
{
    GDRemoteFileServiceSession *_session;
    NSString *_displayName;
    NSArray *_accountInfos;
}

@property(retain, nonatomic) NSArray *accountInfos; // @synthesize accountInfos=_accountInfos;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) GDRemoteFileServiceSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

