//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class FXLabel, RoundedIconView;

__attribute__((visibility("hidden")))
@interface ActionCell : UICollectionViewCell
{
    RoundedIconView *_iconView;
    FXLabel *_textLabel;
}

@property(retain, nonatomic) FXLabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) RoundedIconView *iconView; // @synthesize iconView=_iconView;
- (void).cxx_destruct;
- (void)setImage:(id)arg1 rounded:(_Bool)arg2;
- (void)setTitle:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

