//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGPreferencesTableViewController.h"

__attribute__((visibility("hidden")))
@interface AdvancedOptionsTableViewController : TGPreferencesTableViewController
{
}

- (void)swithAccessCheckbox;
- (void)showSecurity:(id)arg1;
- (void)showSortOptions:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

@end

