//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "FICImageCacheDelegate.h"
#import "UIApplicationDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UISplitViewControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, UIAlertView, UIView, UIWindow;

__attribute__((visibility("hidden")))
@interface AppDelegate : UIResponder <UIApplicationDelegate, FICImageCacheDelegate, UISplitViewControllerDelegate, UINavigationControllerDelegate, UITextFieldDelegate>
{
    int uid;
    int gid;
    UIAlertView *alert;
    UIWindow *_window;
    id _block;
    UIView *_blockBackground;
}

@property(retain, nonatomic) UIView *blockBackground; // @synthesize blockBackground=_blockBackground;
@property(retain, nonatomic) id block; // @synthesize block=_block;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)applicationWillTerminate:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)authenticateWithTouchID:(id)arg1;
- (void)authenticateWithPassword;
- (void)authenticateIfNeeds;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)imageCache:(id)arg1 errorDidOccurWithMessage:(id)arg2;
- (_Bool)imageCache:(id)arg1 shouldProcessAllFormatsInFamily:(id)arg2 forEntity:(id)arg3;
- (void)imageCache:(id)arg1 wantsSourceImageForEntity:(id)arg2 withFormatName:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)__handleOpenURL:(id)arg1;
- (_Bool)splitViewController:(id)arg1 shouldHideViewController:(id)arg2 inOrientation:(long long)arg3;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

