//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FileItem.h"

@class LSApplicationProxy, NSString;

__attribute__((visibility("hidden")))
@interface ApplicationItem : FileItem
{
    NSString *_UUID;
    _Bool _system;
    NSString *_bundleId;
    NSString *_iconPath;
    NSString *_documentPath;
    LSApplicationProxy *_appProxy;
    NSString *_version;
}

@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) LSApplicationProxy *appProxy; // @synthesize appProxy=_appProxy;
@property(retain, nonatomic) NSString *documentPath; // @synthesize documentPath=_documentPath;
@property(retain, nonatomic) NSString *iconPath; // @synthesize iconPath=_iconPath;
@property(retain, nonatomic) NSString *bundleId; // @synthesize bundleId=_bundleId;
@property(nonatomic, getter=isSystem) _Bool system; // @synthesize system=_system;
- (void).cxx_destruct;
- (id)UUID;
- (id)icon;
- (_Bool)isEqual:(id)arg1;
- (CDUnknownBlockType)drawingBlockForImage:(id)arg1 withFormatName:(id)arg2;
- (id)sourceImageURLWithFormatName:(id)arg1;
- (id)fileSizeString;
- (id)thumbIconPath;

@end

