//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIImageView;

__attribute__((visibility("hidden")))
@interface ButtonsGroup : UIView
{
    _Bool _isExpanded;
    _Bool _enabled;
    id <ButtonsGroupDelegate> _delegate;
    NSArray *_images;
    NSArray *_titles;
    long long _activeIndex;
    UIImageView *_imageView;
    UIImageView *_arrowImageView;
    NSArray *_imageViews;
}

@property(retain, nonatomic) NSArray *imageViews; // @synthesize imageViews=_imageViews;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) long long activeIndex; // @synthesize activeIndex=_activeIndex;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(retain, nonatomic) NSArray *images; // @synthesize images=_images;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool isExpanded; // @synthesize isExpanded=_isExpanded;
@property(nonatomic) __weak id <ButtonsGroupDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setImages:(id)arg1 title:(id)arg2 activeIndex:(long long)arg3;
- (void)buttonsGroupTapped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

