//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ButtonsGroup;

@protocol ButtonsGroupDelegate <NSObject>
- (void)buttonGroupDidResizeInAnimations:(ButtonsGroup *)arg1;
- (void)buttonGroup:(ButtonsGroup *)arg1 didSelectedIndex:(int)arg2;
@end

