//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UITextView;

__attribute__((visibility("hidden")))
@interface ChangeLogViewController : UIViewController
{
    UITextView *_logView;
}

@property(retain, nonatomic) UITextView *logView; // @synthesize logView=_logView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

