//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface CkoCertChain : NSObject
{
    void *m_obj;
}

- (_Bool)VerifyCertSignatures;
- (_Bool)SaveLastError:(id)arg1;
- (_Bool)IsRootTrusted:(id)arg1;
- (id)GetCert:(id)arg1;
@property(readonly, copy, nonatomic) NSString *Version;
@property(nonatomic) _Bool VerboseLogging;
@property(readonly, nonatomic) _Bool ReachesRoot;
@property(readonly, copy, nonatomic) NSNumber *NumExpiredCerts;
@property(readonly, copy, nonatomic) NSNumber *NumCerts;
@property(nonatomic) _Bool LastMethodSuccess;
@property(readonly, copy, nonatomic) NSString *LastErrorXml;
@property(readonly, copy, nonatomic) NSString *LastErrorText;
@property(readonly, copy, nonatomic) NSString *LastErrorHtml;
@property(copy, nonatomic) NSString *DebugLogFilePath;
- (id)stringWithUtf8:(const char *)arg1;
- (void)clearCppImplObj;
- (void)setCppImplObj:(void *)arg1;
- (void *)CppImplObj;
- (void)dispose;
- (void)dealloc;
- (id)init;

@end

