//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString;

@interface CkoCert : NSObject
{
    void *m_obj;
}

- (_Bool)VerifySignature;
- (_Bool)UseCertVault:(id)arg1;
- (_Bool)SetPrivateKeyPem:(id)arg1;
- (_Bool)SetPrivateKey:(id)arg1;
- (_Bool)SetFromEncoded:(id)arg1;
- (_Bool)SaveToFile:(id)arg1;
- (_Bool)SaveLastError:(id)arg1;
- (_Bool)PemFileToDerFile:(id)arg1 toPath:(id)arg2;
- (_Bool)LoadTaskResult:(id)arg1;
- (_Bool)LoadPfxFile:(id)arg1 password:(id)arg2;
- (_Bool)LoadPfxData2:(id)arg1 szByteData:(id)arg2 password:(id)arg3;
- (_Bool)LoadPfxData:(id)arg1 password:(id)arg2;
- (_Bool)LoadPem:(id)arg1;
- (_Bool)LoadFromFile:(id)arg1;
- (_Bool)LoadFromBinary2:(id)arg1 szByteData:(id)arg2;
- (_Bool)LoadFromBinary:(id)arg1;
- (_Bool)LoadFromBase64:(id)arg1;
- (_Bool)HasPrivateKey;
- (id)GetValidToDt;
- (id)GetValidFromDt;
- (id)GetPrivateKeyPem;
- (id)GetExtensionAsXml:(id)arg1;
- (id)GetEncoded;
- (id)GetCertChain;
- (id)FindIssuer;
- (id)ExportToPfxData:(id)arg1 includeCertChain:(_Bool)arg2;
- (id)ExportPublicKey;
- (id)ExportPrivateKey;
- (id)ExportCertXml;
- (_Bool)ExportCertPemFile:(id)arg1;
- (id)ExportCertPem;
- (_Bool)ExportCertDerFile:(id)arg1;
- (id)ExportCertDer;
- (id)CheckRevoked;
@property(readonly, copy, nonatomic) NSString *Version;
@property(nonatomic) _Bool VerboseLogging;
@property(readonly, copy, nonatomic) NSString *ValidToStr;
@property(readonly, copy, nonatomic) NSDate *ValidTo;
@property(readonly, copy, nonatomic) NSString *ValidFromStr;
@property(readonly, copy, nonatomic) NSDate *ValidFrom;
@property(readonly, nonatomic) _Bool TrustedRoot;
@property(readonly, copy, nonatomic) NSString *SubjectS;
@property(readonly, copy, nonatomic) NSString *SubjectOU;
@property(readonly, copy, nonatomic) NSString *SubjectO;
@property(readonly, copy, nonatomic) NSString *SubjectL;
@property(readonly, copy, nonatomic) NSString *SubjectKeyId;
@property(readonly, copy, nonatomic) NSString *SubjectE;
@property(readonly, copy, nonatomic) NSString *SubjectDN;
@property(readonly, copy, nonatomic) NSString *SubjectCN;
@property(readonly, copy, nonatomic) NSString *SubjectC;
@property(readonly, nonatomic) _Bool SignatureVerified;
@property(readonly, copy, nonatomic) NSString *Sha1Thumbprint;
@property(readonly, copy, nonatomic) NSString *SerialNumber;
@property(readonly, nonatomic) _Bool SelfSigned;
@property(readonly, copy, nonatomic) NSString *Rfc822Name;
@property(readonly, nonatomic) _Bool Revoked;
@property(readonly, copy, nonatomic) NSString *OcspUrl;
@property(nonatomic) _Bool LastMethodSuccess;
@property(readonly, copy, nonatomic) NSString *LastErrorXml;
@property(readonly, copy, nonatomic) NSString *LastErrorText;
@property(readonly, copy, nonatomic) NSString *LastErrorHtml;
@property(readonly, copy, nonatomic) NSString *IssuerS;
@property(readonly, copy, nonatomic) NSString *IssuerOU;
@property(readonly, copy, nonatomic) NSString *IssuerO;
@property(readonly, copy, nonatomic) NSString *IssuerL;
@property(readonly, copy, nonatomic) NSString *IssuerE;
@property(readonly, copy, nonatomic) NSString *IssuerDN;
@property(readonly, copy, nonatomic) NSString *IssuerCN;
@property(readonly, copy, nonatomic) NSString *IssuerC;
@property(readonly, nonatomic) _Bool IsRoot;
@property(readonly, copy, nonatomic) NSNumber *IntendedKeyUsage;
@property(readonly, nonatomic) _Bool ForTimeStamping;
@property(readonly, nonatomic) _Bool ForServerAuthentication;
@property(readonly, nonatomic) _Bool ForSecureEmail;
@property(readonly, nonatomic) _Bool ForCodeSigning;
@property(readonly, nonatomic) _Bool ForClientAuthentication;
@property(readonly, nonatomic) _Bool Expired;
@property(copy, nonatomic) NSString *DebugLogFilePath;
@property(readonly, copy, nonatomic) NSNumber *CertVersion;
@property(readonly, copy, nonatomic) NSString *AuthorityKeyId;
- (id)stringWithUtf8:(const char *)arg1;
- (void)clearCppImplObj;
- (void)setCppImplObj:(void *)arg1;
- (void *)CppImplObj;
- (void)dispose;
- (void)dealloc;
- (id)init;

@end

