//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface CkoDtObj : NSObject
{
    void *m_obj;
}

- (id)Serialize;
- (_Bool)SaveLastError:(id)arg1;
- (void)DeSerialize:(id)arg1;
@property(copy, nonatomic) NSNumber *Year;
@property(readonly, copy, nonatomic) NSString *Version;
@property(nonatomic) _Bool VerboseLogging;
@property(nonatomic) _Bool Utc;
@property(copy, nonatomic) NSNumber *StructTmYear;
@property(copy, nonatomic) NSNumber *StructTmMonth;
@property(copy, nonatomic) NSNumber *Second;
@property(copy, nonatomic) NSNumber *Month;
@property(copy, nonatomic) NSNumber *Minute;
@property(nonatomic) _Bool LastMethodSuccess;
@property(readonly, copy, nonatomic) NSString *LastErrorXml;
@property(readonly, copy, nonatomic) NSString *LastErrorText;
@property(readonly, copy, nonatomic) NSString *LastErrorHtml;
@property(copy, nonatomic) NSNumber *Hour;
@property(copy, nonatomic) NSString *DebugLogFilePath;
@property(copy, nonatomic) NSNumber *Day;
- (id)stringWithUtf8:(const char *)arg1;
- (void)clearCppImplObj;
- (void)setCppImplObj:(void *)arg1;
- (void *)CppImplObj;
- (void)dispose;
- (void)dealloc;
- (id)init;

@end

