//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface CkoPrivateKey : NSObject
{
    void *m_obj;
}

- (_Bool)SaveXmlFile:(id)arg1;
- (_Bool)SaveRsaPemFile:(id)arg1;
- (_Bool)SaveRsaDerFile:(id)arg1;
- (_Bool)SavePkcs8PemFile:(id)arg1;
- (_Bool)SavePkcs8File:(id)arg1;
- (_Bool)SavePkcs8EncryptedPemFile:(id)arg1 path:(id)arg2;
- (_Bool)SavePkcs8EncryptedFile:(id)arg1 path:(id)arg2;
- (_Bool)SaveLastError:(id)arg1;
- (_Bool)LoadXmlFile:(id)arg1;
- (_Bool)LoadXml:(id)arg1;
- (_Bool)LoadRsaDerFile:(id)arg1;
- (_Bool)LoadRsaDer:(id)arg1;
- (_Bool)LoadPkcs8File:(id)arg1;
- (_Bool)LoadPkcs8EncryptedFile:(id)arg1 password:(id)arg2;
- (_Bool)LoadPkcs8Encrypted:(id)arg1 password:(id)arg2;
- (_Bool)LoadPkcs8:(id)arg1;
- (_Bool)LoadPemFile:(id)arg1;
- (_Bool)LoadPem:(id)arg1;
- (_Bool)LoadEncryptedPemFile:(id)arg1 password:(id)arg2;
- (_Bool)LoadEncryptedPem:(id)arg1 password:(id)arg2;
- (id)GetXml;
- (id)GetRsaPem;
- (id)GetRsaDer;
- (id)GetPublicKey;
- (id)GetPkcs8Pem;
- (id)GetPkcs8EncryptedPem:(id)arg1;
- (id)GetPkcs8EncryptedENC:(id)arg1 password:(id)arg2;
- (id)GetPkcs8Encrypted:(id)arg1;
- (id)GetPkcs8ENC:(id)arg1;
- (id)GetPkcs8;
- (id)GetPkcs1ENC:(id)arg1;
@property(readonly, copy, nonatomic) NSString *Version;
@property(nonatomic) _Bool VerboseLogging;
@property(copy, nonatomic) NSString *Pkcs8EncryptAlg;
@property(nonatomic) _Bool LastMethodSuccess;
@property(readonly, copy, nonatomic) NSString *LastErrorXml;
@property(readonly, copy, nonatomic) NSString *LastErrorText;
@property(readonly, copy, nonatomic) NSString *LastErrorHtml;
@property(readonly, copy, nonatomic) NSString *KeyType;
@property(copy, nonatomic) NSString *DebugLogFilePath;
@property(readonly, copy, nonatomic) NSNumber *BitLength;
- (id)stringWithUtf8:(const char *)arg1;
- (void)clearCppImplObj;
- (void)setCppImplObj:(void *)arg1;
- (void *)CppImplObj;
- (void)dispose;
- (void)dealloc;
- (id)init;

@end

