//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CkoPublicKey : NSObject
{
    void *m_obj;
}

- (_Bool)SaveXmlFile:(id)arg1;
- (_Bool)SaveRsaDerFile:(id)arg1;
- (_Bool)SaveOpenSslPemFile:(id)arg1;
- (_Bool)SaveOpenSslDerFile:(id)arg1;
- (_Bool)SaveLastError:(id)arg1;
- (_Bool)LoadXmlFile:(id)arg1;
- (_Bool)LoadXml:(id)arg1;
- (_Bool)LoadRsaDerFile:(id)arg1;
- (_Bool)LoadRsaDer:(id)arg1;
- (_Bool)LoadPkcs1Pem:(id)arg1;
- (_Bool)LoadOpenSslPemFile:(id)arg1;
- (_Bool)LoadOpenSslPem:(id)arg1;
- (_Bool)LoadOpenSslDerFile:(id)arg1;
- (_Bool)LoadOpenSslDer:(id)arg1;
- (_Bool)LoadBase64:(id)arg1;
- (id)GetXml;
- (id)GetRsaDer;
- (id)GetPkcs8ENC:(id)arg1;
- (id)GetPkcs1ENC:(id)arg1;
- (id)GetOpenSslPem;
- (id)GetOpenSslDer;
@property(readonly, copy, nonatomic) NSString *Version;
@property(nonatomic) _Bool VerboseLogging;
@property(nonatomic) _Bool LastMethodSuccess;
@property(readonly, copy, nonatomic) NSString *LastErrorXml;
@property(readonly, copy, nonatomic) NSString *LastErrorText;
@property(readonly, copy, nonatomic) NSString *LastErrorHtml;
@property(readonly, copy, nonatomic) NSString *KeyType;
@property(copy, nonatomic) NSString *DebugLogFilePath;
- (id)stringWithUtf8:(const char *)arg1;
- (void)clearCppImplObj;
- (void)setCppImplObj:(void *)arg1;
- (void *)CppImplObj;
- (void)dispose;
- (void)dealloc;
- (id)init;

@end

