//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGPageViewController.h"

__attribute__((visibility("hidden")))
@interface CloudPageViewController : TGPageViewController
{
    int _filesCount;
    int _folderCount;
    int _hiddenItemsCount;
    id <TGSafeArray> _fileListForViewers;
}

@property(retain, nonatomic) id <TGSafeArray> fileListForViewers; // @synthesize fileListForViewers=_fileListForViewers;
- (void).cxx_destruct;
- (id)itemsForBarMenuManager:(id)arg1;
- (id)itemsForPanelMenuManager:(id)arg1;
- (void)newItemArrive:(id)arg1;
- (void)actionTouched;
- (void)setDefaultMenuStates;
- (void)updateEditingToolbar;
- (void)openItem:(id)arg1 withViewerName:(id)arg2;
- (void)browserView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)previewingControllerForIndexPath:(id)arg1;
- (void)hideLoadingProgress;
- (_Bool)showLoadingProgress;
- (void)browserViewRequireToLoadingThumbnailIfNeeds:(id)arg1 atIndexPath:(id)arg2;
- (void)reloadItem:(id)arg1;
- (void)insertFilesAndDirectoryFromPasteboard;
- (void)copyFilesAndDirectoryFromPasteboard;
- (void)moveFilesAndDirectoryFromPasteboard;
- (void)_loadThumbnails;
- (void)loadFilesWithSortMode:(int)arg1;
- (void)reloadFilesAndFolders:(id)arg1;
- (void)renameView:(id)arg1 completeWithName:(id)arg2;
- (_Bool)renameView:(id)arg1 checkIfNameExisted:(id)arg2;
- (void)renameTouched;
- (void)setCurrentPath:(id)arg1;
- (void)doOpenPropertiesSelectedIndexPath:(id)arg1 fromSrcRect:(struct CGRect)arg2 srcView:(id)arg3;
- (void)performActionForMenuWithIdentifier:(id)arg1 sourceView:(id)arg2 sourceRect:(struct CGRect)arg3;
- (void)downloadSelectedFilesAndFolders;
- (void)loadFilesWithSortModeIfNeeds:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteSelectedItems;
- (void)didNewFolderAction:(id)arg1 success:(_Bool)arg2 type:(_Bool)arg3 files:(id)arg4;
- (_Bool)newFolder:(id)arg1 checkIfDirNameExisted:(id)arg2;
- (void)updateModifiedDate;
- (void)newFolder:(id)arg1 completeWithName:(id)arg2;
- (void)NewEmptyFile:(id)arg1 completeWithName:(id)arg2;
- (_Bool)NewEmptyFile:(id)arg1 checkIfNameExisted:(id)arg2;
- (id)doEraseSelectedIndexPaths:(id)arg1;
- (id)doTrashSelectedIndexPaths:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)browserViewDidBeginLoading:(id)arg1;
- (void)doLoadingPage;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

