//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface ColorView : UIView
{
    _Bool _isSelected;
    UIColor *color;
}

@property(retain, nonatomic) UIColor *color; // @synthesize color;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withColor:(id)arg2;

@end

