//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface CustomValueSelectorViewController : TGThemeTableViewController
{
    _Bool _multiple;
    NSArray *_values;
    NSArray *_display;
    NSString *_name;
    NSString *_display_name;
    NSArray *_selected;
    id <CustomValueSelectorViewControllerDelegate> _delegate;
}

@property(nonatomic) _Bool multiple; // @synthesize multiple=_multiple;
@property(nonatomic) __weak id <CustomValueSelectorViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *selected; // @synthesize selected=_selected;
@property(retain, nonatomic) NSString *display_name; // @synthesize display_name=_display_name;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSArray *display; // @synthesize display=_display;
@property(retain, nonatomic) NSArray *values; // @synthesize values=_values;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

