//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CustomValueSelectorViewController, NSArray, NSString;

@protocol CustomValueSelectorViewControllerDelegate <NSObject>
- (void)customValueSelectorViewControllerChanged:(CustomValueSelectorViewController *)arg1 values:(NSArray *)arg2 selected:(NSArray *)arg3 name:(NSString *)arg4;
@end

