//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DLAVAlertViewTextControlTheme.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface DLAVAlertViewButtonTheme : DLAVAlertViewTextControlTheme
{
    UIColor *_textShadowColor;
    double _textShadowOpacity;
    double _textShadowRadius;
    struct CGSize _textShadowOffset;
}

@property(nonatomic) struct CGSize textShadowOffset; // @synthesize textShadowOffset=_textShadowOffset;
@property(nonatomic) double textShadowRadius; // @synthesize textShadowRadius=_textShadowRadius;
@property(nonatomic) double textShadowOpacity; // @synthesize textShadowOpacity=_textShadowOpacity;
@property(retain, nonatomic) UIColor *textShadowColor; // @synthesize textShadowColor=_textShadowColor;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

