//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DLAVAlertViewTextControlTheme.h"

__attribute__((visibility("hidden")))
@interface DLAVAlertViewTextFieldTheme : DLAVAlertViewTextControlTheme
{
    long long _textAlignment;
}

@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

