//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class DLAVAlertView, NSMutableArray, NSObject<OS_dispatch_queue>, NSString, UITapGestureRecognizer, UIView, UIWindow;

__attribute__((visibility("hidden")))
@interface DLAVAlertViewController : UIViewController <UITextFieldDelegate>
{
    NSObject<OS_dispatch_queue> *smooth_animation_queue;
    _Bool _visible;
    NSMutableArray *_alertViews;
    DLAVAlertView *_currentAlertView;
    UIWindow *_alertWindow;
    UIView *_backgroundView;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

+ (id)sharedController;
@property(nonatomic, getter=isVisible) _Bool visible; // @synthesize visible=_visible;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIWindow *alertWindow; // @synthesize alertWindow=_alertWindow;
@property(retain, nonatomic) DLAVAlertView *currentAlertView; // @synthesize currentAlertView=_currentAlertView;
@property(retain, nonatomic) NSMutableArray *alertViews; // @synthesize alertViews=_alertViews;
- (void).cxx_destruct;
- (void)dismiss:(id)arg1;
- (void)hideBackgroundViewWithCompletion:(CDUnknownBlockType)arg1;
- (void)showBackgroundViewWithCompletion:(CDUnknownBlockType)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (struct CGRect)frameForOrientation:(long long)arg1;
- (void)windowsWithLevel:(double)arg1 block:(CDUnknownBlockType)arg2;
- (id)lastWindowWithLevel:(double)arg1;
- (id)firstWindowWithLevel:(double)arg1;
- (void)removeAlertView:(id)arg1;
- (void)addAlertView:(id)arg1;
- (void)setBackdropColor:(id)arg1;
- (id)animationQueue;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

