//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DLSFTPRequest.h"

@class NSArray, NSString;

@interface DLSFTPListFilesRequest : DLSFTPRequest
{
    NSString *_directoryPath;
    NSArray *_fileList;
}

@property(copy, nonatomic) NSArray *fileList; // @synthesize fileList=_fileList;
@property(copy, nonatomic) NSString *directoryPath; // @synthesize directoryPath=_directoryPath;
- (void).cxx_destruct;
- (void)succeed;
- (void)start;
- (id)initWithDirectoryPath:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;

@end

