//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DLSFTPRequest.h"

@class DLSFTPFile, NSDate, NSObject<OS_dispatch_io>, NSObject<OS_dispatch_semaphore>, NSObject<OS_dispatch_source>, NSString;

@interface DLSFTPDownloadRequest : DLSFTPRequest
{
    _Bool _shouldResume;
    NSObject<OS_dispatch_source> *_progressSource;
    NSObject<OS_dispatch_io> *_channel;
    NSObject<OS_dispatch_semaphore> *_semaphore;
    CDUnknownBlockType _progressBlock;
    NSString *_remotePath;
    NSString *_localPath;
    NSDate *_startTime;
    NSDate *_finishTime;
    DLSFTPFile *_downloadedFile;
    struct _LIBSSH2_SFTP_HANDLE *_handle;
}

@property(nonatomic) struct _LIBSSH2_SFTP_HANDLE *handle; // @synthesize handle=_handle;
@property(nonatomic) _Bool shouldResume; // @synthesize shouldResume=_shouldResume;
@property(retain, nonatomic) DLSFTPFile *downloadedFile; // @synthesize downloadedFile=_downloadedFile;
@property(retain, nonatomic) NSDate *finishTime; // @synthesize finishTime=_finishTime;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *localPath; // @synthesize localPath=_localPath;
@property(copy, nonatomic) NSString *remotePath; // @synthesize remotePath=_remotePath;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *semaphore; // @synthesize semaphore=_semaphore;
@property(retain, nonatomic) NSObject<OS_dispatch_io> *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *progressSource; // @synthesize progressSource=_progressSource;
- (void).cxx_destruct;
- (void)succeed;
- (void)downloadFailed;
- (void)downloadFinished;
- (void)downloadChunk;
- (void)start;
- (_Bool)openFileHandle;
- (void)dealloc;
- (id)initWithRemotePath:(id)arg1 localPath:(id)arg2 resume:(_Bool)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5 progressBlock:(CDUnknownBlockType)arg6;

@end

