//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DLSFTPRequest.h"

@class DLSFTPFile, NSString;

@interface DLSFTPMoveRenameRequest : DLSFTPRequest
{
    NSString *_sourcePath;
    NSString *_destinationPath;
    DLSFTPFile *_destinationItem;
}

@property(retain, nonatomic) DLSFTPFile *destinationItem; // @synthesize destinationItem=_destinationItem;
@property(copy, nonatomic) NSString *destinationPath; // @synthesize destinationPath=_destinationPath;
@property(copy, nonatomic) NSString *sourcePath; // @synthesize sourcePath=_sourcePath;
- (void).cxx_destruct;
- (void)succeed;
- (void)start;
- (id)initWithSourcePath:(id)arg1 destinationPath:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;

@end

