//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary, NSString;

@interface DLSFTPFile : NSObject <NSCoding>
{
    NSString *_path;
    NSMutableDictionary *_attributes;
}

@property(readonly, nonatomic) NSMutableDictionary *attributes; // @synthesize attributes=_attributes;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)filename;
- (long long)compare:(id)arg1;
- (id)description;
- (id)initWithPath:(id)arg1 attributes:(id)arg2;

@end

