//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DLSFTPRequest.h"

@class DLSFTPFile, NSString;

@interface DLSFTPSetFilePermissionRequest : DLSFTPRequest
{
    NSString *_directoryPath;
    DLSFTPFile *_createdDirectory;
    unsigned long long _permissions;
}

@property(nonatomic) unsigned long long permissions; // @synthesize permissions=_permissions;
@property(retain, nonatomic) DLSFTPFile *createdDirectory; // @synthesize createdDirectory=_createdDirectory;
@property(copy, nonatomic) NSString *directoryPath; // @synthesize directoryPath=_directoryPath;
- (void).cxx_destruct;
- (void)succeed;
- (void)start;
- (id)initWithPath:(id)arg1 withPermission:(unsigned long long)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;

@end

