//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextFieldDelegate.h"

@class DOAutocompleteTextField, NSString;

@protocol DOAutocompleteTextFieldDelegate <UITextFieldDelegate>

@optional
- (NSString *)textField:(DOAutocompleteTextField *)arg1 completionForPrefix:(NSString *)arg2;
@end

