//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface DropBoxJSON : NSObject
{
}

+ (id)asciiEscapeWithString:(id)arg1;
+ (id)utf8StringWithData:(id)arg1;
+ (id)jsonDataWithJsonObj:(id)arg1;
+ (id)serializeArgString:(id)arg1;

@end

