//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

#import "UITextFieldDelegate.h"

@class MediaFileItem, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface EditMusicFileViewController : TGThemeTableViewController <UITextFieldDelegate>
{
    int _defaultIndex;
    MediaFileItem *_file;
    NSString *_textTrackNumber;
    NSString *_textTitle;
    NSString *_textArtist;
    NSString *_textAlbum;
    NSString *_textYear;
    NSString *_textSeriesName;
    NSString *_textAlbumArtist;
    NSArray *_allSections;
}

@property(retain, nonatomic) NSArray *allSections; // @synthesize allSections=_allSections;
@property(retain, nonatomic) NSString *textAlbumArtist; // @synthesize textAlbumArtist=_textAlbumArtist;
@property(retain, nonatomic) NSString *textSeriesName; // @synthesize textSeriesName=_textSeriesName;
@property(retain, nonatomic) NSString *textYear; // @synthesize textYear=_textYear;
@property(retain, nonatomic) NSString *textAlbum; // @synthesize textAlbum=_textAlbum;
@property(retain, nonatomic) NSString *textArtist; // @synthesize textArtist=_textArtist;
@property(retain, nonatomic) NSString *textTitle; // @synthesize textTitle=_textTitle;
@property(retain, nonatomic) NSString *textTrackNumber; // @synthesize textTrackNumber=_textTrackNumber;
@property(nonatomic) int defaultIndex; // @synthesize defaultIndex=_defaultIndex;
@property(retain, nonatomic) MediaFileItem *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)saveValues:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

