//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

#import "TextVIewTableViewCell.h"

@class FileItem, NSString, UIViewController<TGViewerProtocol>;

__attribute__((visibility("hidden")))
@interface ErrorZXViewController : TGThemeTableViewController <TextVIewTableViewCell>
{
    NSString *_error;
    NSString *_fileName;
    NSString *_hexDump;
    FileItem *_openWithFileItem;
    UIViewController<TGViewerProtocol> *_parentVc;
}

@property(nonatomic) __weak UIViewController<TGViewerProtocol> *parentVc; // @synthesize parentVc=_parentVc;
@property(nonatomic) __weak FileItem *openWithFileItem; // @synthesize openWithFileItem=_openWithFileItem;
@property(retain, nonatomic) NSString *hexDump; // @synthesize hexDump=_hexDump;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSString *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (void)textViewTableViewCellDidBeginEditing:(id)arg1;
- (_Bool)textViewTableViewCell:(id)arg1 textDidChange:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)openItem:(id)arg1 withViewerName:(id)arg2;
- (void)openWithClicked:(id)arg1;
- (void)doneclicked;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

