//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FICEntity.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ExtensionItem : NSObject <FICEntity>
{
    NSString *_UUID;
    NSString *_name;
    NSString *_lname;
}

@property(retain, nonatomic) NSString *lname; // @synthesize lname=_lname;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (CDUnknownBlockType)drawingBlockForImage:(id)arg1 withFormatName:(id)arg2;
- (id)sourceImageURLWithFormatName:(id)arg1;
@property(readonly, copy, nonatomic) NSString *sourceImageUUID;
@property(readonly, copy, nonatomic) NSString *UUID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

