//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FICImageFormat, NSString, NSURL, UIImage;

@protocol FICEntity <NSObject>
@property(readonly, copy, nonatomic) NSString *sourceImageUUID;
@property(readonly, copy, nonatomic) NSString *UUID;
- (void (^)(struct CGContext *, struct CGSize))drawingBlockForImage:(UIImage *)arg1 withFormatName:(NSString *)arg2;
- (NSURL *)sourceImageURLWithFormatName:(NSString *)arg1;

@optional
- (UIImage *)imageForFormat:(FICImageFormat *)arg1;
@end

