//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FICEntity.h"
#import "NSItemProviderWriting.h"

@class ExtensionItem, NSArray, NSDate, NSString;

__attribute__((visibility("hidden")))
@interface FileItem : NSObject <FICEntity, NSItemProviderWriting>
{
    NSString *filePath;
    NSString *_UUID;
    _Bool isSelected;
    _Bool _isHiddenItem;
    _Bool _isExcutable;
    int fileType;
    unsigned long long fileSize;
    NSDate *fileDate;
    long long fileTagValue;
    NSString *_applicationName;
    NSDate *_fileCreationDate;
    FileItem *_sourceItem;
    long long _fileID;
    ExtensionItem *_extensionItem;
    FileItem *_destination;
    NSString *_aFileName;
    NSString *_aDateString;
    NSString *_aFileSizeString;
    NSString *_aFilePermissionString;
    unsigned long long _perm;
}

+ (id)iconForFileType:(int)arg1 isExecutable:(_Bool)arg2;
+ (id)initWithFilePath:(id)arg1 attribute:(id)arg2;
@property(nonatomic) unsigned long long perm; // @synthesize perm=_perm;
@property(retain, nonatomic) NSString *aFilePermissionString; // @synthesize aFilePermissionString=_aFilePermissionString;
@property(retain, nonatomic) NSString *aFileSizeString; // @synthesize aFileSizeString=_aFileSizeString;
@property(retain, nonatomic) NSString *aDateString; // @synthesize aDateString=_aDateString;
@property(retain, nonatomic) NSString *aFileName; // @synthesize aFileName=_aFileName;
@property(retain, nonatomic) FileItem *destination; // @synthesize destination=_destination;
@property(retain, nonatomic) ExtensionItem *extensionItem; // @synthesize extensionItem=_extensionItem;
@property(nonatomic) long long fileID; // @synthesize fileID=_fileID;
@property(retain, nonatomic) FileItem *sourceItem; // @synthesize sourceItem=_sourceItem;
@property(nonatomic) _Bool isExcutable; // @synthesize isExcutable=_isExcutable;
@property(nonatomic) _Bool isHiddenItem; // @synthesize isHiddenItem=_isHiddenItem;
@property(retain, nonatomic) NSDate *fileCreationDate; // @synthesize fileCreationDate=_fileCreationDate;
@property(retain, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected;
@property(nonatomic) long long fileTagValue; // @synthesize fileTagValue;
@property(nonatomic) int fileType; // @synthesize fileType;
@property(retain, nonatomic) NSDate *fileDate; // @synthesize fileDate;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize;
- (void).cxx_destruct;
- (CDUnknownBlockType)drawingBlockForImage:(id)arg1 withFormatName:(id)arg2;
- (id)thumbIconPath;
- (id)sourceImageURLWithFormatName:(id)arg1;
@property(readonly, copy, nonatomic) NSString *sourceImageUUID;
- (_Bool)isLink;
@property(readonly, copy, nonatomic) NSString *UUID;
- (long long)accessoryType;
- (id)icon;
- (id)dateString;
- (id)fileName;
- (_Bool)isDirectory;
- (id)fileExtension;
- (id)permissionString;
- (id)fileSizeString;
- (_Bool)isEqual:(id)arg1;
- (id)filePath;
- (void)setFilePath:(id)arg1;
- (void)setFilePath:(id)arg1 attribute:(id)arg2;
- (id)dimensionString;
- (id)mimeType;
- (id)UTType;
- (const char *)UTF8String;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSArray *writableTypeIdentifiersForItemProvider;

@end

