//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

#import "UIAlertViewDelegate.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface FileAssocViewController : TGThemeTableViewController <UIAlertViewDelegate>
{
    NSMutableArray *__allExtensions;
    NSDictionary *_viewers;
    NSMutableDictionary *_allAppItems;
}

@property(retain, nonatomic) NSMutableDictionary *allAppItems; // @synthesize allAppItems=_allAppItems;
@property(retain, nonatomic) NSDictionary *viewers; // @synthesize viewers=_viewers;
@property(retain, nonatomic) NSMutableArray *_allExtensions; // @synthesize _allExtensions=__allExtensions;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addNew;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

