//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIScrollView, UIView;

__attribute__((visibility("hidden")))
@interface FloatingToolbarHandle : NSObject <UIGestureRecognizerDelegate>
{
    UIView *floatingHeaderView;
    UIScrollView *scrollView;
    _Bool _IBShouldShowHeaderViewWhenScrollUp;
    _Bool _IBHeaderBeginHide;
    _Bool _stop;
    _Bool _FloatingHeaderEnabled;
    int _barHeight;
    double _currentOffset;
}

@property(nonatomic) double currentOffset; // @synthesize currentOffset=_currentOffset;
@property(nonatomic) int barHeight; // @synthesize barHeight=_barHeight;
@property(nonatomic) _Bool FloatingHeaderEnabled; // @synthesize FloatingHeaderEnabled=_FloatingHeaderEnabled;
@property(nonatomic) _Bool stop; // @synthesize stop=_stop;
@property(nonatomic) _Bool IBHeaderBeginHide; // @synthesize IBHeaderBeginHide=_IBHeaderBeginHide;
@property(nonatomic) _Bool IBShouldShowHeaderViewWhenScrollUp; // @synthesize IBShouldShowHeaderViewWhenScrollUp=_IBShouldShowHeaderViewWhenScrollUp;
- (void).cxx_destruct;
- (void)___svDidScrollToContentOffset:(struct CGPoint)arg1;
- (void)___svEndDecelerating;
- (void)___svEndDraggingAndWillDecelerating:(_Bool)arg1;
- (void)completeHeaderViewAnimation;
- (id)beginBlockHeaderViewPositionInView:(id)arg1;
- (void)endBlockHeaderViewPosition:(id)arg1;
- (void)completeHeaderViewAnimationNoAnimation;
- (void)_handleNewHeaderView;
- (void)_handlePreviousHeaderView;
@property(nonatomic) _Bool shouldShowHeaderViewWhenScrollUp;
- (void)setFloatingFooterView:(id)arg1;
- (void)setFloatingHeaderView:(id)arg1 forView:(id)arg2;
- (_Bool)isFloatingHeaderEnabled;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

