//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface GDCredentialManager : NSObject
{
    NSDictionary *_keyedClientCredentials;
    NSObject<OS_dispatch_queue> *_isolationQueue;
}

+ (id)sharedCredentialManager;
+ (void)setSharedCredentialManager:(id)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *isolationQueue; // @synthesize isolationQueue=_isolationQueue;
@property(copy, nonatomic) NSDictionary *keyedClientCredentials; // @synthesize keyedClientCredentials=_keyedClientCredentials;
- (void).cxx_destruct;
- (id)loadCredentialsForAccount:(id)arg1;
- (void)saveCredentials:(id)arg1 forAccount:(id)arg2;
- (id)clientCredentialsForAccount:(id)arg1;
- (void)mutateClientCredentialsForAccount:(id)arg1 asyncMutationBlock:(CDUnknownBlockType)arg2;
- (void)removeCredential:(id)arg1 forAccount:(id)arg2;
- (void)updateCredential:(id)arg1;
- (void)addCredential:(id)arg1 forAccount:(id)arg2;
- (id)init;

@end

