//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDDictionaryBackedObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface GDDropboxMetadata : GDDictionaryBackedObject
{
    NSDate *_modifiedDate;
}

+ (id)canonicalPathForPath:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDate *modifiedDate; // @synthesize modifiedDate=_modifiedDate;
@property(readonly, nonatomic) _Bool isDeleted;
- (id)directoryContentsHash;
@property(readonly, nonatomic) long long fileSize;
@property(readonly, nonatomic) _Bool isDirectory;
@property(readonly, copy, nonatomic) NSString *rev;
@property(readonly, copy, nonatomic) NSString *path;
- (id)detailsInformation;
- (id)initWithDictionary:(id)arg1;

@end

