//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDDictionaryBackedObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface GDDropboxUploadState : GDDictionaryBackedObject
{
    long long _offset;
}

@property(nonatomic) long long offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) NSDate *expiryDate;
@property(readonly, copy, nonatomic) NSString *uploadID;
- (id)initWithDictionary:(id)arg1;

@end

