//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSManagedObjectContext, NSManagedObjectModel, NSNumber, NSPersistentStoreCoordinator, NSPredicate, NSURL;

__attribute__((visibility("hidden")))
@interface GDFileManagerDataCacheCoordinator : NSObject
{
    NSManagedObjectModel *__managedObjectModel;
    NSPersistentStoreCoordinator *__persistentStoreCoordinator;
    NSManagedObjectContext *__managedObjectContext;
    NSURL *_fileCacheDirectoryURL;
    NSPredicate *_sourceAndVersionIdentifierPredicateTemplate;
    NSPredicate *_sourcePredicateTemplate;
}

+ (id)sharedCacheCoordinator;
@property(readonly, nonatomic) NSPredicate *sourcePredicateTemplate; // @synthesize sourcePredicateTemplate=_sourcePredicateTemplate;
@property(readonly, nonatomic) NSPredicate *sourceAndVersionIdentiferPredicateTemplate; // @synthesize sourceAndVersionIdentiferPredicateTemplate=_sourceAndVersionIdentifierPredicateTemplate;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=__managedObjectContext;
@property(retain, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=__persistentStoreCoordinator;
- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *fileCacheDirectoryURL; // @synthesize fileCacheDirectoryURL=_fileCacheDirectoryURL;
- (void)_saveContext;
- (void)asyncSaveContext;
- (void)saveContext;
@property(readonly, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=__managedObjectModel;
- (void)resumePendingUploads;
- (void)persistentUploadOperation:(id)arg1 failedWithError:(id)arg2;
- (void)persistentUploadOperation:(id)arg1 completedSuccessfullyWithMetadata:(id)arg2;
- (void)persistentUploadOperation:(id)arg1 newUploadState:(id)arg2;
- (void)registerPersistentUploadOperation:(id)arg1;
- (void)_trimCache;
- (void)asyncTrimCacheIfNeeded;
- (void)setObject:(id)arg1 forMetadataKey:(id)arg2;
- (id)objectForMetadataKey:(id)arg1;
@property(retain, nonatomic) NSNumber *maximumCacheSize;
@property(retain, nonatomic) NSNumber *cacheSize;
- (void)deleteCachedFile:(id)arg1;
- (_Bool)createCacheDirectory;
- (_Bool)moveLocalURLIntoFileCache:(id)arg1 filename:(id)arg2 cacheFilePath:(id *)arg3 error:(id *)arg4;
- (_Bool)copyLocalURLIntoFileCache:(id)arg1 filename:(id)arg2 cacheFilePath:(id *)arg3 error:(id *)arg4;
- (id)createFileCachePathForFilename:(id)arg1 error:(id *)arg2;
- (void)removeAllItems;
- (void)addCacheFilePath:(id)arg1 intoCacheForURL:(id)arg2 metadata:(id)arg3;
- (id)moveLocalURL:(id)arg1 intoCacheForURL:(id)arg2 metadata:(id)arg3;
- (id)cacheURLForURL:(id)arg1 versionIdentifier:(id)arg2 cachedMetadata:(id *)arg3;
- (id)cacheURLForURL:(id)arg1 cachedMetadata:(id *)arg2;
- (id)init;

@end

