//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GDFileServiceManager, NSCache, NSOperationQueue;

__attribute__((visibility("hidden")))
@interface GDFileManager : NSObject
{
    id <GDMetadataCache> _sessionCache;
    GDFileServiceManager *_fileServiceManager;
    unsigned long long _defaultCachePolicy;
    NSOperationQueue *_operationQueue;
    NSCache *_directoryResultsCache;
    NSCache *_multimapDirectoryResultsCache;
    id <GDMetadataCache> _layeredCache;
}

+ (void)enqueueLowPriorityFileManagerOperation:(id)arg1;
+ (id)cachedMetadataForCanonicalURL:(id)arg1;
+ (void)cacheMetadata:(id)arg1 forCanonicalURL:(id)arg2;
+ (id)sharedFileCache;
+ (void)setSharedFileCache:(id)arg1;
+ (id)sharedMetadataCache;
+ (void)setSharedMetadataCache:(id)arg1;
+ (id)sharedManager;
+ (void)initialize;
@property(retain, nonatomic) id <GDMetadataCache> layeredCache; // @synthesize layeredCache=_layeredCache;
@property(retain, nonatomic) NSCache *multimapDirectoryResultsCache; // @synthesize multimapDirectoryResultsCache=_multimapDirectoryResultsCache;
@property(retain, nonatomic) NSCache *directoryResultsCache; // @synthesize directoryResultsCache=_directoryResultsCache;
@property(readonly, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(nonatomic) unsigned long long defaultCachePolicy; // @synthesize defaultCachePolicy=_defaultCachePolicy;
@property(readonly, nonatomic) GDFileServiceManager *fileServiceManager; // @synthesize fileServiceManager=_fileServiceManager;
@property(retain, nonatomic) id <GDMetadataCache> sessionCache; // @synthesize sessionCache=_sessionCache;
- (void).cxx_destruct;
- (id)addLocalFileServiceSessionForLocalURL:(id)arg1 name:(id)arg2;
- (void)_updateLayeredCache;
- (void)sharedMetadataCacheDidChange:(id)arg1;
- (void)resetSessionCache;
- (id)persistentUploadOperationFromSourceFileURL:(id)arg1 options:(unsigned long long)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)uploadOperationFromSourceFileURL:(id)arg1 options:(unsigned long long)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)enqueueLowPriorityFileManagerOperation:(id)arg1;
- (void)enqueueFileManagerOperation:(id)arg1;
- (id)cacheURLForURL:(id)arg1 versionIdentifier:(id)arg2 cachedMetadata:(id *)arg3;
- (id)cacheURLForURL:(id)arg1 cachedMetadata:(id *)arg2;
- (id)cachedDownloadOperationFromSourceURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)downloadOperationFromSourceURL:(id)arg1 toLocalFileURL:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)resolveAlias:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)createDirectoryName:(id)arg1 parentURL:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)createAliasForURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)_findItemsMatchingPath:(id)arg1 relativeToURL:(id)arg2 multimap:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)findItemsMatchingPath:(id)arg1 relativeToURL:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)searchItemsMatchingName:(id)arg1 relativeToURL:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)cacheClientMetadataContents:(id)arg1 forURL:(id)arg2;
- (void)cacheClientMetadata:(id)arg1 addToParent:(_Bool)arg2;
- (void)cacheClientMetadata:(id)arg1;
- (id)clientMetadataForURLMetadata:(id)arg1 clientURL:(id)arg2 fileServiceSession:(id)arg3 cache:(id)arg4;
- (void)moveFileAtURL:(id)arg1 toParentURL:(id)arg2 name:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)copyFileAtURL:(id)arg1 toParentURL:(id)arg2 name:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)deleteURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getLatestVersionIdentifierForURL:(id)arg1 cachePolicy:(unsigned long long)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)getLatestVersionIdentifierForURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)createSharedLink:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getSharedLink:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)updateSharedLink:(id)arg1 withAttributes:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (_Bool)supportSharedLink:(id)arg1;
- (void)getMetadataForURL:(id)arg1 cachePolicy:(unsigned long long)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)getMetadataForURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getContentsOfDirectoryAtURL:(id)arg1 cachePolicy:(unsigned long long)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)setFilePermissionsForURL:(id)arg1 withPermissions:(int)arg2 recursive:(_Bool)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getContentsOfDirectoryAtURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (_Bool)handleOpenURL:(id)arg1;
- (id)sessionNameForURL:(id)arg1;
- (id)uniqueRootURLForURLScheme:(id)arg1 error:(id *)arg2;
- (id)fileServiceSessionForURL:(id)arg1;
- (id)fileServiceForURLScheme:(id)arg1;
- (id)initWithFileServiceManager:(id)arg1;
- (id)init;
- (void)dealloc;

@end

