//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDParentOperation.h"

@class GDFileManager, GDFileManagerUploadState, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface GDFileManagerUploadOperation : GDParentOperation
{
    NSURL *_destinationURL;
    NSString *_mimeType;
    unsigned long long _uploadMode;
    GDFileManager *_fileManager;
    NSURL *_sourceURL;
    NSString *_destinationFilename;
    NSString *_parentVersionID;
    NSURL *_parentFolderURL;
    unsigned long long _options;
    GDFileManagerUploadState *_uploadState;
    CDUnknownBlockType _uploadStateHandler;
    CDUnknownBlockType _uploadProgressBlock;
    CDUnknownBlockType _success;
    CDUnknownBlockType _failure;
}

@property(readonly, nonatomic) CDUnknownBlockType failure; // @synthesize failure=_failure;
@property(readonly, nonatomic) CDUnknownBlockType success; // @synthesize success=_success;
@property(copy, nonatomic) CDUnknownBlockType uploadProgressBlock; // @synthesize uploadProgressBlock=_uploadProgressBlock;
@property(copy, nonatomic) CDUnknownBlockType uploadStateHandler; // @synthesize uploadStateHandler=_uploadStateHandler;
@property(retain, nonatomic) GDFileManagerUploadState *uploadState; // @synthesize uploadState=_uploadState;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(readonly, nonatomic) NSURL *parentFolderURL; // @synthesize parentFolderURL=_parentFolderURL;
@property(readonly, copy, nonatomic) NSString *parentVersionID; // @synthesize parentVersionID=_parentVersionID;
@property(readonly, copy, nonatomic) NSString *destinationFilename; // @synthesize destinationFilename=_destinationFilename;
@property(retain, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(readonly, nonatomic) GDFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(nonatomic) unsigned long long uploadMode; // @synthesize uploadMode=_uploadMode;
- (void).cxx_destruct;
- (void)startChildUploadOperationWithSessionURL:(id)arg1 configurationBlock:(CDUnknownBlockType)arg2;
- (id)filenameAvoidingConflictsWithExistingContents:(id)arg1 fromSession:(id)arg2;
- (void)startUpload;
- (void)main;
@property(readonly, copy, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(readonly, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
- (void)setDestinationURL:(id)arg1 mimeType:(id)arg2 parentVersionID:(id)arg3;
- (void)createNewFileWithFilename:(id)arg1 mimeType:(id)arg2 parentFolderURL:(id)arg3;
- (id)initWithFileManager:(id)arg1 sourceFileURL:(id)arg2 options:(unsigned long long)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;

@end

