//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_GDFileManagerPendingUpload.h"

@class GDFileManagerPersistentUploadOperation, GDFileManagerUploadState, GDPersistentUploadDestination, NSURL;

__attribute__((visibility("hidden")))
@interface GDFileManagerPendingUpload : _GDFileManagerPendingUpload
{
    GDFileManagerPersistentUploadOperation *uploadOperation;
}

@property(nonatomic) __weak GDFileManagerPersistentUploadOperation *uploadOperation; // @synthesize uploadOperation;
- (void).cxx_destruct;
- (void)prepareForDeletion;

// Remaining properties
@property(retain, nonatomic) NSURL *sourceURL; // @dynamic sourceURL;
@property(retain, nonatomic) GDPersistentUploadDestination *uploadDestination; // @dynamic uploadDestination;
@property(retain, nonatomic) GDFileManagerUploadState *uploadState; // @dynamic uploadState;

@end

