//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface GDFileManagerUploadState : NSObject <NSCoding>
{
    NSString *_parentVersionID;
    id <NSCoding> _uploadState;
    NSURL *_uploadURL;
    NSString *_mimeType;
    NSDictionary *_extraState;
}

@property(readonly, nonatomic) NSDictionary *extraState; // @synthesize extraState=_extraState;
@property(readonly, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(readonly, nonatomic) NSURL *uploadURL; // @synthesize uploadURL=_uploadURL;
@property(readonly, nonatomic) id <NSCoding> uploadState; // @synthesize uploadState=_uploadState;
@property(readonly, nonatomic) NSString *parentVersionID; // @synthesize parentVersionID=_parentVersionID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) NSURL *fileServiceSessionURL;
- (id)initWithUploadState:(id)arg1 mimeType:(id)arg2 uploadURL:(id)arg3 parentVersionID:(id)arg4 extraState:(id)arg5;
- (id)initWithUploadState:(id)arg1 mimeType:(id)arg2 uploadURL:(id)arg3 parentVersionID:(id)arg4;

@end

