//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDParentOperation.h"

@class GDFTPCredential, NSObject<OS_dispatch_queue>, NSString, TGCkoFtp2;

__attribute__((visibility("hidden")))
@interface GDFTPDownloadOperation : GDParentOperation
{
    _Bool aborted;
    _Bool isDownloading;
    TGCkoFtp2 *_manager;
    GDFTPCredential *_credential;
    CDUnknownBlockType _failureBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _progressBlock;
    NSString *_localPath;
    NSString *_remotePath;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSString *remotePath; // @synthesize remotePath=_remotePath;
@property(retain, nonatomic) NSString *localPath; // @synthesize localPath=_localPath;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(retain, nonatomic) GDFTPCredential *credential; // @synthesize credential=_credential;
@property(retain, nonatomic) TGCkoFtp2 *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancel;
- (void)didAborted;
- (void)main;
- (id)initWithManager:(id)arg1 localPath:(id)arg2 remotePath:(id)arg3 queue:(id)arg4;

@end

