//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDHTTPClient.h"

@class GDFTPCredential, NSObject<OS_dispatch_queue>, NSTimer, TGCkoFtp2;

__attribute__((visibility("hidden")))
@interface GDFTPClient : GDHTTPClient
{
    _Bool _isRequesting;
    TGCkoFtp2 *_manager;
    NSTimer *_timer;
    NSObject<OS_dispatch_queue> *_ftpQueue;
}

@property _Bool isRequesting; // @synthesize isRequesting=_isRequesting;
@property(retain) NSObject<OS_dispatch_queue> *ftpQueue; // @synthesize ftpQueue=_ftpQueue;
@property(retain) NSTimer *timer; // @synthesize timer=_timer;
@property(retain) TGCkoFtp2 *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (id)uploadFile:(id)arg1 mimeType:(id)arg2 toWebDAVPath:(id)arg3 progress:(CDUnknownBlockType)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (id)downloadFile:(id)arg1 intoPath:(id)arg2 progress:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)movePath:(id)arg1 toPath:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)copyPath:(id)arg1 toPath:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)searchAtPath:(id)arg1 withParameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)createPath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)deletePath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getPROPFINDResponseForPath:(id)arg1 depth:(unsigned long long)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)getContentsOfDirectoryAtPath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)execWithBlock:(CDUnknownBlockType)arg1;
- (void)disconnect;
- (void)getMetadataForPath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)setFilePermissionsForPath:(id)arg1 withPermissions:(unsigned long long)arg2 recursive:(_Bool)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)validateFTPServerWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)initWithClientManager:(id)arg1 credential:(id)arg2 baseURL:(id)arg3;

// Remaining properties
@property(retain) GDFTPCredential *credential; // @dynamic credential;

@end

