//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDClientManager.h"

#import "GIDSignInDelegate.h"
#import "GIDSignInUIDelegate.h"

@class GDGoogleDriveAPIToken, NSString, UIViewController;

__attribute__((visibility("hidden")))
@interface GDGoogleDriveClientManager : GDClientManager <GIDSignInUIDelegate, GIDSignInDelegate>
{
    UIViewController *_rootViewController;
    CDUnknownBlockType _success;
    CDUnknownBlockType _fail;
    GDGoogleDriveAPIToken *_apiToken;
}

+ (Class)clientClass;
+ (Class)apiTokenClass;
@property(retain, nonatomic) GDGoogleDriveAPIToken *apiToken; // @synthesize apiToken=_apiToken;
@property(copy, nonatomic) CDUnknownBlockType fail; // @synthesize fail=_fail;
@property(copy, nonatomic) CDUnknownBlockType success; // @synthesize success=_success;
@property(retain, nonatomic) UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void).cxx_destruct;
- (void)validateCredential:(id)arg1 apiToken:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)oauthCodeFromCallbackURL:(id)arg1 error:(id *)arg2;
- (void)linkUserID:(id)arg1 apiToken:(id)arg2 fromController:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)unlink;
- (void)signIn:(id)arg1 didDisconnectWithUser:(id)arg2 withError:(id)arg3;
- (void)signIn:(id)arg1 didSignInForUser:(id)arg2 withError:(id)arg3;
- (void)signIn:(id)arg1 dismissViewController:(id)arg2;
- (void)signIn:(id)arg1 presentViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(retain, nonatomic) GDGoogleDriveAPIToken *defaultAPIToken; // @dynamic defaultAPIToken;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

