//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDFileServiceSession.h"

@class NSFileManager, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface GDLocalFileServiceSession : GDFileServiceSession
{
    NSURL *_localRootURL;
    NSFileManager *_fileManager;
}

+ (void)initialize;
@property(readonly, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(readonly, copy, nonatomic) NSURL *localRootURL; // @synthesize localRootURL=_localRootURL;
- (void).cxx_destruct;
- (id)clientMetadataFromFileURL:(id)arg1 parentURL:(id)arg2 clientURL:(id)arg3;
- (id)clientMetadataFromFileURL:(id)arg1 parentURL:(id)arg2;
- (id)clientMetadataFromFileURL:(id)arg1 clientURL:(id)arg2;
- (id)clientMetadataForMetadataDictionary:(id)arg1 url:(id)arg2;
@property(readonly, copy, nonatomic) NSString *localRootPath;
- (id)filenameFromCanonicalURL:(id)arg1;
- (id)fileURLFromCanonicalURL:(id)arg1;
- (id)absolutePathFromCanonicalURL:(id)arg1;
- (id)cacheURLForURL:(id)arg1 versionIdentifier:(id)arg2 cachedMetadata:(id *)arg3;
- (id)uploadFileURL:(id)arg1 toDestinationURL:(id)arg2 filename:(id)arg3 mimeType:(id)arg4 parentVersionID:(id)arg5 internalUploadState:(id)arg6 uploadStateHandler:(CDUnknownBlockType)arg7 progress:(CDUnknownBlockType)arg8 success:(CDUnknownBlockType)arg9 failure:(CDUnknownBlockType)arg10;
- (id)uploadFileURL:(id)arg1 filename:(id)arg2 mimeType:(id)arg3 toParentFolderURL:(id)arg4 uploadStateHandler:(CDUnknownBlockType)arg5 progress:(CDUnknownBlockType)arg6 success:(CDUnknownBlockType)arg7 failure:(CDUnknownBlockType)arg8;
- (id)uploadFileURL:(id)arg1 mimeType:(id)arg2 toDestinationURL:(id)arg3 parentVersionID:(id)arg4 internalUploadState:(id)arg5 uploadStateHandler:(CDUnknownBlockType)arg6 progress:(CDUnknownBlockType)arg7 success:(CDUnknownBlockType)arg8 failure:(CDUnknownBlockType)arg9;
- (id)downloadURL:(id)arg1 intoFileURL:(id)arg2 fileVersion:(id)arg3 progress:(CDUnknownBlockType)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)moveFileAtURL:(id)arg1 toParentURL:(id)arg2 name:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)copyFileAtURL:(id)arg1 toParentURL:(id)arg2 name:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)deleteURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getContentsOfDirectoryAtURL:(id)arg1 metadataCache:(id)arg2 cachedMetadata:(id)arg3 cachedContents:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)getMetadataForURL:(id)arg1 metadataCache:(id)arg2 cachedMetadata:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)validateAccessWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)initWithName:(id)arg1 localRootURL:(id)arg2 fileService:(id)arg3;
- (id)initWithBaseURL:(id)arg1 fileService:(id)arg2;

@end

