//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDFileService.h"

__attribute__((visibility("hidden")))
@interface GDLocalFileService : GDFileService
{
}

+ (Class)fileServiceSessionClass;
- (id)name;
- (id)iconImage;
- (id)largeIconImage;
- (id)logoImage;
- (id)urlScheme;
- (_Bool)shouldCacheResults;

@end

