//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDParentOperation.h"

@class GDOneDriveClient, GDOneDriveMetadata, GDOneDriveUploadState, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface GDOneDriveChunkedUploadOperation : GDParentOperation
{
    GDOneDriveClient *_client;
    NSString *_sourcePath;
    NSString *_destinationFileID;
    long long _chunkSize;
    GDOneDriveUploadState *_uploadState;
    CDUnknownBlockType _uploadStateHandler;
    CDUnknownBlockType _uploadProgressBlock;
    CDUnknownBlockType _success;
    CDUnknownBlockType _failure;
    GDOneDriveMetadata *_fileMetadata;
    unsigned long long _fileSize;
    NSDictionary *_remoteFileInfo;
}

@property(retain, nonatomic) NSDictionary *remoteFileInfo; // @synthesize remoteFileInfo=_remoteFileInfo;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(retain, nonatomic) GDOneDriveMetadata *fileMetadata; // @synthesize fileMetadata=_fileMetadata;
@property(readonly, nonatomic) CDUnknownBlockType failure; // @synthesize failure=_failure;
@property(readonly, nonatomic) CDUnknownBlockType success; // @synthesize success=_success;
@property(copy, nonatomic) CDUnknownBlockType uploadProgressBlock; // @synthesize uploadProgressBlock=_uploadProgressBlock;
@property(copy, nonatomic) CDUnknownBlockType uploadStateHandler; // @synthesize uploadStateHandler=_uploadStateHandler;
@property(retain, nonatomic) GDOneDriveUploadState *uploadState; // @synthesize uploadState=_uploadState;
@property(nonatomic) long long chunkSize; // @synthesize chunkSize=_chunkSize;
@property(copy, nonatomic) NSString *destinationFileID; // @synthesize destinationFileID=_destinationFileID;
@property(readonly, copy, nonatomic) NSString *sourcePath; // @synthesize sourcePath=_sourcePath;
@property(readonly, nonatomic) GDOneDriveClient *client; // @synthesize client=_client;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *uploadSessionURI;
- (void)getFileMetadata;
- (void)uploadNextChunk;
- (void)createUploadSession;
- (id)pathForFileID:(id)arg1 path:(id)arg2;
- (id)pathForFileID:(id)arg1 path:(id)arg2 name:(id)arg3;
- (id)nomalizeName:(id)arg1;
- (void)createFileAndGetMetadata;
- (void)nextUploadStep;
- (void)main;
- (void)setUploadState:(id)arg1 notifyDelegate:(_Bool)arg2;
- (void)createNewFileWithFilename:(id)arg1 mimeType:(id)arg2 parentFolderID:(id)arg3;
- (void)createNewFileWithFilename:(id)arg1 parentFolderID:(id)arg2;
- (id)initWithClient:(id)arg1 fromLocalPath:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;

@end

