//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDParentOperation.h"

@class DLSFTPConnection, DLSFTPDownloadRequest;

__attribute__((visibility("hidden")))
@interface GDSFTPFileDownloadOperation : GDParentOperation
{
    DLSFTPConnection *_connection;
    DLSFTPDownloadRequest *_request;
    CDUnknownBlockType _failureBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _cancelBlock;
}

@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(retain, nonatomic) DLSFTPDownloadRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) DLSFTPConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancel;
- (void)main;
- (id)initWithRequest:(id)arg1 andConnection:(id)arg2;

@end

