//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDParentOperation.h"

@class MiniSMB, NSString;

__attribute__((visibility("hidden")))
@interface GDSMBUploadOperation : GDParentOperation
{
    int _jobId;
    MiniSMB *_connection;
    NSString *_smbPath;
    NSString *_localPath;
    CDUnknownBlockType _aProgressBlock;
    CDUnknownBlockType _aCompletionBlock;
}

@property(nonatomic) int jobId; // @synthesize jobId=_jobId;
@property(copy, nonatomic) CDUnknownBlockType aCompletionBlock; // @synthesize aCompletionBlock=_aCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType aProgressBlock; // @synthesize aProgressBlock=_aProgressBlock;
@property(retain, nonatomic) NSString *localPath; // @synthesize localPath=_localPath;
@property(retain, nonatomic) NSString *smbPath; // @synthesize smbPath=_smbPath;
@property(retain, nonatomic) MiniSMB *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancel;
- (void)main;
- (id)initWithConnection:(id)arg1;

@end

