//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDDictionaryBackedObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface GDSMBMetadata : GDDictionaryBackedObject
{
}

- (id)detailsInformation;
@property(readonly, nonatomic) NSDate *modifiedDate;
@property(readonly, copy, nonatomic) NSString *lastModifiedString;
@property(readonly, nonatomic) unsigned long long fileSize;
@property(readonly, nonatomic) _Bool isDirectory;
@property(readonly, copy, nonatomic) NSString *href;
- (id)initWithSMBItem:(id)arg1;

@end

