//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDHTTPClient.h"

@class GDSMBCredential, MiniSMB;

__attribute__((visibility("hidden")))
@interface GDSMBClient : GDHTTPClient
{
    MiniSMB *_client;
}

@property(retain, nonatomic) MiniSMB *client; // @synthesize client=_client;
- (void).cxx_destruct;
- (void)dealloc;
- (void)doNothing;
- (id)uploadFile:(id)arg1 mimeType:(id)arg2 toWebDAVPath:(id)arg3 progress:(CDUnknownBlockType)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (id)downloadFile:(id)arg1 intoPath:(id)arg2 progress:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)copyPath:(id)arg1 toPath:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)movePath:(id)arg1 toPath:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)setFilePermissionsForPath:(id)arg1 withPermissions:(unsigned long long)arg2 recursive:(_Bool)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)deletePath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)createPath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getMetadataForPath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getContentsOfDirectoryAtPath:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)validateSMBServerWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)initWithClientManager:(id)arg1 credential:(id)arg2 baseURL:(id)arg3;

// Remaining properties
@property(retain) GDSMBCredential *credential; // @dynamic credential;

@end

