//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDDictionaryBackedObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface GDSugarSyncAccountInfo : GDDictionaryBackedObject
{
}

@property(readonly, copy, nonatomic) NSString *magicBriefcaseObjectID;
@property(readonly, copy, nonatomic) NSString *deletedItemsObjectID;
@property(readonly, copy, nonatomic) NSString *syncFoldersObjectID;
@property(readonly, copy, nonatomic) NSString *workspacesObjectID;
@property(readonly, copy, nonatomic) NSString *nickname;
@property(readonly, copy, nonatomic) NSString *username;

@end

