//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDHTTPClient.h"

@class GDSugarSyncAPIToken, GDSugarSyncAccountInfo, GDSugarSyncCredential, ISO8601DateFormatter, NSDictionary;

__attribute__((visibility("hidden")))
@interface GDSugarSyncClient : GDHTTPClient
{
    ISO8601DateFormatter *_dateFormatter;
    GDSugarSyncAccountInfo *_cachedAccountInfo;
    NSDictionary *_fixedMetadataByObjectID;
}

@property(readonly, nonatomic) NSDictionary *fixedMetadataByObjectID; // @synthesize fixedMetadataByObjectID=_fixedMetadataByObjectID;
@property(readonly, nonatomic) GDSugarSyncAccountInfo *cachedAccountInfo; // @synthesize cachedAccountInfo=_cachedAccountInfo;
@property(readonly, nonatomic) ISO8601DateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (void).cxx_destruct;
- (id)metadataArrayFromXMLNode:(id)arg1;
- (id)objectFromXMLNode:(id)arg1;
- (id)contentStringForElementWithName:(id)arg1 inXMLElement:(id)arg2;
- (void)deleteChildOfXMLElement:(id)arg1 withName:(id)arg2;
- (_Bool)setString:(id)arg1 asContentForElementWithName:(id)arg2 inXMLElement:(id)arg3;
- (id)rootMetadata;
- (id)syncFoldersMetadata;
- (id)workspacesMetadata;
- (id)uploadFile:(id)arg1 toFileID:(id)arg2 parentVersionID:(id)arg3 uploadState:(id)arg4 uploadStateHandler:(CDUnknownBlockType)arg5 progress:(CDUnknownBlockType)arg6 success:(CDUnknownBlockType)arg7 failure:(CDUnknownBlockType)arg8;
- (void)createFileWithName:(id)arg1 mimeType:(id)arg2 inCollectionID:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)createDirectoryWithName:(id)arg1 inDirectory:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)downloadFileID:(id)arg1 intoPath:(id)arg2 fileVersionID:(id)arg3 progress:(CDUnknownBlockType)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)copyFileID:(id)arg1 toFolderID:(id)arg2 name:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)trashObjectID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)deleteSharedLinkForObjectID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)createSharedLinkForObjectID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getSharedLinkForObjectID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)moveObjectID:(id)arg1 toFolderID:(id)arg2 name:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)createFileVersionForFileID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getVersionHistoryForObjectID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getSyncFoldersWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)getWorkspacesWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)contentsOfToplevelCollection:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getContentsOfCollectionID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getContentsOfMetadataArrayID:(id)arg1 offset:(long long)arg2 resultsArray:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getContentsOfMetadataArrayID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getMetadataForObjectID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getCachedAccountInfoWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)getAccountInfoWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)getAccessTokenWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)getRefreshTokenWithUsername:(id)arg1 password:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)xmlDataByFillingXMLTemplateName:(id)arg1 substitutionVariables:(id)arg2;
- (_Bool)isAuthenticationFailureError:(id)arg1;
- (_Bool)authorizeRequest:(id)arg1;
- (void)enqueueSugarSyncRequestOperationWithMethod:(id)arg1 path:(id)arg2 urlParameters:(id)arg3 xmlTemplateName:(id)arg4 substitutionVariables:(id)arg5 requiresAccessToken:(_Bool)arg6 success:(CDUnknownBlockType)arg7 failure:(CDUnknownBlockType)arg8;
- (void)enqueueSugarSyncRequestOperationWithMethod:(id)arg1 path:(id)arg2 urlParameters:(id)arg3 xmlTemplateName:(id)arg4 substitutionVariables:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (id)initWithClientManager:(id)arg1 credential:(id)arg2 baseURL:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) GDSugarSyncAPIToken *apiToken; // @dynamic apiToken;
@property(retain) GDSugarSyncCredential *credential; // @dynamic credential;

@end

