//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSDictionary, NSString, NSURL;

@protocol GDURLMetadataProperties <NSObject>
@property(readonly, nonatomic) _Bool isSymbolicLink;
@property(readonly, nonatomic) NSURL *parentUrl;
@property(readonly, nonatomic) NSDictionary *rawData;
@property(readonly, nonatomic) NSDate *modifiedDate;
@property(readonly, nonatomic, getter=isReadOnly) _Bool readOnly;
@property(readonly, copy, nonatomic) NSString *filename;
@property(readonly, copy, nonatomic) NSString *fileVersionIdentifier;
@property(readonly, nonatomic) long long fileSize;
@property(readonly, nonatomic, getter=isDirectory) _Bool directory;
- (NSArray *)detailsInformation;
- (_Bool)isValid;
@end

