//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDURLMetadata.h"

@class GDWebDAVMetadata, NSDate, NSDictionary, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface GDWebDAVURLMetadata : NSObject <GDURLMetadata>
{
    GDWebDAVMetadata *_metadata;
}

@property(readonly, nonatomic) GDWebDAVMetadata *metadata; // @synthesize metadata=_metadata;
- (void).cxx_destruct;
- (_Bool)isValid;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSDate *modifiedDate;
@property(readonly, copy, nonatomic) NSString *webDAVPath;
@property(readonly, copy, nonatomic) NSString *filename;
@property(readonly, copy, nonatomic) NSString *fileVersionIdentifier;
@property(readonly, nonatomic) long long fileSize;
@property(readonly, nonatomic, getter=isReadOnly) _Bool readOnly;
@property(readonly, nonatomic, getter=isDirectory) _Bool directory;
@property(readonly, nonatomic) NSDictionary *rawData;
- (id)cacheableMetadata;
- (id)jsonDictionary;
@property(readonly, nonatomic) _Bool isSymbolicLink;
- (id)detailsInformation;
- (id)initWithWebDAVMetadata:(id)arg1;
- (id)initWithMetadataDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSURL *parentUrl; // @dynamic parentUrl;
@property(readonly) Class superclass;

@end

