//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDClientCredential.h"

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface GDWebDAVCredential : GDClientCredential
{
    NSString *_password;
    NSURL *_serverURL;
}

@property(readonly, nonatomic) NSURL *serverURL; // @synthesize serverURL=_serverURL;
@property(readonly, copy, nonatomic) NSString *password; // @synthesize password=_password;
- (void).cxx_destruct;
- (_Bool)isValid;
@property(readonly, copy, nonatomic) NSString *username;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)alias;
- (id)initWithUsername:(id)arg1 password:(id)arg2 serverURL:(id)arg3;
- (id)initWithUserID:(id)arg1 apiToken:(id)arg2;

@end

