//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIAlertViewDelegate.h"
#import "UIWebViewDelegate.h"

@class GDWebLoginController, NSString, NSURLRequest, UIAlertView, UIWebView;

__attribute__((visibility("hidden")))
@interface GDWebLoginViewController : UIViewController <UIWebViewDelegate, UIAlertViewDelegate>
{
    _Bool _haveStartedLoading;
    _Bool _hasLoaded;
    NSURLRequest *_urlRequest;
    GDWebLoginController *_loginController;
    UIWebView *_webView;
    UIAlertView *_alertView;
}

@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
@property(nonatomic) _Bool hasLoaded; // @synthesize hasLoaded=_hasLoaded;
@property(nonatomic) _Bool haveStartedLoading; // @synthesize haveStartedLoading=_haveStartedLoading;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak GDWebLoginController *loginController; // @synthesize loginController=_loginController;
@property(retain, nonatomic) NSURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
- (void).cxx_destruct;
- (void)stopLoading;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)beginLoading;
- (void)loadURLRequest:(id)arg1;
- (void)loadURL:(id)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithWebLoginController:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

