//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class FXLabel, NSString, TagColorBackgroundView, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface GridViewRowCell : UICollectionViewCell
{
    _Bool _customHighlighted;
    _Bool _editing;
    _Bool _isForiPad;
    _Bool _waitForThumnail;
    _Bool _isLink;
    UIImageView *_iconImageView;
    UIImageView *_mask;
    FXLabel *_nameLabel;
    UILabel *_detailLabel;
    UIButton *_checkBoxSelection;
    long long _tagColorValue;
    NSString *_cellUUID;
    UIButton *_accessoryView;
    TagColorBackgroundView *_tagBackground;
}

@property(retain, nonatomic) TagColorBackgroundView *tagBackground; // @synthesize tagBackground=_tagBackground;
@property(nonatomic) _Bool isLink; // @synthesize isLink=_isLink;
@property(retain, nonatomic) UIButton *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(retain, nonatomic) NSString *cellUUID; // @synthesize cellUUID=_cellUUID;
@property(nonatomic) _Bool waitForThumnail; // @synthesize waitForThumnail=_waitForThumnail;
@property(nonatomic) _Bool isForiPad; // @synthesize isForiPad=_isForiPad;
@property(nonatomic) _Bool editing; // @synthesize editing=_editing;
@property(nonatomic) long long tagColorValue; // @synthesize tagColorValue=_tagColorValue;
@property(retain, nonatomic) UIButton *checkBoxSelection; // @synthesize checkBoxSelection=_checkBoxSelection;
@property(readonly, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(readonly, nonatomic) FXLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *mask; // @synthesize mask=_mask;
@property(readonly, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)setIsDirectory:(_Bool)arg1;
- (void)setCustomHighlighted:(_Bool)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1;
- (void)initCheckbox:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

