//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface HexEditorLayout : UICollectionViewLayout
{
    _Bool _vShouldAlignCenter;
    _Bool _vShowHeader;
    int _vColumnsGroupCount;
    int _vLinesGroupCount;
    int _numberOfColumns;
    int _numberOfLines;
    int _columnsGroupCount;
    int _linesGroupCount;
    NSArray *_vSectionItemWidths;
    double _vLineHeight;
    double _vSectionSpace;
    double _vItemSpace;
    double _vLineHeaderSpace;
    double _vLineHeaderSize;
    double _vContentWidth;
    id <HexEditorLayoutDataSource> _dataSource;
    NSArray *_sectionItemWidths;
    double _lineHeight;
    double _sectionSpace;
    double _itemSpace;
    double _lineHeaderSpace;
    double _lineHeaderSize;
    double _contentWidth;
    struct CGSize _contentSize;
    struct UIEdgeInsets _vInsets;
    struct UIEdgeInsets _insets;
}

@property(nonatomic) double contentWidth; // @synthesize contentWidth=_contentWidth;
@property(nonatomic) int linesGroupCount; // @synthesize linesGroupCount=_linesGroupCount;
@property(nonatomic) int columnsGroupCount; // @synthesize columnsGroupCount=_columnsGroupCount;
@property(nonatomic) double lineHeaderSize; // @synthesize lineHeaderSize=_lineHeaderSize;
@property(nonatomic) double lineHeaderSpace; // @synthesize lineHeaderSpace=_lineHeaderSpace;
@property(nonatomic) double itemSpace; // @synthesize itemSpace=_itemSpace;
@property(nonatomic) double sectionSpace; // @synthesize sectionSpace=_sectionSpace;
@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
@property(nonatomic) double lineHeight; // @synthesize lineHeight=_lineHeight;
@property(retain, nonatomic) NSArray *sectionItemWidths; // @synthesize sectionItemWidths=_sectionItemWidths;
@property(nonatomic) struct CGSize contentSize; // @synthesize contentSize=_contentSize;
@property(nonatomic) int numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property(nonatomic) int numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) __weak id <HexEditorLayoutDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) double vContentWidth; // @synthesize vContentWidth=_vContentWidth;
@property(nonatomic) _Bool vShowHeader; // @synthesize vShowHeader=_vShowHeader;
@property(nonatomic) _Bool vShouldAlignCenter; // @synthesize vShouldAlignCenter=_vShouldAlignCenter;
@property(nonatomic) int vLinesGroupCount; // @synthesize vLinesGroupCount=_vLinesGroupCount;
@property(nonatomic) int vColumnsGroupCount; // @synthesize vColumnsGroupCount=_vColumnsGroupCount;
@property(nonatomic) double vLineHeaderSize; // @synthesize vLineHeaderSize=_vLineHeaderSize;
@property(nonatomic) double vLineHeaderSpace; // @synthesize vLineHeaderSpace=_vLineHeaderSpace;
@property(nonatomic) double vItemSpace; // @synthesize vItemSpace=_vItemSpace;
@property(nonatomic) double vSectionSpace; // @synthesize vSectionSpace=_vSectionSpace;
@property(nonatomic) struct UIEdgeInsets vInsets; // @synthesize vInsets=_vInsets;
@property(nonatomic) double vLineHeight; // @synthesize vLineHeight=_vLineHeight;
@property(retain, nonatomic) NSArray *vSectionItemWidths; // @synthesize vSectionItemWidths=_vSectionItemWidths;
- (void).cxx_destruct;
- (long long)numberOfItemLines;
- (long long)numberOfItemColumns;
- (void)invalidateLayout;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (struct CGRect)frameForIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;
- (void)_initialize;
- (void)relayout;
- (struct CGSize)collectionViewContentSize;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

