//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSStream, NSString;

__attribute__((visibility("hidden")))
@interface ID3Tag : NSObject
{
    NSString *title_;
    NSString *album_;
    NSString *artist_;
    NSNumber *trackNumber_;
    NSNumber *totalTracks_;
    NSString *genre_;
    NSString *year_;
    NSNumber *approxDuration_;
    NSString *composer_;
    NSString *tempo_;
    NSString *keySignature_;
    NSString *timeSignature_;
    NSString *lyricist_;
    NSString *recordedDate_;
    NSString *comments_;
    NSString *copyright_;
    NSString *sourceEncoder_;
    NSString *encodingApplication_;
    NSString *bitRate_;
    NSStream *sourceBitRate_;
    NSString *channelLayout_;
    NSString *isrc_;
    NSString *subtitle_;
    NSString *_title;
    NSString *_album;
    NSString *_artist;
    NSNumber *_trackNumber;
    NSNumber *_totalTracks;
    NSString *_genre;
    NSString *_year;
    NSNumber *_approxDuration;
    NSString *_composer;
    NSString *_tempo;
    NSString *_keySignature;
    NSString *_timeSignature;
    NSString *_lyricist;
    NSString *_recordedDate;
    NSString *_comments;
    NSString *_copyright;
    NSString *_sourceEncoder;
    NSString *_encodingApplication;
    NSString *_bitRate;
    NSStream *_sourceBitRate;
    NSString *_channelLayout;
    NSString *_isrc;
    NSString *_subtitle;
}

@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) NSString *isrc; // @synthesize isrc=_isrc;
@property(retain, nonatomic) NSString *channelLayout; // @synthesize channelLayout=_channelLayout;
@property(retain, nonatomic) NSStream *sourceBitRate; // @synthesize sourceBitRate=_sourceBitRate;
@property(retain, nonatomic) NSString *bitRate; // @synthesize bitRate=_bitRate;
@property(retain, nonatomic) NSString *encodingApplication; // @synthesize encodingApplication=_encodingApplication;
@property(retain, nonatomic) NSString *sourceEncoder; // @synthesize sourceEncoder=_sourceEncoder;
@property(retain, nonatomic) NSString *copyright; // @synthesize copyright=_copyright;
@property(retain, nonatomic) NSString *comments; // @synthesize comments=_comments;
@property(retain, nonatomic) NSString *recordedDate; // @synthesize recordedDate=_recordedDate;
@property(retain, nonatomic) NSString *lyricist; // @synthesize lyricist=_lyricist;
@property(retain, nonatomic) NSString *timeSignature; // @synthesize timeSignature=_timeSignature;
@property(retain, nonatomic) NSString *keySignature; // @synthesize keySignature=_keySignature;
@property(retain, nonatomic) NSString *tempo; // @synthesize tempo=_tempo;
@property(retain, nonatomic) NSString *composer; // @synthesize composer=_composer;
@property(retain, nonatomic) NSNumber *approxDuration; // @synthesize approxDuration=_approxDuration;
@property(retain, nonatomic) NSString *year; // @synthesize year=_year;
@property(retain, nonatomic) NSString *genre; // @synthesize genre=_genre;
@property(retain, nonatomic) NSNumber *totalTracks; // @synthesize totalTracks=_totalTracks;
@property(retain, nonatomic) NSNumber *trackNumber; // @synthesize trackNumber=_trackNumber;
@property(retain, nonatomic) NSString *artist; // @synthesize artist=_artist;
@property(retain, nonatomic) NSString *album; // @synthesize album=_album;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

