//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "TextVIewTableViewCell.h"
#import "UITextViewDelegate.h"

@class NSMutableString, NSString, NSThread, UITextView;

__attribute__((visibility("hidden")))
@interface InstallerViewController : UITableViewController <TextVIewTableViewCell, UITextViewDelegate>
{
    _Bool run;
    _Bool ready;
    int master;
    struct termios oldt;
    int pid;
    int isStop;
    NSString *_information;
    NSMutableString *_history;
    NSThread *_thread;
    NSMutableString *_command;
    UITextView *_textView;
}

@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSMutableString *command; // @synthesize command=_command;
@property(retain, nonatomic) NSThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) NSMutableString *history; // @synthesize history=_history;
@property(retain, nonatomic) NSString *information; // @synthesize information=_information;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)done:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)addString:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)forkACommand;
- (void)_showError;
- (void)respring;
- (void)dealloc;
- (void)resizeTextViewToAccommodateKeyboardFrame:(struct CGRect)arg1 withAnimationDuration:(double)arg2 animationCurve:(long long)arg3;
- (void)resizeTextViewWithKeyboardNotification:(id)arg1;
- (void)install:(id)arg1;
- (void)resignIfNeeds:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)textViewTableViewCellDidBeginEditing:(id)arg1;
- (_Bool)textViewTableViewCell:(id)arg1 textDidChange:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

