//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "ItemEditTableViewControllerDelegate.h"
#import "TextVIewTableViewCell.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"

@class NSIndexPath, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface ItemEditTableViewController : UITableViewController <UITableViewDataSource, UITableViewDelegate, TextVIewTableViewCell, UIActionSheetDelegate, ItemEditTableViewControllerDelegate, UITextViewDelegate>
{
    _Bool _allowChangeTitle;
    _Bool _isRoot;
    _Bool _edited;
    _Bool _deleted;
    NSMutableDictionary *_item;
    NSIndexPath *_indexPath;
    id <ItemEditTableViewControllerDelegate> _delegate;
}

@property(nonatomic) _Bool deleted; // @synthesize deleted=_deleted;
@property(nonatomic) __weak id <ItemEditTableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool edited; // @synthesize edited=_edited;
@property(nonatomic) _Bool isRoot; // @synthesize isRoot=_isRoot;
@property(nonatomic) _Bool allowChangeTitle; // @synthesize allowChangeTitle=_allowChangeTitle;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) NSMutableDictionary *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)addObject:(id)arg1 withKey:(id)arg2;
- (void)deleteObjectAtIndex:(long long)arg1;
- (id)objectAtIndex:(long long)arg1;
- (id)titleAtIndex:(long long)arg1;
- (void)itemEditTableViewController:(id)arg1 doDeleteObject:(id)arg2 andKey:(id)arg3 atIndexPath:(id)arg4;
- (void)itemEditTableViewController:(id)arg1 didReplaceWithObject:(id)arg2 andKey:(id)arg3 atIndexPath:(id)arg4;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)timeWasSelected:(id)arg1;
- (void)dateWasSelected:(id)arg1;
- (void)changeTime:(id)arg1;
- (void)changeDate:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)switched:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)textViewTableViewCellDidBeginEditing:(id)arg1;
- (_Bool)textViewTableViewCell:(id)arg1 textDidChange:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (void)updateTitle;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

