//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ItemEditTableViewController, NSIndexPath, NSString;

@protocol ItemEditTableViewControllerDelegate <NSObject>
- (void)itemEditTableViewController:(ItemEditTableViewController *)arg1 doDeleteObject:(id)arg2 andKey:(NSString *)arg3 atIndexPath:(NSIndexPath *)arg4;
- (void)itemEditTableViewController:(ItemEditTableViewController *)arg1 didReplaceWithObject:(id)arg2 andKey:(NSString *)arg3 atIndexPath:(NSIndexPath *)arg4;
@end

