//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIProgressView.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface JEProgressView : UIProgressView
{
    UIImageView *_trackImageView;
    UIImageView *_progressImageView;
}

@property(nonatomic) __weak UIImageView *progressImageView; // @synthesize progressImageView=_progressImageView;
@property(nonatomic) __weak UIImageView *trackImageView; // @synthesize trackImageView=_trackImageView;
- (void).cxx_destruct;
- (long long)compareVersionString:(id)arg1 withVersionString:(id)arg2;
- (void)setupProgressView;
- (void)setTrackImage:(id)arg1;
- (void)setProgressImage:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

