//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface JobsManager : NSObject
{
    NSObject<OS_dispatch_queue> *dispatchQueue;
    NSMutableArray *_jobs;
    NSMutableDictionary *_block;
    NSLock *_locking;
}

+ (id)sharedInstance;
@property(retain) NSLock *locking; // @synthesize locking=_locking;
@property(retain) NSMutableDictionary *block; // @synthesize block=_block;
@property(retain) NSMutableArray *jobs; // @synthesize jobs=_jobs;
- (void).cxx_destruct;
- (void)dealloc;
- (void)abortJobWIthJobId:(int)arg1;
- (int)count;
- (void)unlock;
- (void)lock;
- (int)addJobWithType:(int)arg1 block:(CDUnknownBlockType)arg2;
- (_Bool)isJobCancelled:(int)arg1;
- (void)execJobs;
- (id)init;

@end

