//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

#import "ReorderTableViewDelegate.h"
#import "TGMenuManagerDelegate.h"
#import "UIPopoverControllerDelegate.h"

@class LeftEditingPanelViewController, NSArray, NSMutableArray, NSString, TGThemePopoverController;

__attribute__((visibility("hidden")))
@interface LeftPanelTableViewController : TGThemeTableViewController <ReorderTableViewDelegate, UIPopoverControllerDelegate, TGMenuManagerDelegate>
{
    _Bool _disabled;
    _Bool _hasSharedFolder;
    _Bool _addWindow;
    NSMutableArray *_windows;
    NSMutableArray *_links;
    TGThemePopoverController *_moreController;
    LeftEditingPanelViewController *_editingViewController;
    NSArray *_sections;
}

@property(retain, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) LeftEditingPanelViewController *editingViewController; // @synthesize editingViewController=_editingViewController;
@property(retain, nonatomic) TGThemePopoverController *moreController; // @synthesize moreController=_moreController;
@property(nonatomic) _Bool addWindow; // @synthesize addWindow=_addWindow;
@property(retain, nonatomic) NSMutableArray *links; // @synthesize links=_links;
@property(retain, nonatomic) NSMutableArray *windows; // @synthesize windows=_windows;
- (void).cxx_destruct;
- (void)menuManager:(id)arg1 hideAnimated:(_Bool)arg2;
- (void)menuManager:(id)arg1 showWithItems:(id)arg2 animated:(_Bool)arg3;
- (id)menuManager:(id)arg1 sourceViewForMenuItemWithIdentifier:(id)arg2;
- (struct CGRect)menuManager:(id)arg1 rectForMenuItemWithIdentifier:(id)arg2;
- (void)menuManager:(id)arg1 updateItemWithIdenfier:(id)arg2 isEnabled:(_Bool)arg3;
- (void)reloadCloud;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)disableAddingWindow:(_Bool)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)finishReorderingWithObject:(id)arg1 atIndexPath:(id)arg2;
- (void)moveRowAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (id)saveObjectAndInsertBlankRowAtIndexPath:(id)arg1;
- (_Bool)canMoveRowFromIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (_Bool)canMoveRowAtIndexPath:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)disableLeftPanel:(_Bool)arg1;
- (void)addLink;
- (void)updateEditingToolbarWithSelectedFilesCount:(int)arg1;
- (void)dealloc;
- (void)loadFavorites;
- (void)reloadFavorites;
- (void)reloadSections:(id)arg1;
- (void)viewDidLoad;
- (void)updateTitleForPage:(id)arg1;
- (void)highLightPage:(id)arg1;
- (void)removeWindow:(id)arg1;
- (void)addWindow:(id)arg1;
- (void)reloadSharedFolder;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

