//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, FileItem, NSDictionary, NSURL, UIImage;

__attribute__((visibility("hidden")))
@interface MDAudioFile : NSObject
{
    NSURL *filePath;
    NSDictionary *fileInfoDict;
    FileItem *_fileItemRef;
    UIImage *_artWork;
    AVAsset *_asset;
}

@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
@property(retain, nonatomic) UIImage *artWork; // @synthesize artWork=_artWork;
@property(retain, nonatomic) FileItem *fileItemRef; // @synthesize fileItemRef=_fileItemRef;
@property(retain, nonatomic) NSDictionary *fileInfoDict; // @synthesize fileInfoDict;
@property(retain, nonatomic) NSURL *filePath; // @synthesize filePath;
- (void).cxx_destruct;
- (void)artworkWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)coverImage;
- (id)durationInMinutes;
- (float)duration;
- (float)durationMiliseconds;
- (id)album;
- (id)artist;
- (int)realYear;
- (id)composerName;
- (id)genre;
- (long long)releaseYear;
- (id)getTitle;
- (double)bitrate;
- (long long)trackNumber;
- (id)lyrics;
- (id)title;
- (id)stringFromArray:(id)arg1;
- (void)fetchTagID3IfNeeds;
- (id)lyricsFromAllKeySpaces:(id)arg1;
- (id)trackNumberFromAllKeySpaces:(id)arg1;
- (id)albumYearFromAllKeySpaces:(id)arg1;
- (id)albumNamesFromAllKeySpaces:(id)arg1;
- (id)artistsFromAllKeySpaces:(id)arg1;
- (id)initWithPath:(id)arg1;

@end

