//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FileItem.h"

@class ML3Track, MPMediaItem, NSString;

__attribute__((visibility("hidden")))
@interface MediaFileItem : FileItem
{
    MPMediaItem *_item;
    ML3Track *_track;
    NSString *__fileName;
    long long _perID;
    NSString *_aFilePath;
}

+ (id)realPathOfMusicPath:(id)arg1;
@property(retain, nonatomic) NSString *aFilePath; // @synthesize aFilePath=_aFilePath;
@property(nonatomic) long long perID; // @synthesize perID=_perID;
@property(retain, nonatomic) NSString *_fileName; // @synthesize _fileName=__fileName;
@property(retain, nonatomic) ML3Track *track; // @synthesize track=_track;
@property(retain, nonatomic) MPMediaItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (id)icon;
- (id)typeString;
- (id)stringFromArray:(id)arg1;
- (id)album;
- (id)__dateString;
- (id)dateString;
- (int)fileType;
- (long long)accessoryType;
- (id)fileSizeString;
- (double)duration;
- (id)fileExtension;
- (id)fileName;
- (id)musicPath;
- (id)realPath;
- (void)reload;
- (id)filePath;
- (void)setFilePath:(id)arg1;
- (void)setPersistentID:(long long)arg1;
- (_Bool)isDownloaded;
- (id)permissionString;
- (unsigned long long)mediaType;
- (void)setMusicPath:(id)arg1;

@end

