//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface MiniSMBErrorMessage : NSObject
{
}

+ (id)errorWithSMB2:(struct smb2_context *)arg1 error:(int)arg2;
+ (id)errorWithSMB1:(struct smb_session *)arg1 error:(int)arg2;
+ (id)ErrorMessageSMB2:(struct smb2_context *)arg1 error:(int)arg2 code:(int *)arg3;
+ (id)ErrorMessageSMB1:(struct smb_session *)arg1 error:(int)arg2 code:(int *)arg3;

@end

