//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TIGIBrowserView.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface MountPointsBrowserView : TIGIBrowserView
{
    UIView *_footer;
}

@property(retain, nonatomic) UIView *footer; // @synthesize footer=_footer;
- (void).cxx_destruct;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;

@end

