//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FileItem.h"

__attribute__((visibility("hidden")))
@interface MountPointItem : FileItem
{
    struct statfs stat;
}

- (struct statfs *)statfs;
- (void)setFileSystemStat:(struct statfs *)arg1;

@end

