//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface MutLockArray : NSObject
{
    NSMutableArray *array;
    struct _opaque_pthread_rwlock_t {
        long long __sig;
        char __opaque[192];
    } arrayLock;
}

+ (id)arrayWithCapacity:(long long)arg1;
- (void)lockSortUsingDescriptors:(id)arg1;
- (void)sortUsingDescriptors:(id)arg1;
- (long long)lockCount;
- (long long)count;
- (id)reverseObjectEnumerator;
- (id)objectEnumerator;
- (void)lockSortUsingSelector:(SEL)arg1;
- (void)sortUsingSelector:(SEL)arg1;
- (void)lockMakeObjectsPerformSelector:(SEL)arg1 withObject:(id)arg2;
- (void)makeObjectsPerformSelector:(SEL)arg1 withObject:(id)arg2;
- (void)lockMakeObjectsPerformSelector:(SEL)arg1;
- (void)makeObjectsPerformSelector:(SEL)arg1;
- (id)lockFilteredArrayUsingPredicate:(id)arg1;
- (id)filteredArrayUsingPredicate:(id)arg1;
- (void)lockRemoveIdenticalPtr:(id)arg1;
- (void)removeIdenticalPtr:(id)arg1;
- (long long)lockIndexOfIdenticalPtr:(id)arg1;
- (long long)indexOfIdenticalPtr:(id)arg1;
- (_Bool)lockContainsIdenticalPtr:(id)arg1;
- (_Bool)containsIdenticalPtr:(id)arg1;
- (long long)lockIndexOfObject:(id)arg1;
- (long long)indexOfObject:(id)arg1;
- (id)lockObjectsAtIndexes:(id)arg1;
- (id)objectsAtIndexes:(id)arg1;
- (id)lockObjectAtIndex:(long long)arg1;
- (id)objectAtIndex:(long long)arg1;
- (_Bool)lockContainsObject:(id)arg1;
- (_Bool)containsObject:(id)arg1;
- (id)lockValueForKey:(id)arg1;
- (id)valueForKey:(id)arg1;
- (void)lockRemoveIdenticalPtrsInArray:(id)arg1;
- (void)removeIdenticalPtrsInArray:(id)arg1;
- (void)lockRemoveObjectsInArray:(id)arg1;
- (void)removeObjectsInArray:(id)arg1;
- (void)lockRemoveObjectsAtIndexes:(id)arg1;
- (void)removeObjectsAtIndexes:(id)arg1;
- (void)lockRemoveObjectAtIndex:(long long)arg1;
- (void)removeObjectAtIndex:(long long)arg1;
- (void)lockRemoveObject:(id)arg1;
- (void)removeObject:(id)arg1;
- (void)lockRemoveLastObject;
- (void)removeLastObject;
- (id)lockLastObject;
- (id)lastObject;
- (void)lockRemoveFirstObject;
- (void)removeFirstObject;
- (id)lockFirstObject;
- (id)firstObject;
- (void)lockRemoveAllObjects;
- (void)removeAllObjects;
- (_Bool)lockInsertObject:(id)arg1 atIndex:(long long)arg2;
- (_Bool)insertObject:(id)arg1 atIndex:(long long)arg2;
- (void)lockReplaceObjectsAtIndexes:(id)arg1 withObjects:(id)arg2;
- (void)replaceObjectsAtIndexes:(id)arg1 withObjects:(id)arg2;
- (void)lockReplaceWithObjectsFromArray:(id)arg1;
- (void)replaceWithObjectsFromArray:(id)arg1;
- (void)lockAddObjectsFromArray:(id)arg1;
- (void)addObjectsFromArray:(id)arg1;
- (void)lockAddObject:(id)arg1;
- (void)addObject:(id)arg1;
- (id)lockCreateArrayCopy;
- (id)createArrayCopy;
- (id)array;
- (void)unlock;
- (void)wrlock;
- (_Bool)tryRdLock;
- (void)rdlock;
- (void)dealloc;
- (id)init;
- (id)initWithCapacity:(long long)arg1;
- (id)description;

@end

