//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSURL, UIImage;

@protocol MWPhoto <NSObject>
@property(retain, nonatomic) NSDictionary *EXIFInfo;
@property(retain, nonatomic) NSURL *imageURL;
@property(retain, nonatomic) NSString *caption;
@property(readonly, nonatomic) UIImage *image;
@end

