//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIButton, UILabel, UITextField;

__attribute__((visibility("hidden")))
@interface NewActivationViewController : UIViewController
{
    UITextField *_serialNumberTextField;
    UIButton *_purchaseButton;
    UIButton *_activationButton;
    UILabel *_textLabel;
    UILabel *_snLabel;
}

@property(nonatomic) UILabel *snLabel; // @synthesize snLabel=_snLabel;
@property(nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) UIButton *activationButton; // @synthesize activationButton=_activationButton;
@property(nonatomic) UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(nonatomic) UITextField *serialNumberTextField; // @synthesize serialNumberTextField=_serialNumberTextField;
- (void)didReceiveMemoryWarning;
- (void)done:(id)arg1;
- (void)activateFromURL:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)purchase:(id)arg1;
- (void)activate:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

