//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NewEmptyFile;

@protocol NewEmptyFileDelegate <NSObject>
- (void)NewEmptyFile:(NewEmptyFile *)arg1 completeWithName:(NSString *)arg2;
- (_Bool)NewEmptyFile:(NewEmptyFile *)arg1 checkIfNameExisted:(NSString *)arg2;
@end

