//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TGPreferencesTableViewController;

__attribute__((visibility("hidden")))
@interface NewLicenseManager : NSObject
{
    TGPreferencesTableViewController *_preferencesTbv;
}

+ (id)sharedInstance;
@property(nonatomic) __weak TGPreferencesTableViewController *preferencesTbv; // @synthesize preferencesTbv=_preferencesTbv;
- (void).cxx_destruct;
- (void)loadSignature;

@end

