//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (TGRootFileManager)
+ (id)dataWithContentsOfFilePrivileged:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
+ (id)dataWithContentsOfFilePrivileged:(id)arg1;
- (_Bool)writeToFilePrivileged:(id)arg1 atomically:(_Bool)arg2;
@end

