//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (Sorting)
- (long long)insertObject:(id)arg1 atSortMode:(int)arg2 preferredIndex:(long long)arg3;
- (void)sortWithMode:(int)arg1;
@end

