//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISlider.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface OBSlider : UISlider
{
    float _scrubbingSpeed;
    float _realPositionValue;
    NSArray *_scrubbingSpeeds;
    NSArray *_scrubbingSpeedChangePositions;
    struct CGPoint _beganTrackkingLocation;
}

@property(nonatomic) float realPositionValue; // @synthesize realPositionValue=_realPositionValue;
@property(nonatomic) struct CGPoint beganTrackingLocation; // @synthesize beganTrackingLocation=_beganTrackkingLocation;
@property(retain, nonatomic) NSArray *scrubbingSpeedChangePositions; // @synthesize scrubbingSpeedChangePositions=_scrubbingSpeedChangePositions;
@property(retain, nonatomic) NSArray *scrubbingSpeeds; // @synthesize scrubbingSpeeds=_scrubbingSpeeds;
@property(nonatomic) float scrubbingSpeed; // @synthesize scrubbingSpeed=_scrubbingSpeed;
- (void).cxx_destruct;
- (id)defaultScrubbingSpeedChangePositions;
- (id)defaultScrubbingSpeeds;
- (unsigned long long)indexOfLowerScrubbingSpeed:(id)arg1 forOffset:(double)arg2;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

