//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchBar.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface OOSearchBar : UISearchBar
{
    UIView *_prev;
}

@property(retain, nonatomic) UIView *prev; // @synthesize prev=_prev;
- (void).cxx_destruct;
- (void)stopSpinnerAnimating:(id)arg1;
- (void)startSpinnerAnimating:(id)arg1;

@end

