//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

@class FileItem, NSMutableArray;

__attribute__((visibility("hidden")))
@interface OwnerShip : BaseTableViewController
{
    _Bool _applyRescursively;
    _Bool _changed;
    int _type;
    int _ownerUserId;
    int _ownerGroupId;
    FileItem *_file;
    NSMutableArray *_user;
    NSMutableArray *_group;
}

@property(nonatomic) _Bool changed; // @synthesize changed=_changed;
@property(retain, nonatomic) NSMutableArray *group; // @synthesize group=_group;
@property(retain, nonatomic) NSMutableArray *user; // @synthesize user=_user;
@property(nonatomic) _Bool applyRescursively; // @synthesize applyRescursively=_applyRescursively;
@property(nonatomic) int ownerGroupId; // @synthesize ownerGroupId=_ownerGroupId;
@property(nonatomic) int ownerUserId; // @synthesize ownerUserId=_ownerUserId;
@property(nonatomic) __weak FileItem *file; // @synthesize file=_file;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)setRecurve:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setFile:(id)arg1 withType:(int)arg2;
- (void)didReceiveMemoryWarning;
- (void)apply;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

