//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "UITextFieldDelegate.h"

@class FileItem, NSString;

__attribute__((visibility("hidden")))
@interface PermissionSetting : BaseTableViewController <UITextFieldDelegate>
{
    _Bool _applyRescursively;
    FileItem *_file;
    unsigned long long _pem;
}

@property(nonatomic) unsigned long long pem; // @synthesize pem=_pem;
@property(nonatomic) _Bool applyRescursively; // @synthesize applyRescursively=_applyRescursively;
@property(nonatomic) __weak FileItem *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)setRecurve:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)apply;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

