//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSNumber, UIColor, UIFont, UIView;

@interface QAppearance : NSObject <NSCopying>
{
    _Bool _toolbarTranslucent;
    UIFont *_sectionTitleFont;
    UIColor *_sectionTitleColor;
    UIFont *_sectionFooterFont;
    UIColor *_sectionFooterColor;
    long long _entryAlignment;
    long long _buttonAlignment;
    UIView *_selectedBackgroundView;
    UIColor *_sectionTitleShadowColor;
    UIColor *_labelColorDisabled;
    UIColor *_labelColorEnabled;
    UIFont *_labelFont;
    UIColor *_backgroundColorEnabled;
    UIColor *_backgroundColorDisabled;
    long long _labelAlignment;
    UIColor *_tableGroupedBackgroundColor;
    UIColor *_tableBackgroundColor;
    UIView *_tableBackgroundView;
    UIColor *_tableSeparatorColor;
    UIFont *_entryFont;
    UIColor *_entryTextColorEnabled;
    UIColor *_entryTextColorDisabled;
    UIColor *_valueColorEnabled;
    UIColor *_valueColorDisabled;
    UIFont *_valueFont;
    long long _valueAlignment;
    UIColor *_actionColorEnabled;
    UIColor *_actionColorDisabled;
    double _cellBorderWidth;
    NSNumber *_defaultHeightForHeader;
    NSNumber *_defaultHeightForFooter;
    long long _toolbarStyle;
    UIView *_tableGroupedBackgroundView;
}

@property(retain, nonatomic) UIView *tableGroupedBackgroundView; // @synthesize tableGroupedBackgroundView=_tableGroupedBackgroundView;
@property(nonatomic) long long toolbarStyle; // @synthesize toolbarStyle=_toolbarStyle;
@property(retain, nonatomic) NSNumber *defaultHeightForFooter; // @synthesize defaultHeightForFooter=_defaultHeightForFooter;
@property(retain, nonatomic) NSNumber *defaultHeightForHeader; // @synthesize defaultHeightForHeader=_defaultHeightForHeader;
@property(nonatomic) double cellBorderWidth; // @synthesize cellBorderWidth=_cellBorderWidth;
@property(nonatomic) _Bool toolbarTranslucent; // @synthesize toolbarTranslucent=_toolbarTranslucent;
@property(retain, nonatomic) UIColor *actionColorDisabled; // @synthesize actionColorDisabled=_actionColorDisabled;
@property(retain, nonatomic) UIColor *actionColorEnabled; // @synthesize actionColorEnabled=_actionColorEnabled;
@property(nonatomic) long long valueAlignment; // @synthesize valueAlignment=_valueAlignment;
@property(retain, nonatomic) UIFont *valueFont; // @synthesize valueFont=_valueFont;
@property(retain, nonatomic) UIColor *valueColorDisabled; // @synthesize valueColorDisabled=_valueColorDisabled;
@property(retain, nonatomic) UIColor *valueColorEnabled; // @synthesize valueColorEnabled=_valueColorEnabled;
@property(retain, nonatomic) UIColor *entryTextColorDisabled; // @synthesize entryTextColorDisabled=_entryTextColorDisabled;
@property(retain, nonatomic) UIColor *entryTextColorEnabled; // @synthesize entryTextColorEnabled=_entryTextColorEnabled;
@property(retain, nonatomic) UIFont *entryFont; // @synthesize entryFont=_entryFont;
@property(retain, nonatomic) UIColor *tableSeparatorColor; // @synthesize tableSeparatorColor=_tableSeparatorColor;
@property(retain, nonatomic) UIView *tableBackgroundView; // @synthesize tableBackgroundView=_tableBackgroundView;
@property(retain, nonatomic) UIColor *tableBackgroundColor; // @synthesize tableBackgroundColor=_tableBackgroundColor;
@property(retain, nonatomic) UIColor *tableGroupedBackgroundColor; // @synthesize tableGroupedBackgroundColor=_tableGroupedBackgroundColor;
@property(nonatomic) long long labelAlignment; // @synthesize labelAlignment=_labelAlignment;
@property(retain, nonatomic) UIColor *backgroundColorDisabled; // @synthesize backgroundColorDisabled=_backgroundColorDisabled;
@property(retain, nonatomic) UIColor *backgroundColorEnabled; // @synthesize backgroundColorEnabled=_backgroundColorEnabled;
@property(retain, nonatomic) UIFont *labelFont; // @synthesize labelFont=_labelFont;
@property(retain, nonatomic) UIColor *labelColorEnabled; // @synthesize labelColorEnabled=_labelColorEnabled;
@property(retain, nonatomic) UIColor *labelColorDisabled; // @synthesize labelColorDisabled=_labelColorDisabled;
@property(retain, nonatomic) UIColor *sectionTitleShadowColor; // @synthesize sectionTitleShadowColor=_sectionTitleShadowColor;
@property(retain, nonatomic) UIView *selectedBackgroundView; // @synthesize selectedBackgroundView=_selectedBackgroundView;
@property(nonatomic) long long buttonAlignment; // @synthesize buttonAlignment=_buttonAlignment;
@property(nonatomic) long long entryAlignment; // @synthesize entryAlignment=_entryAlignment;
@property(retain, nonatomic) UIColor *sectionFooterColor; // @synthesize sectionFooterColor=_sectionFooterColor;
@property(retain, nonatomic) UIFont *sectionFooterFont; // @synthesize sectionFooterFont=_sectionFooterFont;
@property(retain, nonatomic) UIColor *sectionTitleColor; // @synthesize sectionTitleColor=_sectionTitleColor;
@property(retain, nonatomic) UIFont *sectionTitleFont; // @synthesize sectionTitleFont=_sectionTitleFont;
- (void).cxx_destruct;
- (void)cell:(id)arg1 willAppearForElement:(id)arg2 atIndexPath:(id)arg3;
- (double)heightForFooterInSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (double)heightForHeaderInSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (id)buildFooterForSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (id)buildHeaderForSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setDefaults;
- (id)init;

@end

