//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QEntryTableViewCell.h"

#import "DOAutocompleteTextFieldDelegate.h"
#import "UITextFieldDelegate.h"

@class DOAutocompleteTextField, NSArray, NSString, QAutoEntryElement, UIColor;

@interface QAutoEntryTableViewCell : QEntryTableViewCell <UITextFieldDelegate, DOAutocompleteTextFieldDelegate>
{
    DOAutocompleteTextField *txtField;
    NSArray *autoCompleteValues;
    UIColor *autoColor;
    NSString *_lastFullStringWithAutocompletion;
    QAutoEntryElement *_autoEntryElement;
    _Bool _autoCompleteEnabled;
    DOAutocompleteTextField *_autoCompleteField;
}

@property(retain, nonatomic) NSString *lastFullStringWithAutocompletion; // @synthesize lastFullStringWithAutocompletion=_lastFullStringWithAutocompletion;
@property(retain, nonatomic) NSArray *autoCompleteValues; // @synthesize autoCompleteValues;
@property(retain, nonatomic) DOAutocompleteTextField *autoCompleteField; // @synthesize autoCompleteField=_autoCompleteField;
- (void).cxx_destruct;
- (id)textField:(id)arg1 completionForPrefix:(id)arg2;
- (_Bool)becomeFirstResponder;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldEditingChanged:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)recalculateEntryFieldPosition;
- (_Bool)handleActionBarDone:(id)arg1;
- (void)prepareForElement:(id)arg1 inTableView:(id)arg2;
- (id)init;
- (void)createSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

