//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLabelElement.h"

@class NSString, UIColor;

@interface QBadgeElement : QLabelElement
{
    UIColor *_badgeColor;
    UIColor *_badgeTextColor;
    NSString *_badge;
}

@property(retain, nonatomic) NSString *badge; // @synthesize badge=_badge;
@property(retain, nonatomic) UIColor *badgeColor; // @synthesize badgeColor=_badgeColor;
@property(retain, nonatomic) UIColor *badgeTextColor; // @synthesize badgeTextColor=_badgeTextColor;
- (void).cxx_destruct;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)initWithTitle:(id)arg1 Value:(id)arg2;
- (id)init;

@end

