//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class UIColor;

@interface QBadgeLabel : UILabel
{
    UIColor *_badgeColor;
}

@property(retain, nonatomic) UIColor *badgeColor; // @synthesize badgeColor=_badgeColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)init;

@end

