//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QTableViewCell.h"

@class QBadgeLabel;

@interface QBadgeTableCell : QTableViewCell
{
    QBadgeLabel *_badgeLabel;
}

@property(readonly, nonatomic) QBadgeLabel *badgeLabel; // @synthesize badgeLabel=_badgeLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)init;

@end

