//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLabelElement.h"

@class NSNumber, UIImage;

@interface QBooleanElement : QLabelElement
{
    _Bool _boolValue;
    _Bool _enabled;
    UIImage *_onImage;
    UIImage *_offImage;
}

@property(nonatomic) _Bool boolValue; // @synthesize boolValue=_boolValue;
@property(retain, nonatomic) UIImage *offImage; // @synthesize offImage=_offImage;
@property(retain, nonatomic) UIImage *onImage; // @synthesize onImage=_onImage;
- (void).cxx_destruct;
- (void)setNilValueForKey:(id)arg1;
- (void)fetchValueIntoObject:(id)arg1;
- (void)switched:(id)arg1;
- (void)buttonPressed:(id)arg1;
- (void)selected:(id)arg1 controller:(id)arg2 indexPath:(id)arg3;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (void)setOffImageName:(id)arg1;
- (void)setOnImageName:(id)arg1;
@property(nonatomic) NSNumber *numberValue;
- (id)initWithTitle:(id)arg1 BoolValue:(_Bool)arg2;
- (id)init;

@end

