//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QAppearance.h"

@interface QClassicAppearance : QAppearance
{
}

- (float)currentGroupedTableViewMarginForTableView:(id)arg1;
- (void)cell:(id)arg1 willAppearForElement:(id)arg2 atIndexPath:(id)arg3;
- (double)heightForFooterInSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (double)heightForHeaderInSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (id)buildFooterForSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (id)buildHeaderForSection:(id)arg1 andTableView:(id)arg2 andIndex:(long long)arg3;
- (void)setDefaults;

@end

