//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QDateTimeInlineElement.h"

@class NSNumber;

@interface QCountdownElement : QDateTimeInlineElement
{
    NSNumber *_ticks;
}

- (void).cxx_destruct;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (void)setDateValue:(id)arg1;
- (id)dateValue;
- (id)ticksValue;
- (void)setTicksValue:(id)arg1;
- (id)init;

@end

