//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QTableViewCell.h"

@class QDateTimeInlineElement, UIDatePicker;

@interface QDateInlineTableViewCell : QTableViewCell
{
    _Bool _presentingPicker;
    UIDatePicker *_pickerView;
    QDateTimeInlineElement *_element;
}

@property(nonatomic) _Bool presentingPicker; // @synthesize presentingPicker=_presentingPicker;
@property(nonatomic) __weak QDateTimeInlineElement *element; // @synthesize element=_element;
@property(retain, nonatomic) UIDatePicker *pickerView; // @synthesize pickerView=_pickerView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)formatInterval:(double)arg1;
- (_Bool)endEditing:(_Bool)arg1;
- (void)setEditing:(_Bool)arg1;
- (_Bool)isEditing;
- (void)applyAppearanceForElement:(id)arg1;
- (void)prepareForElement:(id)arg1 inTableView:(id)arg2;
- (void)dateChanged:(id)arg1;
- (void)prepareDateTimePicker:(id)arg1;
- (id)init;

@end

