//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QEntryTableViewCell.h"

@class UIDatePicker, UILabel;

@interface QDateEntryTableViewCell : QEntryTableViewCell
{
    UIDatePicker *_pickerView;
    UILabel *_centeredLabel;
}

@property(retain, nonatomic) UILabel *centeredLabel; // @synthesize centeredLabel=_centeredLabel;
@property(retain, nonatomic) UIDatePicker *pickerView; // @synthesize pickerView=_pickerView;
- (void).cxx_destruct;
- (id)formatInterval:(double)arg1;
- (void)prepareForElement:(id)arg1 inTableView:(id)arg2;
- (void)dateChanged:(id)arg1;
- (void)createSubviews;
- (void)prepareDateTimePicker:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (id)init;

@end

