//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QEntryElement.h"

@class NSNumber;

@interface QDecimalElement : QEntryElement
{
    unsigned long long _fractionDigits;
    NSNumber *_numberValue;
}

@property(nonatomic) unsigned long long fractionDigits; // @synthesize fractionDigits=_fractionDigits;
@property(retain, nonatomic) NSNumber *numberValue; // @synthesize numberValue=_numberValue;
- (void).cxx_destruct;
- (void)fetchValueIntoObject:(id)arg1;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)init;
- (id)initWithValue:(id)arg1;
- (void)setFloatValue:(id)arg1;
- (id)initWithTitle:(id)arg1 value:(id)arg2;

@end

