//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSection.h"

@class NSString;

@interface QDynamicDataSection : QSection
{
    NSString *_emptyMessage;
    _Bool showLoading;
}

@property(retain, nonatomic) NSString *emptyMessage; // @synthesize emptyMessage=_emptyMessage;
- (void).cxx_destruct;
- (void)bindToObject:(id)arg1 withString:(id)arg2;
- (id)init;

@end

