//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QAppearance, QSection, UIViewController;

@interface QElement : NSObject
{
    QSection *_parentSection;
    UIViewController *_controller;
    NSString *_key;
    NSString *_bind;
    double _height;
    _Bool _hidden;
    CDUnknownBlockType _onSelected;
    NSString *_controllerAction;
    id _object;
    NSString *_controllerAccessoryAction;
    _Bool _enabled;
    _Bool _shallowBind;
    int _labelingPolicy;
    NSString *_accessibilityLabel;
    NSString *_accessibilityIdentifier;
}

+ (void)setAppearance:(id)arg1;
+ (id)appearance;
@property(copy, nonatomic) NSString *accessibilityIdentifier; // @synthesize accessibilityIdentifier=_accessibilityIdentifier;
@property(copy, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
@property(nonatomic) _Bool shallowBind; // @synthesize shallowBind=_shallowBind;
@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) int labelingPolicy; // @synthesize labelingPolicy=_labelingPolicy;
@property(retain, nonatomic) NSString *controllerAccessoryAction; // @synthesize controllerAccessoryAction=_controllerAccessoryAction;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) double height; // @synthesize height=_height;
@property(retain, nonatomic) id object; // @synthesize object=_object;
@property(retain, nonatomic) NSString *controllerAction; // @synthesize controllerAction=_controllerAction;
@property(copy, nonatomic) CDUnknownBlockType onSelected; // @synthesize onSelected=_onSelected;
@property(retain, nonatomic) NSString *bind; // @synthesize bind=_bind;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(nonatomic) __weak QSection *parentSection; // @synthesize parentSection=_parentSection;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)performAccessoryAction;
- (void)performAction;
- (void)fetchValueUsingBindingsIntoObject:(id)arg1;
- (void)bindToObject:(id)arg1 shallow:(_Bool)arg2;
- (void)bindToObject:(id)arg1;
- (void)bindToObject:(id)arg1 withString:(id)arg2;
- (void)fetchValueIntoObject:(id)arg1;
- (id)getIndexPath;
@property(readonly, nonatomic) unsigned long long visibleIndex; // @dynamic visibleIndex;
- (double)getRowHeightForTableView:(id)arg1;
- (void)selected:(id)arg1 controller:(id)arg2 indexPath:(id)arg3;
- (void)selectedAccessory:(id)arg1 controller:(id)arg2 indexPath:(id)arg3;
- (id)getOrCreateEmptyCell:(id)arg1;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)initWithKey:(id)arg1;
- (id)init;
@property(retain, nonatomic) QAppearance *appearance;

@end

