//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLabelElement.h"

#import "UITextInputTraits.h"

@class NSString, UITextInputPasswordRules;

@interface QEntryElement : QLabelElement <UITextInputTraits>
{
    NSString *_placeholder;
    NSString *_textValue;
    _Bool _hiddenToolbar;
    _Bool _enablesReturnKeyAutomatically;
    _Bool _secureTextEntry;
    _Bool _clearsOnBeginEditing;
    int _maxLength;
    NSString *_prefix;
    NSString *_suffix;
    CDUnknownBlockType _onValueChanged;
    id <QuickDialogEntryElementDelegate> _delegate;
    long long _autocorrectionType;
    long long _autocapitalizationType;
    long long _keyboardType;
    long long _keyboardAppearance;
    long long _returnKeyType;
    NSString *_customDateFormat;
}

@property int maxLength; // @synthesize maxLength=_maxLength;
@property(copy, nonatomic) NSString *customDateFormat; // @synthesize customDateFormat=_customDateFormat;
@property(nonatomic) _Bool clearsOnBeginEditing; // @synthesize clearsOnBeginEditing=_clearsOnBeginEditing;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry; // @synthesize secureTextEntry=_secureTextEntry;
@property(nonatomic) _Bool enablesReturnKeyAutomatically; // @synthesize enablesReturnKeyAutomatically=_enablesReturnKeyAutomatically;
@property(nonatomic) long long returnKeyType; // @synthesize returnKeyType=_returnKeyType;
@property(nonatomic) long long keyboardAppearance; // @synthesize keyboardAppearance=_keyboardAppearance;
@property(nonatomic) long long keyboardType; // @synthesize keyboardType=_keyboardType;
@property(nonatomic) long long autocapitalizationType; // @synthesize autocapitalizationType=_autocapitalizationType;
@property(nonatomic) long long autocorrectionType; // @synthesize autocorrectionType=_autocorrectionType;
@property(nonatomic) id <QuickDialogEntryElementDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setOnValueChanged:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)onValueChanged;
@property _Bool hiddenToolbar; // @synthesize hiddenToolbar=_hiddenToolbar;
@property(retain, nonatomic) NSString *suffix; // @synthesize suffix=_suffix;
@property(retain, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
@property(retain, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(retain, nonatomic) NSString *textValue; // @synthesize textValue=_textValue;
- (void).cxx_destruct;
- (void)handleEditingChanged:(id)arg1;
- (_Bool)canTakeFocus;
- (void)fetchValueIntoObject:(id)arg1;
- (void)fieldDidEndEditing;
- (void)selected:(id)arg1 controller:(id)arg2 indexPath:(id)arg3;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)initWithTitle:(id)arg1 Value:(id)arg2 Placeholder:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) UITextInputPasswordRules *passwordRules;
@property(nonatomic) long long smartDashesType;
@property(nonatomic) long long smartInsertDeleteType;
@property(nonatomic) long long smartQuotesType;
@property(nonatomic) long long spellCheckingType;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *textContentType;

@end

