//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLabelElement.h"

@interface QFloatElement : QLabelElement
{
    float _floatValue;
    float _minimumValue;
    float _maximumValue;
}

@property(nonatomic) float maximumValue; // @synthesize maximumValue=_maximumValue;
@property(nonatomic) float minimumValue; // @synthesize minimumValue=_minimumValue;
@property(nonatomic) float floatValue; // @synthesize floatValue=_floatValue;
- (void)setNilValueForKey:(id)arg1;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (void)valueChanged:(id)arg1;
- (void)fetchValueIntoObject:(id)arg1;
- (id)initWithValue:(float)arg1;
- (id)initWithTitle:(id)arg1 value:(float)arg2;
- (id)init;

@end

