//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QRootElement.h"

@class NSString, UIImage;

@interface QLabelElement : QRootElement
{
    id _value;
    UIImage *_image;
    long long _accessoryType;
    _Bool _keepSelected;
}

@property(nonatomic) _Bool keepSelected; // @synthesize keepSelected=_keepSelected;
@property(nonatomic) long long accessoryType; // @synthesize accessoryType=_accessoryType;
@property(retain, nonatomic) id value; // @synthesize value=_value;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)selected:(id)arg1 controller:(id)arg2 indexPath:(id)arg3;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (void)setIconNamed:(id)arg1;
@property(nonatomic) NSString *imageNamed;
- (id)initWithTitle:(id)arg1 Value:(id)arg2;

@end

