//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QElement.h"

@class UIProgressView;

@interface QProgressElement : QElement
{
    float _progress;
    UIProgressView *_bar;
}

@property(retain) UIProgressView *bar; // @synthesize bar=_bar;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)init;

@end

