//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLabelElement.h"

@class QRadioElement, QRadioSection;

@interface QRadioItemElement : QLabelElement
{
    unsigned long long _index;
    QRadioSection *_radioSection;
    QRadioElement *_radioElement;
}

- (void).cxx_destruct;
- (void)selected:(id)arg1 controller:(id)arg2 indexPath:(id)arg3;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)initWithIndex:(unsigned long long)arg1 RadioSection:(id)arg2;
- (id)initWithIndex:(unsigned long long)arg1 RadioElement:(id)arg2;

@end

