//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QRootBuilder : NSObject
{
}

+ (void)trySetProperty:(id)arg1 onObject:(id)arg2 withValue:(id)arg3 localized:(_Bool)arg4;
- (void)initializeMappings;
- (id)buildWithObject:(id)arg1;
- (void)buildSectionWithObject:(id)arg1 forRoot:(id)arg2;
- (id)buildSectionWithObject:(id)arg1;
- (id)buildElementWithObject:(id)arg1;
- (void)updateObject:(id)arg1 withPropertiesFrom:(id)arg2;

@end

