//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSString, QRootElement, UIView;

@interface QSection : NSObject
{
    NSString *_key;
    NSString *_bind;
    struct CGRect _entryPosition;
    QRootElement *_rootElement;
    UIView *_headerView;
    UIView *_footerView;
    id _object;
    NSString *_headerImage;
    NSString *_footerImage;
    NSDictionary *_elementTemplate;
    _Bool _canDeleteRows;
    NSMutableArray *_afterTemplateElements;
    NSMutableArray *_beforeTemplateElements;
    _Bool _hidden;
    NSString *title;
    NSString *footer;
    NSMutableArray *elements;
}

@property(retain, nonatomic) id object; // @synthesize object=_object;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(retain, nonatomic) NSMutableArray *beforeTemplateElements; // @synthesize beforeTemplateElements=_beforeTemplateElements;
@property(retain, nonatomic) NSMutableArray *afterTemplateElements; // @synthesize afterTemplateElements=_afterTemplateElements;
@property(nonatomic) _Bool canDeleteRows; // @synthesize canDeleteRows=_canDeleteRows;
@property(retain, nonatomic) NSDictionary *elementTemplate; // @synthesize elementTemplate=_elementTemplate;
@property(retain, nonatomic) NSString *footerImage; // @synthesize footerImage=_footerImage;
@property(retain, nonatomic) NSString *headerImage; // @synthesize headerImage=_headerImage;
@property(nonatomic) struct CGRect entryPosition; // @synthesize entryPosition=_entryPosition;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSString *bind; // @synthesize bind=_bind;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(nonatomic) QRootElement *rootElement; // @synthesize rootElement=_rootElement;
@property(retain, nonatomic) NSMutableArray *elements; // @synthesize elements;
@property(retain, nonatomic) NSString *footer; // @synthesize footer;
@property(retain, nonatomic) NSString *title; // @synthesize title;
- (void).cxx_destruct;
- (void)fetchValueUsingBindingsIntoObject:(id)arg1;
- (void)bindToObject:(id)arg1 withString:(id)arg2;
- (void)bindToObject:(id)arg1;
- (void)dealloc;
- (void)fetchValueIntoObject:(id)arg1;
- (unsigned long long)indexOfElement:(id)arg1;
- (void)insertElement:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addElement:(id)arg1;
- (id)initWithTitle:(id)arg1;
@property(readonly, nonatomic) _Bool needsEditing;
@property(readonly, nonatomic) unsigned long long visibleIndex; // @dynamic visibleIndex;
- (unsigned long long)getVisibleIndexForElement:(id)arg1;
- (long long)visibleNumberOfElements;
- (id)getVisibleElementForIndex:(long long)arg1;

@end

