//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLabelElement.h"

@class NSString, QSelectSection, UIImage;

@interface QSelectItemElement : QLabelElement
{
    unsigned long long _index;
    QSelectSection *_selectSection;
    UIImage *_checkmarkImage;
    NSString *_checkmarkImageNamed;
}

@property(copy, nonatomic) NSString *checkmarkImageNamed; // @synthesize checkmarkImageNamed=_checkmarkImageNamed;
@property(retain, nonatomic) UIImage *checkmarkImage; // @synthesize checkmarkImage=_checkmarkImage;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(nonatomic) __weak QSelectSection *selectSection; // @synthesize selectSection=_selectSection;
- (void).cxx_destruct;
- (void)updateCell:(id)arg1;
- (void)selected:(id)arg1 controller:(id)arg2 indexPath:(id)arg3;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)initWithIndex:(unsigned long long)arg1 selectSection:(id)arg2;

@end

