//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface QTableViewCell : UITableViewCell
{
    int _labelingPolicy;
}

@property(nonatomic) int labelingPolicy; // @synthesize labelingPolicy=_labelingPolicy;
- (void)applyAppearanceForElement:(id)arg1;
- (void)layoutSubviewsInsideBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1;

@end

