//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QRootElement.h"

@class NSString, UIColor, UIImage;

@interface QTextElement : QRootElement
{
    NSString *_text;
    UIColor *_color;
    UIImage *_image;
}

@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)fetchValueIntoObject:(id)arg1;
- (double)getRowHeightForTableView:(id)arg1;
- (id)getCellForTableView:(id)arg1 controller:(id)arg2;
- (id)initWithText:(id)arg1;
- (id)init;

@end

