//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class NSString;

@interface QTextField : UITextField
{
    NSString *_prefix;
    NSString *_suffix;
}

@property(copy, nonatomic) NSString *suffix; // @synthesize suffix=_suffix;
@property(copy, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
- (void).cxx_destruct;
- (void)drawTextInRect:(struct CGRect)arg1;

@end

