//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QuickDialogController.h"

@class NSString;

@interface QuickDialogWebController : QuickDialogController
{
    NSString *url;
}

@property(retain, nonatomic) NSString *url; // @synthesize url;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)reload;
- (void)presentResult:(id)arg1;
- (void)presentError:(id)arg1;
- (id)createRequestForUrl;

@end

