//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@class QRootElement, QuickDialogController;

@interface QuickDialogTableView : UITableView
{
    _Bool _deselectRowWhenViewAppears;
    QRootElement *_root;
    id <QuickDialogDelegate> _quickDialogDelegate;
    id <UITableViewDelegate> _quickDialogTableDelegate;
    id <UITableViewDataSource> _quickDialogDataSource;
    QuickDialogController *_controller;
}

@property(nonatomic) __weak QuickDialogController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) id <UITableViewDataSource> quickDialogDataSource; // @synthesize quickDialogDataSource=_quickDialogDataSource;
@property(retain, nonatomic) id <UITableViewDelegate> quickDialogTableDelegate; // @synthesize quickDialogTableDelegate=_quickDialogTableDelegate;
@property(nonatomic) __weak id <QuickDialogDelegate> quickDialogDelegate; // @synthesize quickDialogDelegate=_quickDialogDelegate;
@property(nonatomic) _Bool deselectRowWhenViewAppears; // @synthesize deselectRowWhenViewAppears=_deselectRowWhenViewAppears;
@property(retain, nonatomic) QRootElement *root; // @synthesize root=_root;
- (void).cxx_destruct;
- (void)endEditingOnVisibleCells;
- (void)reloadRowHeights;
- (void)reloadCellForElements:(id)arg1;
- (void)deselectRows;
- (id)cellForElement:(id)arg1;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
- (id)indexForElement:(id)arg1;
- (void)applyAppearanceForRoot:(id)arg1;
- (void)reloadData;
- (id)initWithController:(id)arg1;

@end

