//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FileItem.h"

@class GDURLMetadata, NSString;

__attribute__((visibility("hidden")))
@interface RemoteFileItem : FileItem
{
    _Bool _shouldDisplayPerm;
    NSString *_fileUrl;
    GDURLMetadata *_metadata;
}

@property(retain, nonatomic) GDURLMetadata *metadata; // @synthesize metadata=_metadata;
@property(nonatomic) _Bool shouldDisplayPerm; // @synthesize shouldDisplayPerm=_shouldDisplayPerm;
@property(retain, nonatomic) NSString *fileUrl; // @synthesize fileUrl=_fileUrl;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (void)setFilePath:(id)arg1 fileName:(id)arg2 isDirectory:(_Bool)arg3 size:(unsigned long long)arg4 createDate:(id)arg5 modificationDate:(id)arg6;
- (void)setURLMetadata:(id)arg1;
- (id)parentUrl;
- (id)permissionString;
- (void)setFilePath:(id)arg1;
- (id)sourceImageURLWithFormatName:(id)arg1;
- (id)sourceImageUUID;
- (id)filePath;

@end

