//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGFocusedInput.h"

#import "UITextFieldDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface RenameView : TGFocusedInput <UITextFieldDelegate>
{
    _Bool _isDirectory;
    id <RenameViewDelegate> delegate;
}

@property(nonatomic) id <RenameViewDelegate> delegate; // @synthesize delegate;
- (_Bool)shouldEnableDoneButtonWithText:(id)arg1;
- (void)didDoneWithText:(id)arg1;
- (void)didCancel:(id)arg1;
- (void)dealloc;
- (void)showInViewController:(id)arg1 delegate:(id)arg2 isDirectory:(_Bool)arg3;
- (void)initiateData:(id)arg1;
- (void)initiateUI:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

