//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, RenameView, UIImage;

@protocol RenameViewDelegate <NSObject>
- (NSString *)nameForRenameView:(RenameView *)arg1;
- (UIImage *)iconForRenameView:(RenameView *)arg1;
- (void)renameView:(RenameView *)arg1 completeWithName:(NSString *)arg2;
- (_Bool)renameView:(RenameView *)arg1 checkIfNameExisted:(NSString *)arg2;
@end

