//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewDelegate.h"

@class NSIndexPath;

@protocol ReorderTableViewDelegate <UITableViewDelegate>
- (_Bool)canMoveRowFromIndexPath:(NSIndexPath *)arg1 toIndexPath:(NSIndexPath *)arg2;
- (_Bool)canMoveRowAtIndexPath:(NSIndexPath *)arg1;
- (void)finishReorderingWithObject:(id)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)moveRowAtIndexPath:(NSIndexPath *)arg1 toIndexPath:(NSIndexPath *)arg2;
- (id)saveObjectAndInsertBlankRowAtIndexPath:(NSIndexPath *)arg1;
@end

