//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, RMActionController, UIImage, UIView;

__attribute__((visibility("hidden")))
@interface RMAction : NSObject
{
    _Bool _dismissesActionController;
    NSString *_title;
    UIImage *_image;
    long long _style;
    RMActionController *_controller;
    CDUnknownBlockType _handler;
    UIView *_view;
}

+ (id)actionWithStyle:(long long)arg1 andHandler:(CDUnknownBlockType)arg2;
+ (id)actionWithImage:(id)arg1 style:(long long)arg2 andHandler:(CDUnknownBlockType)arg3;
+ (id)actionWithTitle:(id)arg1 style:(long long)arg2 andHandler:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) __weak RMActionController *controller; // @synthesize controller=_controller;
@property(nonatomic) _Bool dismissesActionController; // @synthesize dismissesActionController=_dismissesActionController;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)viewTapped:(id)arg1;
- (id)loadView;
- (id)imageWithColor:(id)arg1;
- (void)executeHandlerOfCancelActionWithController:(id)arg1;
- (_Bool)containsCancelAction;
- (id)init;

@end

