//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface RoundedIconView : UIButton
{
    _Bool _enabledRoundCorners;
    UIColor *_fillColor;
    struct CGPoint _previousPoint;
}

@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(nonatomic) struct CGPoint previousPoint; // @synthesize previousPoint=_previousPoint;
@property(nonatomic) _Bool enabledRoundCorners; // @synthesize enabledRoundCorners=_enabledRoundCorners;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

