//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCPageViewController, UIViewController;

@protocol SCPageViewControllerDataSource <NSObject>
- (UIViewController *)pageViewController:(SCPageViewController *)arg1 viewControllerForPageAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPagesInPageViewController:(SCPageViewController *)arg1;
@end

