//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCPageViewControllerViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSIndexSet, NSMutableArray, NSString, SCScrollView;

__attribute__((visibility("hidden")))
@interface SCPageViewController : UIViewController <SCPageViewControllerViewDelegate, UIScrollViewDelegate>
{
    _Bool _pagingEnabled;
    _Bool _continuousNavigationEnabled;
    _Bool _shouldLayoutPagesOnRest;
    _Bool _isAnimatingLayouterChange;
    _Bool _isContentOffsetBlocked;
    _Bool _isViewVisible;
    _Bool _isRotating;
    id <SCPageLayouterProtocol> _layouter;
    id <SCPageViewControllerDataSource> _dataSource;
    id <SCPageViewControllerDelegate> _delegate;
    SCScrollView *_scrollView;
    unsigned long long _currentPage;
    unsigned long long _numberOfPages;
    id <SCEasingFunctionProtocol> _easingFunction;
    double _animationDuration;
    id <SCPageLayouterProtocol> _previousLayouter;
    NSMutableArray *_pages;
    NSMutableArray *_visibleControllers;
    double _layouterInterItemSpacing;
    unsigned long long _blockedPageIndex;
    NSIndexSet *_insertionIndexes;
    struct UIEdgeInsets _layouterContentInset;
}

@property(retain, nonatomic) NSIndexSet *insertionIndexes; // @synthesize insertionIndexes=_insertionIndexes;
@property(nonatomic) unsigned long long blockedPageIndex; // @synthesize blockedPageIndex=_blockedPageIndex;
@property(nonatomic) double layouterInterItemSpacing; // @synthesize layouterInterItemSpacing=_layouterInterItemSpacing;
@property(nonatomic) struct UIEdgeInsets layouterContentInset; // @synthesize layouterContentInset=_layouterContentInset;
@property(nonatomic) _Bool isRotating; // @synthesize isRotating=_isRotating;
@property(nonatomic) _Bool isViewVisible; // @synthesize isViewVisible=_isViewVisible;
@property(nonatomic) _Bool isContentOffsetBlocked; // @synthesize isContentOffsetBlocked=_isContentOffsetBlocked;
@property(retain, nonatomic) NSMutableArray *visibleControllers; // @synthesize visibleControllers=_visibleControllers;
@property(retain, nonatomic) NSMutableArray *pages; // @synthesize pages=_pages;
@property(retain, nonatomic) id <SCPageLayouterProtocol> previousLayouter; // @synthesize previousLayouter=_previousLayouter;
@property(nonatomic) _Bool isAnimatingLayouterChange; // @synthesize isAnimatingLayouterChange=_isAnimatingLayouterChange;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(retain, nonatomic) id <SCEasingFunctionProtocol> easingFunction; // @synthesize easingFunction=_easingFunction;
@property(nonatomic) _Bool shouldLayoutPagesOnRest; // @synthesize shouldLayoutPagesOnRest=_shouldLayoutPagesOnRest;
@property(nonatomic) _Bool continuousNavigationEnabled; // @synthesize continuousNavigationEnabled=_continuousNavigationEnabled;
@property(nonatomic) _Bool pagingEnabled; // @synthesize pagingEnabled=_pagingEnabled;
@property(nonatomic) unsigned long long numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(nonatomic) unsigned long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) SCScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <SCPageViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SCPageViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) id <SCPageLayouterProtocol> layouter; // @synthesize layouter=_layouter;
- (void).cxx_destruct;
- (void)movePageAtIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)deletePagesAtIndexes:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)insertPagesAtIndexes:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)reloadPagesAtIndexes:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_removePageAtIndex:(unsigned long long)arg1;
- (id)_createAndInsertNewPageAtIndex:(unsigned long long)arg1;
- (void)_sortSubviewsByZPosition;
- (void)_centerOnPageIndex:(unsigned long long)arg1;
- (void)_setAnimatableSublayerTransform:(struct CATransform3D)arg1 forViewController:(id)arg2;
- (struct CGRect)_subtractRect:(struct CGRect)arg1 fromRect:(struct CGRect)arg2 withEdge:(unsigned int)arg3;
- (void)_adjustTargetContentOffset:(inout struct CGPoint *)arg1 withVelocity:(struct CGPoint)arg2;
- (struct CGPoint)_nextStepOffsetForFrame:(struct CGRect)arg1 withVelocity:(struct CGPoint)arg2;
- (unsigned long long)_calculateCurrentPage;
- (void)_unblockContentOffset;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_blockContentOffsetOnPageAtIndex:(unsigned long long)arg1;
- (void)pageViewControllerViewDidChangeFrame:(id)arg1;
- (void)pageViewControllerViewWillChangeFrame:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)_updateFramesAndTriggerAppearanceCallbacks;
- (void)_tilePages;
- (void)_updateNavigationContraints;
- (void)_updateBoundsAndConstraints;
@property(readonly, nonatomic) _Bool visible;
- (unsigned long long)pageIndexForViewController:(id)arg1;
- (id)viewControllerForPageAtIndex:(unsigned long long)arg1;
- (double)visiblePercentageForViewController:(id)arg1;
@property(readonly, nonatomic) NSArray *visibleViewControllers;
@property(readonly, nonatomic) NSArray *loadedViewControllers;
- (void)navigateToPageAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)reloadData;
- (void)setLayouter:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setLayouter:(id)arg1 andFocusOnIndex:(unsigned long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (void)_commonSetup;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

