//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

__attribute__((visibility("hidden")))
@interface SCPageViewControllerPageDetails : NSObject
{
    UIViewController *_viewController;
    double _visiblePercentage;
    unsigned long long _zPosition;
}

@property(nonatomic) unsigned long long zPosition; // @synthesize zPosition=_zPosition;
@property(nonatomic) double visiblePercentage; // @synthesize visiblePercentage=_visiblePercentage;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;

@end

