//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCSafariPageWrapperViewController;

@protocol SCSafariPageWrapperViewControllerDelegate <NSObject>

@optional
- (void)safariPageWrapperViewControllerDidEndDragging:(SCSafariPageWrapperViewController *)arg1 atPercentage:(double)arg2;
- (void)safariPageWrapperViewController:(SCSafariPageWrapperViewController *)arg1 didScrollToPercentage:(double)arg2;
@end

