//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCPageLayouterProtocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SCSafariZoomedOutLayouter : NSObject <SCPageLayouterProtocol>
{
    double interItemSpacing;
    unsigned long long navigationType;
    unsigned long long numberOfPagesToPreloadBeforeCurrentPage;
    unsigned long long numberOfPagesToPreloadAfterCurrentPage;
    unsigned long long navigationConstraintType;
    double _pagePercentage;
    struct UIEdgeInsets _contentInset;
}

@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) double pagePercentage; // @synthesize pagePercentage=_pagePercentage;
@property(nonatomic) unsigned long long navigationConstraintType; // @synthesize navigationConstraintType;
@property(nonatomic) unsigned long long numberOfPagesToPreloadAfterCurrentPage; // @synthesize numberOfPagesToPreloadAfterCurrentPage;
@property(nonatomic) unsigned long long numberOfPagesToPreloadBeforeCurrentPage; // @synthesize numberOfPagesToPreloadBeforeCurrentPage;
@property(nonatomic) unsigned long long navigationType; // @synthesize navigationType;
@property(nonatomic) double interItemSpacing; // @synthesize interItemSpacing;
- (struct CATransform3D)sublayerTransformForPageAtIndex:(long long)arg1 withFrame:(struct CGRect)arg2 totalNumberOfPages:(double)arg3 contentOffset:(struct CGPoint)arg4;
- (double)interItemSpacingForPageViewController:(id)arg1 totalNumberOfPages:(double)arg2;
- (void)animatePageDeletionAtIndex:(unsigned long long)arg1 viewController:(id)arg2 pageViewController:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)animatePageInsertionAtIndex:(unsigned long long)arg1 viewController:(id)arg2 pageViewController:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (struct CATransform3D)sublayerTransformForPageAtIndex:(unsigned long long)arg1 contentOffset:(struct CGPoint)arg2 pageViewController:(id)arg3;
- (unsigned long long)zPositionForPageAtIndex:(unsigned long long)arg1 pageViewController:(id)arg2;
- (struct CGRect)finalFrameForPageAtIndex:(unsigned long long)arg1 pageViewController:(id)arg2;
- (struct CGPoint)contentOffsetForPageViewController:(id)arg1;
- (struct CGSize)contentSizeForPageViewController:(id)arg1;
- (double)interItemSpacingForPageViewController:(id)arg1;
- (struct UIEdgeInsets)contentInsetForPageViewController:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

