//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCPageLayouter.h"

__attribute__((visibility("hidden")))
@interface SCSafariZoomedInLayouter : SCPageLayouter
{
}

- (unsigned long long)zPositionForPageAtIndex:(unsigned long long)arg1 pageViewController:(id)arg2;
- (id)init;

@end

