//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCPageViewControllerDataSource.h"
#import "SCPageViewControllerDelegate.h"
#import "SCSafariPageWrapperViewControllerDelegate.h"

@class NSArray, NSString, SCPageViewController, SCSafariZoomedOutLayouter;

__attribute__((visibility("hidden")))
@interface SCSafariPageController : UIViewController <SCPageViewControllerDataSource, SCPageViewControllerDelegate, SCSafariPageWrapperViewControllerDelegate>
{
    _Bool _isZoomedOut;
    _Bool _shouldIgnoreUpdates;
    id <SCSafariPageControllerDataSource> _dataSource;
    id <SCSafariPageControllerDelegate> _delegate;
    unsigned long long _currentPage;
    SCPageViewController *_pageViewController;
    id <SCPageLayouterProtocol> _zoomedInLayouter;
    SCSafariZoomedOutLayouter *_zoomedOutLayouter;
}

@property(nonatomic) _Bool shouldIgnoreUpdates; // @synthesize shouldIgnoreUpdates=_shouldIgnoreUpdates;
@property(retain, nonatomic) SCSafariZoomedOutLayouter *zoomedOutLayouter; // @synthesize zoomedOutLayouter=_zoomedOutLayouter;
@property(retain, nonatomic) id <SCPageLayouterProtocol> zoomedInLayouter; // @synthesize zoomedInLayouter=_zoomedInLayouter;
@property(retain, nonatomic) SCPageViewController *pageViewController; // @synthesize pageViewController=_pageViewController;
@property(nonatomic) unsigned long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) __weak id <SCSafariPageControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SCSafariPageControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) _Bool isZoomedOut; // @synthesize isZoomedOut=_isZoomedOut;
- (void).cxx_destruct;
- (void)_setAnimatableSublayerTransform:(struct CATransform3D)arg1 forViewController:(id)arg2;
- (void)_updatePageLayout;
@property(readonly, nonatomic) NSArray *visibleViewControllers;
@property(readonly, nonatomic) NSArray *loadedViewControllers;
@property(readonly, nonatomic) unsigned long long numberOfPages;
- (double)visiblePercentageForViewController:(id)arg1;
- (void)navigateToPageAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)movePageAtIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)deletePagesAtIndexes:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)insertPagesAtIndexes:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)reloadPagesAtIndexes:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)reloadData;
- (void)safariPageWrapperViewControllerDidEndDragging:(id)arg1 atPercentage:(double)arg2;
- (void)safariPageWrapperViewController:(id)arg1 didScrollToPercentage:(double)arg2;
- (void)pageViewController:(id)arg1 didNavigateToOffset:(struct CGPoint)arg2;
- (void)pageViewController:(id)arg1 didNavigateToPageAtIndex:(unsigned long long)arg2;
- (void)pageViewController:(id)arg1 didHideViewController:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)pageViewController:(id)arg1 didShowViewController:(id)arg2 atIndex:(unsigned long long)arg3;
- (id)pageViewController:(id)arg1 viewControllerForPageAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPagesInPageViewController:(id)arg1;
- (id)viewControllerForPageAtIndex:(unsigned long long)arg1;
- (void)zoomIntoPageAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)zoomOutAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

