//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIBezierPath;

__attribute__((visibility("hidden")))
@interface SCScrollViewTouchApprovalArea : NSObject
{
    UIBezierPath *_path;
    unsigned long long _direction;
}

@property(nonatomic) unsigned long long direction; // @synthesize direction=_direction;
@property(retain, nonatomic) UIBezierPath *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (id)init;

@end

