//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TGSafeArray.h"

@class FileItem, NSMutableArray, NSString, RemoteFileItem;

__attribute__((visibility("hidden")))
@interface SearchObjectArrayProxy : NSObject <TGSafeArray>
{
    NSMutableArray *main;
    FileItem *_tempObject;
    RemoteFileItem *_remoteTempObject;
}

@property(retain, nonatomic) RemoteFileItem *remoteTempObject; // @synthesize remoteTempObject=_remoteTempObject;
@property(retain, nonatomic) FileItem *tempObject; // @synthesize tempObject=_tempObject;
@property(retain, nonatomic) NSMutableArray *main; // @synthesize main;
- (void).cxx_destruct;
- (long long)insertObject:(id)arg1 atSortMode:(int)arg2 preferredIndex:(long long)arg3;
- (void)sortWithMode:(int)arg1;
- (id)firstObject;
- (void)removeObjectsInArray:(id)arg1;
- (void)insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)removeObjectsAtIndexes:(id)arg1;
- (void)removeObjectAtIndex:(unsigned long long)arg1;
- (void)addObject:(id)arg1;
- (unsigned long long)count;
- (void)removeObject:(id)arg1;
- (void)replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (_Bool)containsObject:(id)arg1;
- (long long)indexOfObject:(id)arg1;
- (void)removeAllObjects;
- (void)addObjectsFromArray:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

