//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TIGIBrowserViewDataSource.h"
#import "TIGIBrowserViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "UIToolbarDelegate.h"

@class FileItem, NSArray, NSDate, NSMutableArray, NSString, NSThread, NSTimer, OOSearchBar, TGMenuController, TGPageViewController, TGThemePopoverController, TIGIBrowserView, UISegmentedControl, UITableView;

__attribute__((visibility("hidden")))
@interface SearchController : UIViewController <UIToolbarDelegate, UITextFieldDelegate, UISearchBarDelegate, UISearchDisplayDelegate, TIGIBrowserViewDataSource, TIGIBrowserViewDelegate, UIGestureRecognizerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    struct _opaque_pthread_mutex_t _plock;
    _Bool _local;
    int _identifier;
    int _searchType;
    int _intCurrentProxyCount;
    OOSearchBar *searchBar;
    NSString *_currentDirectory;
    TGMenuController *_actionMenu;
    FileItem *_openWithFileItem;
    NSArray *_openItemList;
    NSDate *_delay;
    TGPageViewController *_pageObject;
    TGThemePopoverController *_openWithListForiPad;
    UITableView *_autocompleteTextListView;
    NSString *_searchCondition;
    NSString *_searchValue;
    TIGIBrowserView *_browserView;
    NSThread *_searchThread;
    NSString *_text;
    id <TGSafeArray> _foundProxiesList;
    NSMutableArray *_resultStack;
    NSTimer *_startSearchTimer;
    UIViewController *_subParent;
    UISegmentedControl *_control;
    NSArray *_hintsList;
}

@property(retain, nonatomic) NSArray *hintsList; // @synthesize hintsList=_hintsList;
@property(retain, nonatomic) UISegmentedControl *control; // @synthesize control=_control;
@property(retain, nonatomic) UIViewController *subParent; // @synthesize subParent=_subParent;
@property(retain, nonatomic) NSTimer *startSearchTimer; // @synthesize startSearchTimer=_startSearchTimer;
@property(retain, nonatomic) NSMutableArray *resultStack; // @synthesize resultStack=_resultStack;
@property(nonatomic) int intCurrentProxyCount; // @synthesize intCurrentProxyCount=_intCurrentProxyCount;
@property(retain, nonatomic) id <TGSafeArray> foundProxiesList; // @synthesize foundProxiesList=_foundProxiesList;
@property(retain) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSThread *searchThread; // @synthesize searchThread=_searchThread;
@property(retain, nonatomic) TIGIBrowserView *browserView; // @synthesize browserView=_browserView;
@property(retain, nonatomic) NSString *searchValue; // @synthesize searchValue=_searchValue;
@property(retain, nonatomic) NSString *searchCondition; // @synthesize searchCondition=_searchCondition;
@property(nonatomic) int searchType; // @synthesize searchType=_searchType;
@property(retain, nonatomic) UITableView *autocompleteTextListView; // @synthesize autocompleteTextListView=_autocompleteTextListView;
@property(retain, nonatomic) TGThemePopoverController *openWithListForiPad; // @synthesize openWithListForiPad=_openWithListForiPad;
@property(nonatomic) _Bool local; // @synthesize local=_local;
@property(retain, nonatomic) TGPageViewController *pageObject; // @synthesize pageObject=_pageObject;
@property(retain, nonatomic) NSDate *delay; // @synthesize delay=_delay;
@property(retain, nonatomic) NSArray *openItemList; // @synthesize openItemList=_openItemList;
@property(retain, nonatomic) FileItem *openWithFileItem; // @synthesize openWithFileItem=_openWithFileItem;
@property(retain, nonatomic) TGMenuController *actionMenu; // @synthesize actionMenu=_actionMenu;
@property(retain, nonatomic) NSString *currentDirectory; // @synthesize currentDirectory=_currentDirectory;
@property(nonatomic) int identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) OOSearchBar *searchBar; // @synthesize searchBar;
- (void).cxx_destruct;
- (long long)positionForBar:(id)arg1;
- (void)dealloc;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)cancel;
- (void)cancelAnimated:(_Bool)arg1;
- (void)searchFiles;
- (void)startSearchThread;
- (id)browserView:(id)arg1 accessoryForItemAtIndexPath:(id)arg2;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)browserViewDidScroll:(id)arg1;
- (void)browserView:(id)arg1 accessoryButtonTappedForItemAtIndexPath:(id)arg2;
- (void)browserView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)browserView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)browserView:(id)arg1 deleteButtonTappedForItemAtIndexPath:(id)arg2;
- (id)browserView:(id)arg1 itemForSectionAtIndexPath:(id)arg2;
- (long long)browserView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)browserView:(id)arg1 willSortWithSortMode:(int)arg2;
- (void)browserViewDidDeselectAllItems:(id)arg1;
- (void)browserViewDidSelectAllItems:(id)arg1;
- (void)browserViewRequireToLoadingThumbnailIfNeeds:(id)arg1 atIndexPath:(id)arg2;
- (long long)numberOfSectionsInBrowserView:(id)arg1;
- (void)finishSearch;
- (void)showInSearch;
- (void)scheduleNewSearch;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)searchRangeChanged:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)cancelOrEndEditing;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)replaceFoundProxyAtIndex:(long long)arg1 withPath:(id)arg2;
- (void)_updateWithResult:(id)arg1;
- (void)appendResult;
- (void)appendResultOnMainThread;
- (void)deleteSearchWithIndexPaths:(id)arg1;
- (void)prepareForSearch;
- (void)stopSearch;
- (void)resetSearch;
- (void)reloadSearchResult;
- (void)showSearchViewAnimated:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

