//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGPreferencesTableViewController.h"

@class UIAlertView;

__attribute__((visibility("hidden")))
@interface SecurityTableViewController : TGPreferencesTableViewController
{
    UIAlertView *alert;
    id _context;
}

@property(retain, nonatomic) id context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)swithAccessCheckbox;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)swithTouchIDCheckbox;
- (void)changeTimeout:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

@end

