//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SMBShare : NSObject
{
    struct smb_session *smbv1;
    unsigned short tid;
    struct smb2_context *smb;
    struct pollfd pfd;
    NSString *user;
}

- (void).cxx_destruct;
- (void)dealloc;
- (int)reconnect_v1:(id)arg1;
- (int)connect_v1:(id)arg1 server:(id)arg2 username:(id)arg3 password:(id)arg4 workground:(id)arg5;
- (unsigned short)tid;
- (struct smb_session *)context_v1;
- (struct smb2_context *)context;
- (id)user;
- (id)initForSMB:(id)arg1 version:(int)arg2;

@end

