//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TagColorView;

@protocol TagColorViewDelegate <NSObject>
- (void)tagColorViewWillHide:(TagColorView *)arg1;
- (void)tagColorView:(TagColorView *)arg1 selectedColorIndex:(long long)arg2;
@end

