//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

__attribute__((visibility("hidden")))
@interface TagColorView : UIView
{
    _Bool isShowing;
    struct CGPoint pointToShow;
    id <TagColorViewDelegate> _delegate;
}

@property(nonatomic) id <TagColorViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)showInView:(id)arg1 fromButton:(id)arg2 withDelegate:(id)arg3;
- (void)hide;
- (void)handleDismissTap:(id)arg1;
- (void)handleColorTagTap:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

