//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface TempBoardTableViewController : TGThemeTableViewController
{
    NSMutableArray *_allObjects;
}

@property(retain, nonatomic) NSMutableArray *allObjects; // @synthesize allObjects=_allObjects;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)close;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

@end

