//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGAbstractViewerViewController.h"

__attribute__((visibility("hidden")))
@interface TerminalViewerController : TGAbstractViewerViewController
{
}

+ (void)showAsksToOpenDialogWithCompletion:(CDUnknownBlockType)arg1;
+ (_Bool)shouldAsksUserToOpen;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)showInController:(id)arg1 animated:(_Bool)arg2;
- (id)initWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;

@end

