//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextViewDelegate.h"

@class NSMutableString, NSString, NSThread, UITextView;

__attribute__((visibility("hidden")))
@interface TerminalViewController : UIViewController <UITextViewDelegate>
{
    _Bool run;
    _Bool ready;
    int master;
    struct termios oldt;
    int pid;
    int isStop;
    UITextView *_textView;
    NSMutableString *_command;
    NSMutableString *_history;
    NSThread *_thread;
}

@property(retain, nonatomic) NSThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) NSMutableString *history; // @synthesize history=_history;
@property(retain, nonatomic) NSMutableString *command; // @synthesize command=_command;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void)didReceiveMemoryWarning;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)addString:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)forkACommand;
- (void)_showError;
- (void)done:(id)arg1;
- (void)dealloc;
- (void)resizeTextViewToAccommodateKeyboardFrame:(struct CGRect)arg1 withAnimationDuration:(double)arg2 animationCurve:(long long)arg3;
- (void)resizeTextViewWithKeyboardNotification:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

