//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeNavigationViewController.h"

#import "TGViewerProtocol.h"

@class FileItem, MBProgressHUD, NSArray, NSIndexPath, NSString, TGNetworkOperationObject, UILabel, UINavigationController<TGViewerProtocol>, UIProgressView;

__attribute__((visibility("hidden")))
@interface TGAbstractViewerViewController : TGThemeNavigationViewController <TGViewerProtocol>
{
    _Bool _animated;
    _Bool _isFileChanged;
    _Bool _previewing;
    _Bool _needsDismissAnimation;
    MBProgressHUD *_HUD;
    FileItem *_fileItem;
    FileItem *_resultItem;
    NSArray *_fileList;
    NSString *_viewerId;
    NSArray *_tempFileList;
    UIProgressView *_progressView;
    UILabel *_titleLabel;
    TGNetworkOperationObject *_loadingObject;
    UINavigationController<TGViewerProtocol> *_errorVc;
    UILabel *_downloadinglabel;
    id <TGViewerDelegate> _viewerDelegate;
    NSIndexPath *_fileIndexPath;
}

+ (void)showAsksToOpenDialogWithCompletion:(CDUnknownBlockType)arg1;
+ (_Bool)shouldAsksUserToOpen;
+ (_Bool)canOpenFile:(id)arg1;
+ (Class)realClassNameForFileItem:(id)arg1;
+ (id)createViewerWithClass:(id)arg1 fileItem:(id)arg2 moreInfo:(id)arg3 isPreviewer:(_Bool)arg4 delegate:(id)arg5;
@property(nonatomic) _Bool needsDismissAnimation; // @synthesize needsDismissAnimation=_needsDismissAnimation;
@property(retain, nonatomic) NSIndexPath *fileIndexPath; // @synthesize fileIndexPath=_fileIndexPath;
@property(nonatomic) __weak id <TGViewerDelegate> viewerDelegate; // @synthesize viewerDelegate=_viewerDelegate;
@property(retain, nonatomic) UILabel *downloadinglabel; // @synthesize downloadinglabel=_downloadinglabel;
@property(retain, nonatomic) UINavigationController<TGViewerProtocol> *errorVc; // @synthesize errorVc=_errorVc;
@property(nonatomic) __weak TGNetworkOperationObject *loadingObject; // @synthesize loadingObject=_loadingObject;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) NSArray *tempFileList; // @synthesize tempFileList=_tempFileList;
@property(nonatomic, getter=isPreviewing) _Bool previewing; // @synthesize previewing=_previewing;
@property(nonatomic) _Bool isFileChanged; // @synthesize isFileChanged=_isFileChanged;
@property(nonatomic) _Bool animated; // @synthesize animated=_animated;
@property(retain, nonatomic) NSString *viewerId; // @synthesize viewerId=_viewerId;
@property(nonatomic) __weak NSArray *fileList; // @synthesize fileList=_fileList;
@property(retain, nonatomic) FileItem *resultItem; // @synthesize resultItem=_resultItem;
@property(retain, nonatomic) FileItem *fileItem; // @synthesize fileItem=_fileItem;
@property(retain, nonatomic) MBProgressHUD *HUD; // @synthesize HUD=_HUD;
- (void).cxx_destruct;
- (void)dealloc;
- (id)previewActionItems;
- (void)cancelRemoteFileLoading:(id)arg1;
- (id)loadRemoteFileWithCompletion:(CDUnknownBlockType)arg1;
- (void)viewDidLoad;
- (void)commit;
- (void)dismiss;
- (id)viewerName;
- (void)showErrorScreenWithMessage:(id)arg1 showHexdump:(_Bool)arg2;
- (void)writeRecents;
- (void)showInController:(id)arg1 animated:(_Bool)arg2;
- (id)initWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;
- (void)doneclicked;
- (id)initForPreviewingWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

