//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGApplicationsViewController.h"

__attribute__((visibility("hidden")))
@interface TGAppsManagerSearchViewController : TGApplicationsViewController
{
}

- (_Bool)_shouldFreeWhenReceiveMemoryWarning;
- (id)itemsForPanelMenuManager:(id)arg1;
- (id)itemsForBarMenuManager:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)setToolbarItems:(id)arg1;
- (void)setToolbarItems:(id)arg1 animated:(_Bool)arg2;
- (id)toolbarItems;
- (id)navigationItem;
- (id)currentPath;
- (void)viewWillAppear:(_Bool)arg1;
- (void)doLoadingPage;
- (void)loadFilesWithSortMode:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

