//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, TGAudioProvider;

@protocol TGAudioProviderDelegate <NSObject>
- (void)audioProvider:(TGAudioProvider *)arg1 didFinishPlayingAudioAtIndex:(long long)arg2 withError:(NSError *)arg3;
- (void)audioProvider:(TGAudioProvider *)arg1 didFinishLoadingAudioAtIndex:(long long)arg2 withError:(NSError *)arg3;
@end

