//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMDatabaseQueue, NSMutableArray;

__attribute__((visibility("hidden")))
@interface TGDatabaseInterface : NSObject
{
    _Bool _recentsDisabled;
    FMDatabaseQueue *_databaseQueue;
    NSMutableArray *_tempItems;
}

@property(retain, nonatomic) NSMutableArray *tempItems; // @synthesize tempItems=_tempItems;
@property(nonatomic, getter=isRecentsDisabled) _Bool recentsDisabled; // @synthesize recentsDisabled=_recentsDisabled;
@property(retain, nonatomic) FMDatabaseQueue *databaseQueue; // @synthesize databaseQueue=_databaseQueue;
- (void).cxx_destruct;
- (void)dealloc;
- (void)deleteRecents;
- (void)deleteRecentItemWithID:(id)arg1;
- (void)commitTempItemWithSourceUrl:(id)arg1 fileUrl:(id)arg2 parentUrl:(id)arg3 newName:(id)arg4;
- (void)removeTempItemWithSourceUrl:(id)arg1;
- (void)addTempItemToRecentsWithType:(int)arg1 fileName:(id)arg2 fileTye:(int)arg3 sourceUrl:(id)arg4 sourceParentUrl:(id)arg5;
- (void)addItemToRecentsWithType:(int)arg1 fileName:(id)arg2 fileTye:(int)arg3 fileUrl:(id)arg4 parentUrl:(id)arg5 sourceUrl:(id)arg6 sourceParentUrl:(id)arg7;
- (void)addItemToRecentsWithType:(int)arg1 fileName:(id)arg2 fileTye:(int)arg3 fileUrl:(id)arg4 parentUrl:(id)arg5;
- (id)recents;
- (void)initDatabaseIfNeeds;
- (id)init;

@end

