//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TGInfoViewProtocol.h"

@class NSString, UILabel, UITapGestureRecognizer;

__attribute__((visibility("hidden")))
@interface TGDirectoryInfoView : UIView <TGInfoViewProtocol>
{
    _Bool __addedLine;
    double h;
    id <TGDirectoryInfoViewDelegate> _delegate;
    UITapGestureRecognizer *_gesture;
    UILabel *_fileSystemLabel;
    UILabel *_itemsLabel;
    UILabel *_spaceLabel;
}

@property(retain, nonatomic) UILabel *spaceLabel; // @synthesize spaceLabel=_spaceLabel;
@property(retain, nonatomic) UILabel *itemsLabel; // @synthesize itemsLabel=_itemsLabel;
@property(retain, nonatomic) UILabel *fileSystemLabel; // @synthesize fileSystemLabel=_fileSystemLabel;
@property(retain, nonatomic) UITapGestureRecognizer *gesture; // @synthesize gesture=_gesture;
@property(nonatomic) __weak id <TGDirectoryInfoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)space;
- (id)items;
- (id)fileSystem;
- (_Bool)canOpenPropertiesForPath:(id)arg1;
- (void)setFileSystemInfo:(id)arg1;
- (void)setDiskUsageInfo:(id)arg1;
- (void)setNumberOfItemsInfo:(id)arg1;
- (void)itemTapped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

