//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UIDocumentInteractionControllerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITextViewDelegate.h"

@class ICTextView, NSMutableAttributedString, NSString, UIBarButtonItem, UIDocumentInteractionController, UILabel, UISegmentedControl;

__attribute__((visibility("hidden")))
@interface TGFastTextEditViewController : BaseViewController <UITextViewDelegate, UIDocumentInteractionControllerDelegate, UISearchBarDelegate>
{
    UISegmentedControl *prx;
    UILabel *label;
    NSString *aSearchText;
    unsigned long long openedFileFormat;
    unsigned long long openedEncoding;
    struct __sFILE *fileHandle;
    _Bool isReadonly;
    struct CGRect _keyboardRect;
    _Bool _keyboardVisible;
    _Bool _edited;
    int _currentPos;
    ICTextView *textEditor;
    UIBarButtonItem *btnDone;
    UIBarButtonItem *btnEdit;
    NSMutableAttributedString *_searchResultString;
    UIBarButtonItem *_btnCancel;
    UIBarButtonItem *_btnSave;
    UIDocumentInteractionController *_openIn;
}

@property(retain, nonatomic) UIDocumentInteractionController *openIn; // @synthesize openIn=_openIn;
@property(retain, nonatomic) UIBarButtonItem *btnSave; // @synthesize btnSave=_btnSave;
@property(retain, nonatomic) UIBarButtonItem *btnCancel; // @synthesize btnCancel=_btnCancel;
@property(retain, nonatomic) NSMutableAttributedString *searchResultString; // @synthesize searchResultString=_searchResultString;
@property(nonatomic) _Bool edited; // @synthesize edited=_edited;
@property(nonatomic) int currentPos; // @synthesize currentPos=_currentPos;
@property(retain, nonatomic) UIBarButtonItem *btnEdit; // @synthesize btnEdit;
@property(retain, nonatomic) UIBarButtonItem *btnDone; // @synthesize btnDone;
@property(retain, nonatomic) ICTextView *textEditor; // @synthesize textEditor;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (id)setupControllerWithURL:(id)arg1 singDelegate:(id)arg2;
- (void)cancelClicked:(id)arg1;
- (id)loadText;
- (void)saveClicked:(id)arg1;
- (void)hudWasCancelled;
- (void)doneClicked:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)nextOrprevious:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)editClicked:(id)arg1;
- (void)updateTextViewContentInset;
- (void)keyboardWillHide:(id)arg1;
- (void)scrollToVisible;
- (void)keyboardWillShow:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)searchText:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

