//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, OOSearchBar, UIScrollView, UITableView, UIView;

__attribute__((visibility("hidden")))
@interface TGFastQueryViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate>
{
    struct sqlite3_stmt *stmt;
    int currentRow;
    _Bool _canUseFastQuery;
    _Bool _isUpdateQuery;
    int numberOfRows;
    OOSearchBar *searchBar;
    NSString *queryString;
    UIView *_headerView;
    UIScrollView *_scrollView;
    UITableView *_tableView;
    NSMutableArray *_result;
    NSMutableArray *_columnWidths;
    NSMutableArray *_currentData;
    NSMutableArray *_headers;
    NSMutableArray *_types;
    NSString *_errorString;
}

@property(retain, nonatomic) NSString *errorString; // @synthesize errorString=_errorString;
@property(retain, nonatomic) NSMutableArray *types; // @synthesize types=_types;
@property(retain, nonatomic) NSMutableArray *headers; // @synthesize headers=_headers;
@property(retain, nonatomic) NSMutableArray *currentData; // @synthesize currentData=_currentData;
@property(retain, nonatomic) NSMutableArray *columnWidths; // @synthesize columnWidths=_columnWidths;
@property(retain, nonatomic) NSMutableArray *result; // @synthesize result=_result;
@property(nonatomic) _Bool isUpdateQuery; // @synthesize isUpdateQuery=_isUpdateQuery;
@property(nonatomic) _Bool canUseFastQuery; // @synthesize canUseFastQuery=_canUseFastQuery;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSString *queryString; // @synthesize queryString;
@property(nonatomic) int numberOfRows; // @synthesize numberOfRows;
@property(retain, nonatomic) OOSearchBar *searchBar; // @synthesize searchBar;
- (void).cxx_destruct;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)sqlite;
- (void)dealloc;
- (void)loadColumnsWidth;
- (id)dataForRow:(long long)arg1;
- (void)endQuery;
- (_Bool)beginQuery;
- (long long)numberOfRowsForQuery;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

