//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TGHelper : NSObject
{
}

+ (long long)numberOfItemPerLine;
+ (double)usedDiskSpaceInBytes;
+ (double)freeDiskSpaceInBytes;
+ (double)totalDiskSpaceInBytes;
+ (id)usedDiskSpace;
+ (id)freeDiskSpace;
+ (id)totalDiskSpace;
+ (id)timeToString:(id)arg1;
+ (id)hoursToString:(id)arg1;
+ (id)dateFromRFC822String:(id)arg1;
+ (id)dateFromRFC3339StringB:(id)arg1;
+ (id)dateFromRFC3339String:(id)arg1;
+ (id)dateFromSugarSyncDateTime:(id)arg1;
+ (id)timeToString:(id)arg1 format:(id)arg2;
+ (id)sizeToString:(long long)arg1;
+ (_Bool)isImageType:(id)arg1;
+ (_Bool)isAudioType:(id)arg1;
+ (_Bool)isVideoType:(id)arg1;
+ (id)fileSystemList;
+ (struct CGRect)fromRect:(struct CGRect)arg1 ofView:(id)arg2 toView:(id)arg3;

@end

