//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "HexEditorLayoutDataSource.h"
#import "UIAlertViewDelegate.h"
#import "UIBytesCollectionViewCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITextFieldDelegate.h"

@class DataScroller, NSIndexPath, NSMutableArray, NSString, NSTimer, OOSearchBar, UIBytesCollectionViewCell, UICollectionView, UIDocumentInteractionController, UILabel, UISegmentedControl, UITextField;

__attribute__((visibility("hidden")))
@interface TGHexEditorViewController : UIViewController <HexEditorLayoutDataSource, UICollectionViewDataSource, UICollectionViewDelegate, UITextFieldDelegate, UIBytesCollectionViewCellDelegate, UIDocumentInteractionControllerDelegate, UISearchBarDelegate, UIAlertViewDelegate>
{
    _Bool asked;
    int currentHalfByteIndex;
    _Bool warning;
    UICollectionView *_mainView;
    UIBytesCollectionViewCell *_selectedCell;
    UIBytesCollectionViewCell *_highlightedCell;
    NSIndexPath *_selectedIndexPath;
    long long _selectedIndex;
    UITextField *_hiddenTextField;
    long long _numberOfColumns;
    long long _numberOfLinesInGroup;
    DataScroller *_dataScroller;
    UIDocumentInteractionController *_actionController;
    UISegmentedControl *_prx;
    UISegmentedControl *_searchType;
    NSTimer *_searchTimer;
    OOSearchBar *_searchBar;
    UILabel *_resultLabel;
    NSMutableArray *_previous;
    long long _searchResultIndex;
    UILabel *_addressLabel;
}

@property(retain, nonatomic) UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(nonatomic) long long searchResultIndex; // @synthesize searchResultIndex=_searchResultIndex;
@property(retain, nonatomic) NSMutableArray *previous; // @synthesize previous=_previous;
@property(retain, nonatomic) UILabel *resultLabel; // @synthesize resultLabel=_resultLabel;
@property(retain, nonatomic) OOSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) NSTimer *searchTimer; // @synthesize searchTimer=_searchTimer;
@property(retain, nonatomic) UISegmentedControl *searchType; // @synthesize searchType=_searchType;
@property(retain, nonatomic) UISegmentedControl *prx; // @synthesize prx=_prx;
@property(retain, nonatomic) UIDocumentInteractionController *actionController; // @synthesize actionController=_actionController;
@property(retain, nonatomic) DataScroller *dataScroller; // @synthesize dataScroller=_dataScroller;
@property(nonatomic) long long numberOfLinesInGroup; // @synthesize numberOfLinesInGroup=_numberOfLinesInGroup;
@property(nonatomic) long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(retain, nonatomic) UITextField *hiddenTextField; // @synthesize hiddenTextField=_hiddenTextField;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(retain, nonatomic) UIBytesCollectionViewCell *highlightedCell; // @synthesize highlightedCell=_highlightedCell;
@property(retain, nonatomic) UIBytesCollectionViewCell *selectedCell; // @synthesize selectedCell=_selectedCell;
@property(retain, nonatomic) UICollectionView *mainView; // @synthesize mainView=_mainView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)bytesCollectionViewCell:(id)arg1 didSelectedByteIndex:(long long)arg2;
- (void)bytesCollectionViewCellDidSelectedAddress:(id)arg1;
- (unsigned long long)numberOfLinesPerCell;
- (unsigned long long)numberOfColumnsPerCell;
- (unsigned long long)numberOfBytesInHexEditor;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)doneClicked;
- (id)setupControllerWithURL:(id)arg1 singDelegate:(id)arg2;
- (void)actionButtonAction:(id)arg1;
- (void)nextOrprevious:(id)arg1;
- (void)searchNext;
- (void)searchPrevious;
- (id)hexToBytes:(id)arg1;
- (void)searchTypeChanged:(id)arg1;
- (void)startSearchWithText:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)delete1Byte;
- (void)insert1Byte;
- (void)addOrRemoveByte:(id)arg1;
- (void)gotoAddress:(id)arg1;
- (void)viewDidLoad;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

