//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UILabel;

@protocol TGInfoViewProtocol <NSObject>
- (void)setDiskUsageInfo:(NSString *)arg1;
- (void)setFileSystemInfo:(NSString *)arg1;
- (void)setNumberOfItemsInfo:(NSString *)arg1;
- (UILabel *)space;
- (UILabel *)items;
- (UILabel *)fileSystem;
@end

