//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, TGMenuManager, UIView;

@protocol TGMenuManagerDelegate <NSObject>
- (void)menuManager:(TGMenuManager *)arg1 hideAnimated:(_Bool)arg2;
- (void)menuManager:(TGMenuManager *)arg1 updateItemWithIdenfier:(NSString *)arg2 isEnabled:(_Bool)arg3;
- (void)menuManager:(TGMenuManager *)arg1 showWithItems:(NSArray *)arg2 animated:(_Bool)arg3;

@optional
- (void)menuManager:(TGMenuManager *)arg1 setItemSelectedWithIdentifier:(NSString *)arg2;
- (UIView *)menuManager:(TGMenuManager *)arg1 sourceViewForMenuItemWithIdentifier:(NSString *)arg2;
- (struct CGRect)menuManager:(TGMenuManager *)arg1 rectForMenuItemWithIdentifier:(NSString *)arg2;
@end

