//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGAbstractViewerViewController.h"

#import "QLPreviewControllerDataSource.h"
#import "QLPreviewControllerDelegate.h"

@class NSMutableArray, NSString, TGAudioProvider;

__attribute__((visibility("hidden")))
@interface TGMediaPlayerViewController : TGAbstractViewerViewController <QLPreviewControllerDataSource, QLPreviewControllerDelegate>
{
    NSMutableArray *_musicFiles;
    TGAudioProvider *_provider;
}

+ (_Bool)isVideo:(id)arg1;
+ (Class)realClassNameForFileItem:(id)arg1;
@property(retain, nonatomic) TGAudioProvider *provider; // @synthesize provider=_provider;
@property(retain, nonatomic) NSMutableArray *musicFiles; // @synthesize musicFiles=_musicFiles;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dismiss;
- (void)showInController:(id)arg1 animated:(_Bool)arg2;
- (id)previewController:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewController:(id)arg1;
- (id)initWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;
- (id)initForPreviewingWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;
- (Class)audioProviderClass;
- (Class)audioPlayerClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

