//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@class TGMenuManagerItem, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TGMenuBarButtonItem : UIBarButtonItem
{
    TGMenuManagerItem *_item;
    UIImageView *_imageView;
    UILabel *_label;
}

@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) TGMenuManagerItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)itemClicked:(id)arg1;
- (void)setEnabled:(_Bool)arg1;
- (id)initWithItem:(id)arg1;

@end

