//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGMusicLibraryViewController.h"

__attribute__((visibility("hidden")))
@interface TGMusicSearchLibraryViewController : TGMusicLibraryViewController
{
}

- (_Bool)_shouldFreeWhenReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (id)itemsForPanelMenuManager:(id)arg1;
- (id)itemsForBarMenuManager:(id)arg1;
- (id)currentPath;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateEditingToolbar;
- (void)setToolbarItems:(id)arg1;
- (void)setToolbarItems:(id)arg1 animated:(_Bool)arg2;
- (id)toolbarItems;
- (id)navigationItem;
- (void)browserViewRequireToLoadingThumbnailIfNeeds:(id)arg1 atIndexPath:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)doLoadingPage;
- (void)loadFilesWithSortMode:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

