//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGQLAudioViewController.h"

__attribute__((visibility("hidden")))
@interface TGNewAudioViewController : TGQLAudioViewController
{
}

- (void)audioProvider:(id)arg1 didFinishLoadingAudioAtIndex:(long long)arg2 withError:(id)arg3;
- (void)autoplayIfNeeds;
- (void)adjustPlayButtonState;
- (void)updateSeekUI;
- (void)next:(_Bool)arg1;
- (void)playbackTick:(id)arg1;
- (double)currentTrackLength;
- (void)playAndReset:(_Bool)arg1;
- (id)newProvider;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)canBecomeFirstResponder;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)remoteControlReceivedWithEvent:(id)arg1;

@end

