//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGNetworkOperationObject.h"

__attribute__((visibility("hidden")))
@interface TGNetworkMoveOperationObject : TGNetworkOperationObject
{
}

- (void)main;
- (void)moveToLocalOverwrite:(_Bool)arg1 existURL:(id)arg2 inSameParent:(_Bool)arg3;
- (void)moveToRemoteOverwrite:(_Bool)arg1 existURL:(id)arg2 inSameParent:(_Bool)arg3;

@end

