//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class FileItem, NSDate, NSError, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString, NSURL, TGOperationHelper;

__attribute__((visibility("hidden")))
@interface TGNetworkOperationObject : NSOperation
{
    NSObject<OS_dispatch_semaphore> *main_semaphore;
    NSString *_name_iOS7;
    _Bool _isDirectory;
    TGOperationHelper *_helper;
    NSObject<OS_dispatch_queue> *_queue;
    CDUnknownBlockType _operationCompleteCallback;
    CDUnknownBlockType _operationProgressCallback;
    CDUnknownBlockType _operationStartCallback;
    CDUnknownBlockType _existedActionCallback;
    NSURL *_fromUrl;
    NSURL *_destUrl;
    NSURL *_parentUrl;
    long long _fileSize;
    NSDate *_operationDate;
    NSDate *_completedDate;
    FileItem *_result;
    NSURL *_resultURL;
    NSError *_error;
    NSString *_title;
}

@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSURL *resultURL; // @synthesize resultURL=_resultURL;
@property(retain, nonatomic) FileItem *result; // @synthesize result=_result;
@property(retain, nonatomic) NSDate *completedDate; // @synthesize completedDate=_completedDate;
@property(retain, nonatomic) NSDate *operationDate; // @synthesize operationDate=_operationDate;
@property(nonatomic) _Bool isDirectory; // @synthesize isDirectory=_isDirectory;
@property(nonatomic) long long fileSize; // @synthesize fileSize=_fileSize;
@property(retain, nonatomic) NSURL *parentUrl; // @synthesize parentUrl=_parentUrl;
@property(retain, nonatomic) NSURL *destUrl; // @synthesize destUrl=_destUrl;
@property(retain, nonatomic) NSURL *fromUrl; // @synthesize fromUrl=_fromUrl;
@property(copy, nonatomic) CDUnknownBlockType existedActionCallback; // @synthesize existedActionCallback=_existedActionCallback;
@property(copy, nonatomic) CDUnknownBlockType operationStartCallback; // @synthesize operationStartCallback=_operationStartCallback;
@property(copy, nonatomic) CDUnknownBlockType operationProgressCallback; // @synthesize operationProgressCallback=_operationProgressCallback;
@property(copy, nonatomic) CDUnknownBlockType operationCompleteCallback; // @synthesize operationCompleteCallback=_operationCompleteCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) TGOperationHelper *helper; // @synthesize helper=_helper;
- (void).cxx_destruct;
- (id)name;
- (void)setName:(id)arg1;
- (void)deleteSourceVerifyNewURL:(id)arg1;
- (void)processError:(id)arg1;
- (void)processRemoteFileCompletion:(id)arg1;
- (void)processLocalFileCompletion:(id)arg1;
- (void)processDeleteExistedURL:(id)arg1;
- (void)progress:(float)arg1;
- (_Bool)accessOK;
- (void)complete:(unsigned long long)arg1;
- (_Bool)IsNameConflict:(id *)arg1 uRL:(id *)arg2 inSameParent:(_Bool *)arg3;
- (id)nonConfilctFileNameWithPreferName:(id)arg1 inFileList:(id)arg2;
- (_Bool)destIsLocalFile;
- (_Bool)destIsLocalApps;
- (_Bool)destIsLocalMusic;
- (_Bool)destIsLocal;
- (_Bool)sourceIsLocalPasteboard;
- (_Bool)sourceIsLocalMusic;
- (_Bool)sourceIsLocal;
- (void)cancel;
- (_Bool)isAsynchronous;
- (id)tempFileURL:(id)arg1;
- (void)dealloc;
- (id)init;

@end

