//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGAudioProvider.h"

#import "AVAudioPlayerDelegate.h"

@class AVPlayer, NSString;

__attribute__((visibility("hidden")))
@interface TGNewAudioProvider : TGAudioProvider <AVAudioPlayerDelegate>
{
    AVPlayer *_musicPlayer;
}

@property(retain, nonatomic) AVPlayer *musicPlayer; // @synthesize musicPlayer=_musicPlayer;
- (void).cxx_destruct;
- (void)updateState;
- (void)playerDidFinishPlaying:(id)arg1;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)playCurrentTrack:(_Bool)arg1 reset:(_Bool)arg2;
- (id)currentUrl;
- (_Bool)isPlaying;
- (double)currentTime;
- (double)duration;
- (double)currentPositionForTrack:(unsigned long long)arg1;
- (void)seekToPosition:(double)arg1;
- (void)setMediaItems:(id)arg1;
- (void)setCurrentIndex:(long long)arg1;
- (void)nextTrack;
- (id)currentAudioFile;
- (id)previewController:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewController:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

