//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FileItem, TGActionController, UIPopoverController;

__attribute__((visibility("hidden")))
@interface TGOpenWithController : NSObject
{
    FileItem *_fileItem;
    TGActionController *_actionController;
    CDUnknownBlockType _handler;
    UIPopoverController *_popoverController;
}

+ (id)sharedInstance;
@property(retain, nonatomic) UIPopoverController *popoverController; // @synthesize popoverController=_popoverController;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain, nonatomic) TGActionController *actionController; // @synthesize actionController=_actionController;
@property(retain, nonatomic) FileItem *fileItem; // @synthesize fileItem=_fileItem;
- (void).cxx_destruct;
- (void)hideAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissActionControllerWithCompletionBlock:(CDUnknownBlockType)arg1;
- (_Bool)isPresenting;
- (void)loadExternalAppsAsync;
- (id)topMostController;
- (void)showOpenWithActionControllerForFileItem:(id)arg1 fromSourceView:(id)arg2 sourceRect:(struct CGRect)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)_createActionController;
- (void)showOpenWithActionControllerForFileItem:(id)arg1 fromBarButtonItem:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;

@end

