//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "NewEmptyFileDelegate.h"
#import "NewFolderDelegate.h"
#import "RenameViewDelegate.h"
#import "TGMenuManagerDatasource.h"
#import "TGMenuManagerDelegate.h"
#import "TGViewerDelegate.h"
#import "TIGIBrowserViewDataSource.h"
#import "TIGIBrowserViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIContentContainer.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIDragInteractionDelegate.h"
#import "UIDropInteractionDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITraitEnvironment.h"
#import "UIViewControllerPreviewingDelegate.h"

@class NSArray, NSDate, NSIndexPath, NSMutableArray, NSString, NewEmptyFile, NewFolder, TGMenuController, TGMenuManager, TGNotificationView, TIGIBrowserView, UIBarButtonItem, UIDocumentInteractionController, UIPopoverController, UITableView, UITextField, UITraitCollection;

__attribute__((visibility("hidden")))
@interface TGPageViewController : UIViewController <NewFolderDelegate, NewEmptyFileDelegate, UITextFieldDelegate, UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate, TIGIBrowserViewDataSource, TIGIBrowserViewDelegate, UIAlertViewDelegate, UIDocumentInteractionControllerDelegate, MFMailComposeViewControllerDelegate, UIPopoverControllerDelegate, UIGestureRecognizerDelegate, RenameViewDelegate, TGMenuManagerDelegate, TGMenuManagerDatasource, UITraitEnvironment, UIContentContainer, UIViewControllerPreviewingDelegate, TGViewerDelegate, UIDropInteractionDelegate, UIDragInteractionDelegate>
{
    double aStartTime;
    int _filesCount;
    int _folderCount;
    int _hiddenItemsCount;
    struct _opaque_pthread_mutex_t _plock;
    _Bool _editable;
    _Bool _isTrash;
    _Bool _isTrashMetadata;
    _Bool _isLoadingThumbnail;
    _Bool _needsToCancelThumbnailLoading;
    _Bool _needToResumeThumbnailLoading;
    _Bool _needToResetThumbnailLoading;
    int _identifier;
    TGNotificationView *_notificationView;
    TIGIBrowserView *_browserView;
    NSString *_currentPath;
    id <TGSafeArray> _fileList;
    NSArray *_highLightItems;
    id <UIViewControllerPreviewing> _previewingContext;
    NSIndexPath *_editingIndexPath;
    NSMutableArray *_processingQueue;
    TGMenuController *_actionMenu;
    NSDate *_modifiedDate;
    UIPopoverController *_popup;
    UIDocumentInteractionController *_openIn;
    TGMenuManager *_menuManager;
    NewFolder *_aNewFolder;
    NewEmptyFile *_aNewEmptyFile;
    NSIndexPath *_previewIndexPath;
    TGPageViewController *_previewParentPage;
    UITextField *_pathTextField;
    UIBarButtonItem *_hiddenRightBarButton;
    UITableView *_autocompleteTextListView;
    NSArray *_autocompleteFolders;
    long long _lastLoadedThumbTopIndex;
    long long _lastLoadedThumbBottomIndex;
}

@property(nonatomic) long long lastLoadedThumbBottomIndex; // @synthesize lastLoadedThumbBottomIndex=_lastLoadedThumbBottomIndex;
@property(nonatomic) long long lastLoadedThumbTopIndex; // @synthesize lastLoadedThumbTopIndex=_lastLoadedThumbTopIndex;
@property(nonatomic) _Bool needToResetThumbnailLoading; // @synthesize needToResetThumbnailLoading=_needToResetThumbnailLoading;
@property(nonatomic) _Bool needToResumeThumbnailLoading; // @synthesize needToResumeThumbnailLoading=_needToResumeThumbnailLoading;
@property(nonatomic) _Bool needsToCancelThumbnailLoading; // @synthesize needsToCancelThumbnailLoading=_needsToCancelThumbnailLoading;
@property(retain, nonatomic) NSArray *autocompleteFolders; // @synthesize autocompleteFolders=_autocompleteFolders;
@property(retain, nonatomic) UITableView *autocompleteTextListView; // @synthesize autocompleteTextListView=_autocompleteTextListView;
@property(retain, nonatomic) UIBarButtonItem *hiddenRightBarButton; // @synthesize hiddenRightBarButton=_hiddenRightBarButton;
@property(retain, nonatomic) UITextField *pathTextField; // @synthesize pathTextField=_pathTextField;
@property(nonatomic) __weak TGPageViewController *previewParentPage; // @synthesize previewParentPage=_previewParentPage;
@property(retain, nonatomic) NSIndexPath *previewIndexPath; // @synthesize previewIndexPath=_previewIndexPath;
@property(retain, nonatomic) NewEmptyFile *aNewEmptyFile; // @synthesize aNewEmptyFile=_aNewEmptyFile;
@property(retain, nonatomic) NewFolder *aNewFolder; // @synthesize aNewFolder=_aNewFolder;
@property(retain, nonatomic) TGMenuManager *menuManager; // @synthesize menuManager=_menuManager;
@property(retain, nonatomic) UIDocumentInteractionController *openIn; // @synthesize openIn=_openIn;
@property(nonatomic) _Bool isLoadingThumbnail; // @synthesize isLoadingThumbnail=_isLoadingThumbnail;
@property(retain, nonatomic) UIPopoverController *popup; // @synthesize popup=_popup;
@property(retain, nonatomic) NSDate *modifiedDate; // @synthesize modifiedDate=_modifiedDate;
@property(retain, nonatomic) TGMenuController *actionMenu; // @synthesize actionMenu=_actionMenu;
@property(retain, nonatomic) NSMutableArray *processingQueue; // @synthesize processingQueue=_processingQueue;
@property(retain, nonatomic) NSIndexPath *editingIndexPath; // @synthesize editingIndexPath=_editingIndexPath;
@property(retain, nonatomic) id <UIViewControllerPreviewing> previewingContext; // @synthesize previewingContext=_previewingContext;
@property(nonatomic) _Bool isTrashMetadata; // @synthesize isTrashMetadata=_isTrashMetadata;
@property(nonatomic) _Bool isTrash; // @synthesize isTrash=_isTrash;
@property(nonatomic) _Bool editable; // @synthesize editable=_editable;
@property(retain, nonatomic) NSArray *highLightItems; // @synthesize highLightItems=_highLightItems;
@property(retain, nonatomic) id <TGSafeArray> fileList; // @synthesize fileList=_fileList;
@property(retain, nonatomic) NSString *currentPath; // @synthesize currentPath=_currentPath;
@property(retain, nonatomic) TIGIBrowserView *browserView; // @synthesize browserView=_browserView;
@property(retain, nonatomic) TGNotificationView *notificationView; // @synthesize notificationView=_notificationView;
@property(nonatomic) int identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)reloadAutocompletionInfoWithPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)endEditingPath;
- (void)endEditingPathNoAnimation;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)menuManager:(id)arg1 sourceViewForMenuItemWithIdentifier:(id)arg2;
- (struct CGRect)menuManager:(id)arg1 rectForMenuItemWithIdentifier:(id)arg2;
- (id)itemsForPanelMenuManager:(id)arg1;
- (id)itemsForBarMenuManager:(id)arg1;
- (void)menuManager:(id)arg1 updateItemWithIdenfier:(id)arg2 isEnabled:(_Bool)arg3;
- (void)menuManager:(id)arg1 hideAnimated:(_Bool)arg2;
- (void)menuManager:(id)arg1 showWithItems:(id)arg2 animated:(_Bool)arg3;
- (void)dealloc;
- (void)updateEditingToolbar;
- (void)browserViewDidScroll:(id)arg1;
- (void)browserViewDidSelectAllItems:(id)arg1;
- (void)browserViewDidDeselectAllItems:(id)arg1;
- (void)browserView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)openItem:(id)arg1 withViewerName:(id)arg2;
- (void)showOpenWithListForItem:(id)arg1 fromRect:(struct CGRect)arg2 inView:(id)arg3;
- (void)updateCounter;
- (void)browserView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)browserView:(id)arg1 willSortWithSortMode:(int)arg2;
- (id)browserView:(id)arg1 itemForSectionAtIndexPath:(id)arg2;
- (long long)browserView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInBrowserView:(id)arg1;
- (void)browserView:(id)arg1 deleteButtonTappedForItemAtIndexPath:(id)arg2;
- (void)browserView:(id)arg1 accessoryButtonTappedForItemAtIndexPath:(id)arg2;
- (void)_loadThumbnails;
- (void)_unlock;
- (void)_lock;
- (void)loadFilesWithSortMode:(int)arg1;
- (void)updateDirectoryInfoWithFilesCount:(int)arg1 foldersCount:(int)arg2 hiddenCount:(int)arg3;
- (void)updateDirectoryInfo;
- (void)updateDirectoryInfoForDeletedItem:(id)arg1;
- (void)updateDirectoryInfoForInsertedItem:(id)arg1;
- (void)browserViewDidChangeViewMode:(id)arg1;
- (void)browserViewRequireToLoadingThumbnailIfNeeds:(id)arg1 atIndexPath:(id)arg2;
- (void)browserView:(id)arg1 directoryInfoViewTappedAtLabel:(id)arg2;
- (void)doLoadingPage;
- (void)doReloadingPageIfNeeds;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)deleteSelectedFiles;
- (id)moveSelectedFilesToTrash;
- (void)createNewSymbolicLink:(struct CGRect)arg1 sourceView:(id)arg2;
- (void)actionTouched;
- (void)moveTouched;
- (void)copyFilesAndDirectoryFromPasteboard;
- (void)copyFilesAndDirectories:(id)arg1 names:(id)arg2;
- (void)moveFilesAndDirectories:(id)arg1 names:(id)arg2;
- (void)moveFilesAndDirectoryFromPasteboard;
- (void)writeToRecents:(id)arg1;
- (void)insertFilesAndDirectoryFromPasteboard;
- (void)doOpenPropertiesSelectedIndexPath:(id)arg1 fromSrcRect:(struct CGRect)arg2 srcView:(id)arg3;
- (void)doCopySelectedIndexPaths:(id)arg1;
- (void)copyTouched;
- (id)nameForRenameView:(id)arg1;
- (id)iconForRenameView:(id)arg1;
- (void)renameView:(id)arg1 completeWithName:(id)arg2;
- (_Bool)renameView:(id)arg1 checkIfNameExisted:(id)arg2;
- (void)renameTouched;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (id)setupControllerWithURL:(id)arg1 singDelegate:(id)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)sendSelectedItemsToMail;
- (id)zipSelectedFiles;
- (id)createDEBFromSelectedFolder;
- (void)doOpenInWithFileItem:(id)arg1;
- (void)doOpenWithWithFileItem:(id)arg1;
- (void)performActionForMenuWithIdentifier:(id)arg1 sourceView:(id)arg2 sourceRect:(struct CGRect)arg3;
- (void)viewer:(id)arg1 didSelectAction:(id)arg2;
- (void)putSelectedItemsBack;
- (id)doEraseSelectedIndexPaths:(id)arg1;
- (id)doTrashSelectedIndexPaths:(id)arg1;
- (void)deleteSelectedItems;
- (void)showEditingToolBar:(_Bool)arg1 animated:(_Bool)arg2;
- (void)reloadMenuItems;
- (void)didNewFolderAction:(id)arg1 success:(_Bool)arg2 type:(_Bool)arg3 files:(id)arg4;
- (_Bool)newFolder:(id)arg1 checkIfDirNameExisted:(id)arg2;
- (void)updateModifiedDate;
- (void)newFolder:(id)arg1 completeWithName:(id)arg2;
- (void)NewEmptyFile:(id)arg1 completeWithName:(id)arg2;
- (_Bool)NewEmptyFile:(id)arg1 checkIfNameExisted:(id)arg2;
- (void)createNewEmptyFile:(id)arg1;
- (void)createNewFolder:(id)arg1;
- (void)createSymbolicLinkWithDestinations:(id)arg1 relative:(_Bool)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setDefaultMenuStates;
- (void)endEditingIfNeedsAnimated:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (_Bool)_shouldFreeWhenReceiveMemoryWarning;
- (_Bool)isInCurrentFilzaWindow;
- (_Bool)isTopPageOfWindow;
- (void)stopScrollingAnimation;
- (void)resumeScrollingAnimationIfNeed;
- (void)newItemArrive:(id)arg1;
- (void)highLightItemsWithNames:(id)arg1;
- (void)highLightItemWithName:(id)arg1;
- (void)reloadItem:(id)arg1;
- (void)reloadItemPath:(id)arg1;
- (void)updateSortButtons;
- (void)reloadFilesAndFolders:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)titleDidTapped;
- (void)setInitSortMode:(int)arg1;
- (void)browserViewDidBeginLoading:(id)arg1;
- (void)longPressed:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)_showBottomEditingToolbar:(_Bool)arg1;
- (void)_setToolbarHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (Class)fileAttributesClass;
- (Class)browserViewClass;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingControllerForIndexPath:(id)arg1;
- (id)previewActionItems;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (id)dragInteraction:(id)arg1 previewForLiftingItem:(id)arg2 session:(id)arg3;
- (_Bool)dragInteraction:(id)arg1 prefersFullSizePreviewsForSession:(id)arg2;
- (id)dragInteraction:(id)arg1 itemsForBeginningSession:(id)arg2;
- (id)dropInteraction:(id)arg1 sessionDidUpdate:(id)arg2;
- (void)dropInteraction:(id)arg1 performDrop:(id)arg2;
- (_Bool)dropInteraction:(id)arg1 canHandleSession:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct CGSize preferredContentSize;
@property(readonly) Class superclass;
@property(readonly, nonatomic) UITraitCollection *traitCollection;

@end

