//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "ItemEditTableViewControllerDelegate.h"
#import "TreeTableDataSource.h"
#import "UIAlertViewDelegate.h"

@class NSMutableDictionary, NSString, TreeTable;

__attribute__((visibility("hidden")))
@interface TGPlistViewController : UITableViewController <ItemEditTableViewControllerDelegate, UIAlertViewDelegate, TreeTableDataSource>
{
    TreeTable *_treeTable;
    NSMutableDictionary *_root;
    unsigned long long _format;
    NSMutableDictionary *_expandedItems;
}

@property(readonly, nonatomic) NSMutableDictionary *expandedItems; // @synthesize expandedItems=_expandedItems;
@property(nonatomic) unsigned long long format; // @synthesize format=_format;
@property(retain, nonatomic) NSMutableDictionary *root; // @synthesize root=_root;
@property(retain, nonatomic) TreeTable *treeTable; // @synthesize treeTable=_treeTable;
- (void).cxx_destruct;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)enabledSaving:(id)arg1;
- (void)itemEditTableViewController:(id)arg1 didReplaceWithObject:(id)arg2 andKey:(id)arg3 atIndexPath:(id)arg4;
- (void)itemEditTableViewController:(id)arg1 doDeleteObject:(id)arg2 andKey:(id)arg3 atIndexPath:(id)arg4;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (unsigned long long)tableView:(id)arg1 numberOfSubCellsForCellAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 isCellExpanded:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)superItemForIndexPath:(id)arg1;
- (id)itemForIndexPath:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)addClicked;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)doneClicked;
- (void)saveClicked;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

