//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGThemeTableViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSArray, NSString, Reachability;

__attribute__((visibility("hidden")))
@interface TGPreferencesTableViewController : TGThemeTableViewController <UIAlertViewDelegate, MFMailComposeViewControllerDelegate>
{
    _Bool showAirBrowserNotification;
    _Bool Activated;
    NSArray *_items;
    Reachability *_reachWiFi;
}

@property(retain, nonatomic) Reachability *reachWiFi; // @synthesize reachWiFi=_reachWiFi;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)fontSelected:(id)arg1;
- (void)toptoolbar:(id)arg1;
- (void)sidebarChange:(id)arg1;
- (void)sortButtonsChange:(id)arg1;
- (void)setHiddenFilesAndFolders:(id)arg1;
- (void)selectScrollingSpeed:(id)arg1;
- (void)setFolderOnTop:(id)arg1;
- (void)selectHomeDirectory:(id)arg1;
- (void)swithAirBrowserCheckbox;
- (void)selectAirNotification:(id)arg1;
- (void)openAuthenticationBox:(id)arg1;
- (void)selectRunAsService:(id)arg1;
- (void)openWhatNewDialog;
- (void)selectTheme;
- (void)openBonjourBox:(id)arg1;
- (void)selectTempDirectory:(id)arg1;
- (void)selectDownloadDirectory:(id)arg1;
- (void)selectAllowCloudViewers:(id)arg1;
- (void)selectShowApplicationName:(id)arg1;
- (void)selectEnableRecents:(id)arg1;
- (void)commonChange:(id)arg1;
- (void)openBehaviorChange:(id)arg1;
- (void)openLicenseDialog;
- (void)openAboutDialog;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)openUserManual;
- (void)openSupportDialog;
- (void)selectAirPort:(id)arg1;
- (void)openFileAssociations;
- (void)openAccounts;
- (void)openViewers;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)cancel;
- (void)dealloc;
- (void)wifiStatusChanged:(id)arg1;
- (void)presChanged:(id)arg1;
- (void)openSettingsBackupDialog;
- (void)showAdvanced:(id)arg1;
- (void)openExternalViewers:(id)arg1;
- (void)selectTrash:(id)arg1;
- (void)viewDidLoad;
- (void)updateLicense;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

