//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class GCDWebDAVServer, NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimer, TGDatabaseInterface, UIAlertView, UIViewController;

__attribute__((visibility("hidden")))
@interface TGPreferences : NSObject <UIAlertViewDelegate>
{
    _Bool _displaySize;
    _Bool _displayPermissions;
    _Bool _stashParser;
    _Bool _displayFolderDetails;
    _Bool _applicationName;
    _Bool _hiddenFiles;
    int _aZeroKey;
    int _idleTimerCount;
    int _iOS8;
    int _retinaHD;
    _Bool _reduceMotion;
    NSMutableDictionary *apps;
    _Bool _isPlayingMusic;
    int _serialNumberReloadTimes;
    NSDictionary *_preferencesModel;
    GCDWebDAVServer *httpServer;
    NSDictionary *_viewers;
    NSTimer *_blindTimer;
    NSArray *_cloudServices;
    NSMutableArray *_accounts;
    NSMutableDictionary *_customOpenWith;
    UIViewController *_sharedMainViewController;
    UIViewController *_sharedLeftPanelController;
    NSDate *_lastFetchTime;
    TGDatabaseInterface *_databaseInterface;
    UIAlertView *_alert;
    NSMutableDictionary *_extensionDictionary;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *extensionDictionary; // @synthesize extensionDictionary=_extensionDictionary;
@property(retain, nonatomic) UIAlertView *alert; // @synthesize alert=_alert;
@property(retain, nonatomic) TGDatabaseInterface *databaseInterface; // @synthesize databaseInterface=_databaseInterface;
@property(nonatomic) int serialNumberReloadTimes; // @synthesize serialNumberReloadTimes=_serialNumberReloadTimes;
@property(retain, nonatomic) NSDate *lastFetchTime; // @synthesize lastFetchTime=_lastFetchTime;
@property(nonatomic) __weak UIViewController *sharedLeftPanelController; // @synthesize sharedLeftPanelController=_sharedLeftPanelController;
@property(nonatomic) __weak UIViewController *sharedMainViewController; // @synthesize sharedMainViewController=_sharedMainViewController;
@property(retain, nonatomic) NSMutableDictionary *customOpenWith; // @synthesize customOpenWith=_customOpenWith;
@property(nonatomic) _Bool isPlayingMusic; // @synthesize isPlayingMusic=_isPlayingMusic;
@property(retain, nonatomic) NSMutableArray *accounts; // @synthesize accounts=_accounts;
@property(retain, nonatomic) NSArray *cloudServices; // @synthesize cloudServices=_cloudServices;
@property(retain, nonatomic) NSTimer *blindTimer; // @synthesize blindTimer=_blindTimer;
@property(retain, nonatomic) NSDictionary *viewers; // @synthesize viewers=_viewers;
@property(retain, nonatomic) GCDWebDAVServer *httpServer; // @synthesize httpServer;
- (void).cxx_destruct;
- (id)trashDir;
- (id)selfCheckingViewerIdentifierForFile:(id)arg1;
- (_Bool)schemeIsLocal:(id)arg1;
- (void)updateReduceMotionSetting;
- (_Bool)isMotionReduced;
- (id)mimeTypeOfExtension:(id)arg1;
- (id)UTTypeOfExtension:(id)arg1;
- (id)urlFromString:(id)arg1;
- (id)nonConfilctFileNameWithPreferName:(id)arg1 inFileList:(id)arg2;
- (id)nonConfilctFilePathWithPreferName:(id)arg1 inDir:(id)arg2;
- (id)viewerIdentifierForFileExtension:(id)arg1;
- (id)readableUrl:(id)arg1;
- (id)viewerIdentifierForFileExtensionIncludingQuickLook:(id)arg1;
- (id)viewerSpecForFileExtension:(id)arg1;
- (_Bool)isMediaFile:(id)arg1;
- (_Bool)isPDF:(id)arg1;
- (_Bool)isImage:(id)arg1;
- (id)extensionsForViewerId:(id)arg1;
- (id)viewerForFile:(id)arg1 inFileList:(id)arg2 viewerId:(id)arg3 delegate:(id)arg4;
- (id)viewerForFile:(id)arg1 inFileList:(id)arg2 delegate:(id)arg3;
- (id)previewerForFile:(id)arg1 inFileList:(id)arg2 delegate:(id)arg3;
- (id)__previewerForRemoteFile:(id)arg1 inFileList:(id)arg2 delegate:(id)arg3;
- (id)defaultPreviewerForFile:(id)arg1;
- (_Bool)isBinaryFile:(id)arg1;
- (_Bool)isFoldersOnTop;
@property(readonly, nonatomic) NSDictionary *preferencesModel; // @synthesize preferencesModel=_preferencesModel;
- (int)getViewMode;
- (int)getDefaultSortMode;
- (void)updateCachedPreferences:(id)arg1;
- (void)setObject:(id)arg1 forPreferenceKey:(id)arg2 notification:(_Bool)arg3;
- (void)removeObjectForPreferenceKey:(id)arg1 notification:(_Bool)arg2;
- (id)objectForPreferenceKey:(id)arg1;
- (void)setViewMode:(int)arg1;
- (void)setDefaultSortMode:(int)arg1;
- (id)defaultPath;
- (id)applicationNameFromPath:(id)arg1;
- (id)applicationNameFromID:(id)arg1;
- (id)appListCachePath;
- (void)updateAppsList;
- (void)reloadApplicationName;
- (_Bool)isiOS8;
- (void)enableIdleTimer;
- (void)disableIdleTimer;
- (_Bool)displayFolderDetails;
- (_Bool)stashParser;
- (_Bool)displayPermission;
- (_Bool)displaySize;
- (_Bool)applicationName;
- (_Bool)showHiddenFiles;
- (id)libDirectoryPath;
- (id)hostname;
- (id)getIPAddress;
- (void)sendNotification:(id)arg1;
- (void)writeLog:(id)arg1 error:(int)arg2;
- (id)readLog;
- (_Bool)isServerStarted;
- (id)connectionUrlWithHostname;
- (id)connectionUrl;
- (id)uploaderPath;
- (void)wifiChanged:(id)arg1;
- (void)createHttpServer;
- (void)stopAirBrowser;
- (void)startAirBrowser;
- (void)setViewerId:(id)arg1 forExt:(id)arg2;
- (id)UDID;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dismissNagScreen;
- (_Bool)deviceSupportsAirDrop;
- (void)addTrashItem:(id)arg1 metadata:(id)arg2;
- (_Bool)isLocalUrl:(id)arg1;
- (_Bool)isRetinaHD;
- (_Bool)isViewControllerSupports3DTouch:(id)arg1;
- (void)commitCheckpoint;
- (id)uniqueDeviceId;
- (id)MM86912244441;
- (id)allCloudServices;
- (void)updateAllAccounts;
- (id)downloadDirectory;
- (id)tempDirectory;
- (_Bool)allowViewers;
- (id)allAccounts;
- (void)removeDisplayNameForAccount:(id)arg1;
- (id)displayNameForAccount:(id)arg1;
- (void)setDisplayName:(id)arg1 forAccount:(id)arg2;
- (id)viewerIdForFileID:(id)arg1;
- (void)setViewerId:(id)arg1 forFileID:(id)arg2;
- (void)updateFavorites;
- (_Bool)isTopToolbarFixed;
- (void)updateRecentsEnabled;
- (id)previewers;
- (void)saveCloudCreditials:(id)arg1;
- (id)cloudCreditials;
- (_Bool)isCachedPreference:(id)arg1;
- (_Bool)isStashDir:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

