//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLPreviewController.h"

@class QLPreviewItemAVState;

__attribute__((visibility("hidden")))
@interface TGQuickLookViewController : QLPreviewController
{
    QLPreviewItemAVState *_state;
}

@property(retain, nonatomic) QLPreviewItemAVState *state; // @synthesize state=_state;
- (void)dealloc;
- (void)previewContentController:(id)arg1 setAVState:(id)arg2 forPreviewItem:(id)arg3;
- (id)volumeView;
- (id)avStateForPreviewItems;
- (id)playPauseButton;
- (id)reserved;
- (void)_configurePreviewContentController;
- (void)didReceiveMemoryWarning;
- (void)doneClicked;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

