//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@class NSObject<OS_xpc_object>;

__attribute__((visibility("hidden")))
@interface TGRootFileManager : NSFileManager
{
    NSObject<OS_xpc_object> *connection;
    _Bool invalidConnection;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (id)_execRootShellWithOutput:(id)arg1;
- (id)dpkgInfo:(id)arg1;
- (id)fetchActivationSignature;
- (int)forkRootShell:(int *)arg1;
- (void)kill:(int)arg1;
- (void)_execRootShell:(id)arg1 chdir:(id)arg2;
- (struct __sFILE *)openFile:(id)arg1 withFlags:(id)arg2;
- (int)access:(id)arg1 mode:(int)arg2;
- (int)stat:(id)arg1 stat:(struct stat *)arg2;
- (int)dsync:(id)arg1;
- (int)mkdir:(id)arg1 mode:(unsigned short)arg2;
- (long long)readlink:(id)arg1 destination:(char *)arg2 maxSize:(unsigned long long)arg3;
- (int)rmdir:(id)arg1;
- (int)unlink:(id)arg1;
- (int)setxattr:(id)arg1 name:(id)arg2 value:(id)arg3 position:(unsigned int)arg4 option:(int)arg5;
- (int)fileDescriptorForFileAtPath:(id)arg1 withFlags:(int)arg2 andModes:(unsigned short)arg3;
- (int)getPty:(int *)arg1;
- (id)readDataWithFilePath:(id)arg1 option:(unsigned long long)arg2 error:(id *)arg3;
- (id)attributesOfFileSystemForPath:(id)arg1 error:(id *)arg2;
- (_Bool)removeItemAtURL:(id)arg1 error:(id *)arg2;
- (_Bool)removeItemAtPath:(id)arg1 error:(id *)arg2;
- (_Bool)copyItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
- (_Bool)copyItemAtPath:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (_Bool)moveItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
- (_Bool)moveItemAtPath:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (_Bool)createFileAtPath:(id)arg1 contents:(id)arg2 attributes:(id)arg3;
- (_Bool)createSymbolicLinkAtURL:(id)arg1 withDestinationURL:(id)arg2 error:(id *)arg3;
- (_Bool)createSymbolicLinkAtPath:(id)arg1 withDestinationPath:(id)arg2 error:(id *)arg3;
- (_Bool)createHardLinkAtPath:(id)arg1 withDestinationPath:(id)arg2 error:(id *)arg3;
- (_Bool)createDirectoryAtURL:(id)arg1 withIntermediateDirectories:(_Bool)arg2 attributes:(id)arg3 error:(id *)arg4;
- (_Bool)createDirectoryAtPath:(id)arg1 withIntermediateDirectories:(_Bool)arg2 attributes:(id)arg3 error:(id *)arg4;
- (_Bool)setTagValue:(long long)arg1 forItemAtPath:(id)arg2;
- (long long)tagValueForItemAtPath:(id)arg1;
- (_Bool)fileExistsAtPath:(id)arg1;
- (_Bool)fileExistsAtPath:(id)arg1 isDirectory:(_Bool *)arg2;
- (id)contentsOfDirectoryWithSubItemAttributesAtPath:(id)arg1 error:(id *)arg2;
- (_Bool)setAttributes:(id)arg1 ofItemAtPath:(id)arg2 error:(id *)arg3;
- (id)attributesOfItemAtPath:(id)arg1 error:(id *)arg2;
- (id)contentsOfDirectoryAtPath:(id)arg1 error:(id *)arg2;
- (void)createXPCConnection;
- (void)tryLoadFilzaHelper;
- (void)reload;
- (id)init;
- (_Bool)fileExistsAtURLEx:(id)arg1 isDirectory:(_Bool *)arg2;
- (_Bool)fileExistsAtURLEx:(id)arg1;
- (_Bool)fileExistsAtPathEx:(id)arg1 isDirectory:(_Bool *)arg2;
- (_Bool)fileExistsAtPathEx:(id)arg1;
- (_Bool)moveItemAtURLEx:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
- (_Bool)moveItemAtPathEx:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (_Bool)copyItemAtURLEx:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
- (_Bool)copyItemAtPathEx:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (_Bool)removeItemAtURLEx:(id)arg1 error:(id *)arg2;
- (_Bool)removeItemAtPathEx:(id)arg1 error:(id *)arg2;
- (_Bool)setAttributesEx:(id)arg1 ofItemAtPath:(id)arg2 error:(id *)arg3;
- (id)attributesOfItemAtPathEx:(id)arg1 error:(id *)arg2;
- (_Bool)setExtendedAttributes:(id)arg1 ofItemAtPath:(id)arg2 error:(id *)arg3;
- (id)extendedAttributesOfItemAtPath:(id)arg1 error:(id *)arg2;

@end

