//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSIndexSet;

@protocol TGSafeArray <NSObject>
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)firstObject;
- (long long)insertObject:(id)arg1 atSortMode:(int)arg2 preferredIndex:(long long)arg3;
- (void)sortWithMode:(int)arg1;
- (void)insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)removeObjectsInArray:(NSArray *)arg1;
- (long long)indexOfObject:(id)arg1;
- (void)removeAllObjects;
- (void)addObjectsFromArray:(NSArray *)arg1;
- (void)removeObjectsAtIndexes:(NSIndexSet *)arg1;
- (void)removeObjectAtIndex:(unsigned long long)arg1;
- (void)addObject:(id)arg1;
- (unsigned long long)count;
- (void)removeObject:(id)arg1;
- (void)replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (id)objectAtIndex:(unsigned long long)arg1;
- (_Bool)containsObject:(id)arg1;
@end

