//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AMPopTip;

__attribute__((visibility("hidden")))
@interface TGSession : NSObject
{
    _Bool _allowCopyButton;
    _Bool _allowMoveButton;
    _Bool _allowRenameButton;
    _Bool _allowDeleteButton;
    _Bool _allowActionButton;
    _Bool _allowOpenInButton;
    _Bool _allowOpenWithButton;
    _Bool _allowSendEmailButton;
    _Bool _allowZipButton;
    _Bool _allowNewFileButton;
    _Bool _allowNewFolderButton;
    _Bool _allowNewSymbolicLinkButton;
    _Bool _allowPropertiesButton;
    _Bool _allowCreateDEBButton;
    _Bool _allowPutbackButton;
    int _identifier;
    int _initSortMode;
    AMPopTip *_popTipView;
}

+ (id)currentSession;
+ (id)sessionForPageWithIdentifier:(int)arg1;
+ (int)newId;
@property(retain, nonatomic) AMPopTip *popTipView; // @synthesize popTipView=_popTipView;
@property(nonatomic) int initSortMode; // @synthesize initSortMode=_initSortMode;
@property(nonatomic) _Bool allowPutbackButton; // @synthesize allowPutbackButton=_allowPutbackButton;
@property(nonatomic) _Bool allowCreateDEBButton; // @synthesize allowCreateDEBButton=_allowCreateDEBButton;
@property(nonatomic) _Bool allowPropertiesButton; // @synthesize allowPropertiesButton=_allowPropertiesButton;
@property(nonatomic) _Bool allowNewSymbolicLinkButton; // @synthesize allowNewSymbolicLinkButton=_allowNewSymbolicLinkButton;
@property(nonatomic) _Bool allowNewFolderButton; // @synthesize allowNewFolderButton=_allowNewFolderButton;
@property(nonatomic) _Bool allowNewFileButton; // @synthesize allowNewFileButton=_allowNewFileButton;
@property(nonatomic) _Bool allowZipButton; // @synthesize allowZipButton=_allowZipButton;
@property(nonatomic) _Bool allowSendEmailButton; // @synthesize allowSendEmailButton=_allowSendEmailButton;
@property(nonatomic) _Bool allowOpenWithButton; // @synthesize allowOpenWithButton=_allowOpenWithButton;
@property(nonatomic) _Bool allowOpenInButton; // @synthesize allowOpenInButton=_allowOpenInButton;
@property(nonatomic) _Bool allowActionButton; // @synthesize allowActionButton=_allowActionButton;
@property(nonatomic) _Bool allowDeleteButton; // @synthesize allowDeleteButton=_allowDeleteButton;
@property(nonatomic) _Bool allowRenameButton; // @synthesize allowRenameButton=_allowRenameButton;
@property(nonatomic) _Bool allowMoveButton; // @synthesize allowMoveButton=_allowMoveButton;
@property(nonatomic) _Bool allowCopyButton; // @synthesize allowCopyButton=_allowCopyButton;
@property(nonatomic) int identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)close;
- (id)topPageWithSsearch;
- (id)topPage;
- (id)topMostController;
- (void)showErrorMessage:(id)arg1 withTitle:(id)arg2;
- (_Bool)isSearchSession;

@end

