//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TGSQLiteAccess : NSObject
{
    struct sqlite3 *database;
    _Bool _isOpened;
    NSString *errorString;
    NSString *filePath;
}

@property(nonatomic) _Bool isOpened; // @synthesize isOpened=_isOpened;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath;
@property(retain, nonatomic) NSString *errorString; // @synthesize errorString;
- (void).cxx_destruct;
- (void)closeDatabase;
- (_Bool)openDatabaseWith;
- (id)queryWithText:(id)arg1;
- (id)triggers;
- (id)indexes;
- (id)views;
- (id)tables;
- (id)initWith:(id)arg1;
- (struct sqlite3 *)sqlite;
- (id)init;

@end

