//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGAbstractViewerViewController.h"

@class TGSQLiteAccess;

__attribute__((visibility("hidden")))
@interface TGSQLiteNavigationViewController : TGAbstractViewerViewController
{
    TGSQLiteAccess *_sqlite;
}

@property(retain, nonatomic) TGSQLiteAccess *sqlite; // @synthesize sqlite=_sqlite;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;
- (id)initForPreviewingWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;

@end

