//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGAbstractViewerViewController.h"

__attribute__((visibility("hidden")))
@interface TGTextEditorController : TGAbstractViewerViewController
{
}

- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initForPreviewingWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;
- (id)initWithFileItem:(id)arg1 moreInfo:(id)arg2 delegate:(id)arg3;

@end

