//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "AVPlayerViewControllerDelegate.h"

@class MPMoviePlayerViewController, NSString;

__attribute__((visibility("hidden")))
@interface TGVideoPlayerViewController : BaseViewController <AVPlayerViewControllerDelegate>
{
    _Bool willClose;
    _Bool _isPreviousStatusBarHidden;
    MPMoviePlayerViewController *_playeriOS7;
}

@property(retain, nonatomic) MPMoviePlayerViewController *playeriOS7; // @synthesize playeriOS7=_playeriOS7;
@property(nonatomic) _Bool isPreviousStatusBarHidden; // @synthesize isPreviousStatusBarHidden=_isPreviousStatusBarHidden;
- (void).cxx_destruct;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)donePress;
- (void)doneButtonClicked:(id)arg1;
- (void)loadStateDidChange:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)setupStatusbarHidden;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

