//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TGViewerProtocolImplementation : NSObject <UIAlertViewDelegate>
{
    CDUnknownBlockType _completionHandler;
}

+ (void)loadViewerWithVc:(id)arg1 customInitiate:(CDUnknownBlockType)arg2;
+ (void)loadViewerWithVc:(id)arg1 classText:(Class)arg2 classBinary:(Class)arg3 binaryCheck:(_Bool)arg4;
+ (void)loadViewerWithVc:(id)arg1 class:(Class)arg2;
+ (void)cancelRemoteFile:(id)arg1 object:(id)arg2;
+ (id)loadRemoteFile:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (void)__removeProgressView:(id)arg1 fromVc:(id)arg2;
+ (void)__addProgressView:(id)arg1 toVc:(id)arg2;
+ (void)setup:(id)arg1 previewing:(_Bool)arg2;
+ (void)showErrorScreen:(id)arg1 withMessage:(id)arg2 showHexdump:(_Bool)arg3;
+ (id)viewerName:(id)arg1;
+ (void)writeRecents:(id)arg1;
+ (void)commit:(id)arg1;
+ (void)dismiss:(id)arg1;
+ (_Bool)canOpenFile:(id)arg1;
+ (void)show:(id)arg1 inController:(id)arg2 animated:(_Bool)arg3;
+ (void)showFormSheet:(id)arg1 inController:(id)arg2 animated:(_Bool)arg3;
+ (void)setup:(id)arg1 withFileItem:(id)arg2 moreInfo:(id)arg3;
+ (void)controller:(id)arg1 showHUD:(_Bool)arg2;
+ (id)asksToOpenDelegateWithCompletion:(CDUnknownBlockType)arg1;
+ (id)shared;
+ (id)previewActionsForFileItem:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

