//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TNCheckBoxDelegate.h"

@class NSArray, NSString, UIColor, UIFont;

__attribute__((visibility("hidden")))
@interface TNCheckBoxGroup : UIView <TNCheckBoxDelegate>
{
    NSString *_identifier;
    long long _marginBetweenItems;
    UIFont *_labelFont;
    UIColor *_labelColor;
    NSArray *_radioButtons;
    NSArray *_checkBoxData;
    unsigned long long _layout;
    long long _widthOfComponent;
    long long _heightOfComponent;
    struct CGPoint _position;
}

@property(nonatomic) long long heightOfComponent; // @synthesize heightOfComponent=_heightOfComponent;
@property(nonatomic) long long widthOfComponent; // @synthesize widthOfComponent=_widthOfComponent;
@property(nonatomic) unsigned long long layout; // @synthesize layout=_layout;
@property(retain, nonatomic) NSArray *checkBoxData; // @synthesize checkBoxData=_checkBoxData;
@property(retain, nonatomic) NSArray *radioButtons; // @synthesize radioButtons=_radioButtons;
@property(retain, nonatomic) UIColor *labelColor; // @synthesize labelColor=_labelColor;
@property(retain, nonatomic) UIFont *labelFont; // @synthesize labelFont=_labelFont;
@property(nonatomic) long long marginBetweenItems; // @synthesize marginBetweenItems=_marginBetweenItems;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *uncheckedCheckBoxes;
@property(readonly, nonatomic) NSArray *checkedCheckBoxes;
- (void)checkBoxDidChange:(id)arg1;
- (void)createCheckBoxes;
- (void)create;
- (id)initWithCheckBoxData:(id)arg1 style:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

