//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TNCheckBoxProtocol.h"

@class NSString, TNCheckBoxData, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface TNCheckBox : UIView <TNCheckBoxProtocol>
{
    NSString *_identifier;
    NSString *_label;
    TNCheckBoxData *_data;
    UIView *_checkBox;
    UILabel *_lblLabel;
    UIButton *_btnHidden;
    id <TNCheckBoxDelegate> _delegate;
    struct CGPoint _position;
}

@property(nonatomic) __weak id <TNCheckBoxDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
@property(retain, nonatomic) UIButton *btnHidden; // @synthesize btnHidden=_btnHidden;
@property(retain, nonatomic) UILabel *lblLabel; // @synthesize lblLabel=_lblLabel;
@property(retain, nonatomic) UIView *checkBox; // @synthesize checkBox=_checkBox;
@property(retain, nonatomic) TNCheckBoxData *data; // @synthesize data=_data;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)checkWithAnimation:(_Bool)arg1;
- (void)buttonTapped:(id)arg1;
- (void)createHiddenButton;
- (void)createLabel;
- (void)createCheckbox;
- (void)setup;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

