//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNCheckBoxData.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface TNCircularCheckBoxData : TNCheckBoxData
{
    UIColor *_borderColor;
    UIColor *_circleColor;
    long long _borderRadius;
    long long _circleRadius;
}

@property(nonatomic) long long circleRadius; // @synthesize circleRadius=_circleRadius;
@property(nonatomic) long long borderRadius; // @synthesize borderRadius=_borderRadius;
@property(retain, nonatomic) UIColor *circleColor; // @synthesize circleColor=_circleColor;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
- (void).cxx_destruct;

@end

