//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNCheckBox.h"

@class TNImageCheckBoxData, UIImageView;

__attribute__((visibility("hidden")))
@interface TNImageCheckbox : TNCheckBox
{
    UIImageView *_imageView;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)checkWithAnimation:(_Bool)arg1;
- (void)createCheckbox;
- (void)setup;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(retain, nonatomic) TNImageCheckBoxData *data; // @dynamic data;

@end

