//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNCheckBoxData.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface TNRectangularCheckBoxData : TNCheckBoxData
{
    UIColor *_borderColor;
    UIColor *_rectangleColor;
    long long _borderWidth;
    long long _borderHeight;
    long long _rectangleWidth;
    long long _rectangleHeight;
}

@property(nonatomic) long long rectangleHeight; // @synthesize rectangleHeight=_rectangleHeight;
@property(nonatomic) long long rectangleWidth; // @synthesize rectangleWidth=_rectangleWidth;
@property(nonatomic) long long borderHeight; // @synthesize borderHeight=_borderHeight;
@property(nonatomic) long long borderWidth; // @synthesize borderWidth=_borderWidth;
@property(retain, nonatomic) UIColor *rectangleColor; // @synthesize rectangleColor=_rectangleColor;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
- (void).cxx_destruct;

@end

