//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNCheckBox.h"

@class CAShapeLayer, TNRectangularCheckBoxData;

__attribute__((visibility("hidden")))
@interface TNRectangularCheckBox : TNCheckBox
{
    CAShapeLayer *_border;
    CAShapeLayer *_rectangle;
}

@property(retain, nonatomic) CAShapeLayer *rectangle; // @synthesize rectangle=_rectangle;
@property(retain, nonatomic) CAShapeLayer *border; // @synthesize border=_border;
- (void).cxx_destruct;
- (void)checkWithAnimation:(_Bool)arg1;
- (void)createCheckbox;
- (void)setup;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(retain, nonatomic) TNRectangularCheckBoxData *data; // @dynamic data;

@end

