//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ButtonsGroupDelegate.h"
#import "ShortenSortButtonDelegate.h"
#import "TagColorViewDelegate.h"

@class BottomBorder, ButtonsGroup, NSString, ShortenSortButton, TGCustomActivityIndicator, TagColorView, UIButton, UISegmentedControl;

__attribute__((visibility("hidden")))
@interface TopToolBarView : UIView <TagColorViewDelegate, ButtonsGroupDelegate, ShortenSortButtonDelegate>
{
    int _viewMode;
    _Bool _checkAllChecked;
    _Bool _searchButtonEnabled;
    _Bool _isEditing;
    _Bool _shouldAnimation;
    _Bool _tagButtonEnabled;
    _Bool _isLoading;
    double barHeight;
    TagColorView *colorView;
    double _progress;
    _Bool _allowReLoading;
    UIButton *_checkAllOrSearchButton;
    ShortenSortButton *_sortButtons;
    ButtonsGroup *_viewOptionOrTagColorButtons;
    TGCustomActivityIndicator *_activityIndicator;
    id <TopToolBarViewDelegate> _delegate;
    UISegmentedControl *_control;
    BottomBorder *_toolbarBackground;
}

+ (id)newToolbarWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) BottomBorder *toolbarBackground; // @synthesize toolbarBackground=_toolbarBackground;
@property(retain, nonatomic) UISegmentedControl *control; // @synthesize control=_control;
@property(nonatomic) _Bool allowReLoading; // @synthesize allowReLoading=_allowReLoading;
@property(nonatomic) __weak id <TopToolBarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TGCustomActivityIndicator *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) ButtonsGroup *viewOptionOrTagColorButtons; // @synthesize viewOptionOrTagColorButtons=_viewOptionOrTagColorButtons;
@property(retain, nonatomic) ShortenSortButton *sortButtons; // @synthesize sortButtons=_sortButtons;
@property(retain, nonatomic) UIButton *checkAllOrSearchButton; // @synthesize checkAllOrSearchButton=_checkAllOrSearchButton;
- (void).cxx_destruct;
- (void)updateSelectAll;
- (void)updateViewMode:(int)arg1;
- (id)currentSortInfos;
- (void)updateWithCurrentEditingMode;
- (void)replaceTitles:(id)arg1 withTile:(id)arg2;
- (void)setIsEditing:(_Bool)arg1;
- (void)setEditingToolBar:(_Bool)arg1;
- (void)setCheckAllChecked:(_Bool)arg1;
- (void)setViewMode:(int)arg1;
- (void)setTagButtonEnabled:(_Bool)arg1;
- (void)setSearchButtonEnabled:(_Bool)arg1;
- (void)checkAllOrSearchButtonTouched:(_Bool)arg1;
- (void)tagColorView:(id)arg1 selectedColorIndex:(long long)arg2;
- (void)tagColorViewWillHide:(id)arg1;
- (void)buttonGroup:(id)arg1 didSelectedIndex:(int)arg2;
- (void)buttonGroupDidResizeInAnimations:(id)arg1;
- (void)shortenSortButton:(id)arg1 didSelectSortWithSortInfos:(id)arg2;
- (void)setupSearchTopToolBarWithSegmentControl:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)stopProgressAnimation;
- (void)stopLoadingWithAnimation;
- (void)startLoadingWithAnimation;
- (_Bool)isLoading;
- (void)updateWithNewHeight:(double)arg1;
- (void)setProgressValue:(double)arg1;
- (double)progress;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

