//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, TopToolBarView;

@protocol TopToolBarViewDelegate <NSObject>
- (void)TopToolbarViewDidEndLoading:(TopToolBarView *)arg1;
- (void)TopToolbarViewDidBeginLoading:(TopToolBarView *)arg1;
- (void)TopToolbarView:(TopToolBarView *)arg1 didSelectTagColor:(int)arg2;
- (void)TopToolbarView:(TopToolBarView *)arg1 didSelectSearchButton:(_Bool)arg2;
- (void)TopToolbarView:(TopToolBarView *)arg1 didCheckedSelectAll:(_Bool)arg2;
- (void)TopToolbarView:(TopToolBarView *)arg1 didSelectSortMode:(NSDictionary *)arg2;
- (void)TopToolbarView:(TopToolBarView *)arg1 didSelectViewMode:(int)arg2;
@end

