//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGPreferencesTableViewController.h"

__attribute__((visibility("hidden")))
@interface TrashOptionViewController : TGPreferencesTableViewController
{
    _Bool _emptyTrashEnabled;
}

@property(nonatomic) _Bool emptyTrashEnabled; // @synthesize emptyTrashEnabled=_emptyTrashEnabled;
- (void)didReceiveMemoryWarning;
- (void)emptyTrash:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)updateEmptyTrashEnable;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

