//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIActionSheetDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIWebViewDelegate.h"

@class NSString, NSURL, UIActivityIndicatorView, UIBarButtonItem, UIColor, UIDocumentInteractionController, UIWebView;

__attribute__((visibility("hidden")))
@interface TSMiniWebBrowser : UIViewController <UIWebViewDelegate, UIActionSheetDelegate, UIDocumentInteractionControllerDelegate>
{
    NSURL *urlToLoad;
    UIWebView *webView;
    UIActivityIndicatorView *activityIndicator;
    UIBarButtonItem *buttonGoBack;
    UIBarButtonItem *buttonGoForward;
    int mode;
    _Bool showURLStringOnActionSheetTitle;
    _Bool showPageTitleOnTitleBar;
    _Bool showReloadButton;
    _Bool showActionButton;
    long long barStyle;
    UIColor *barTintColor;
    NSString *modalDismissButtonTitle;
    NSString *forcedTitleBarText;
    long long originalBarStyle;
    id <TSMiniWebBrowserDelegate> delegate;
    NSString *domainLockList;
    NSString *currentURL;
    UIDocumentInteractionController *_openIn;
}

@property(retain, nonatomic) UIDocumentInteractionController *openIn; // @synthesize openIn=_openIn;
@property(retain, nonatomic) NSString *currentURL; // @synthesize currentURL;
@property(retain, nonatomic) NSString *domainLockList; // @synthesize domainLockList;
@property(retain, nonatomic) UIColor *barTintColor; // @synthesize barTintColor;
@property(retain, nonatomic) NSString *modalDismissButtonTitle; // @synthesize modalDismissButtonTitle;
@property(nonatomic) long long barStyle; // @synthesize barStyle;
@property(nonatomic) _Bool showActionButton; // @synthesize showActionButton;
@property(nonatomic) _Bool showReloadButton; // @synthesize showReloadButton;
@property(nonatomic) _Bool showPageTitleOnTitleBar; // @synthesize showPageTitleOnTitleBar;
@property(nonatomic) _Bool showURLStringOnActionSheetTitle; // @synthesize showURLStringOnActionSheetTitle;
@property(nonatomic) int mode; // @synthesize mode;
@property id <TSMiniWebBrowserDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (id)setupControllerWithURL:(id)arg1 singDelegate:(id)arg2;
- (void)editClicked:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)loadURL:(id)arg1;
- (void)setFixedTitleBarText:(id)arg1;
- (void)buttonActionTouchUp:(id)arg1;
- (void)reloadButtonTouchUp:(id)arg1;
- (void)forwardButtonTouchUp:(id)arg1;
- (void)backButtonTouchUp:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showActionSheet;
- (void)didReceiveMemoryWarning;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)done;
- (void)viewDidLoad;
- (id)initWithUrl:(id)arg1;
- (void)initWebView;
- (void)initToolBar;
- (void)initTitleBar;
- (void)dealloc;
- (void)dismissController;
- (void)hideActivityIndicators;
- (void)showActivityIndicators;
- (void)toggleBackForwardButtons;
- (void)setTitleBarText:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

