//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class DataScroller;

__attribute__((visibility("hidden")))
@interface UIBytesCollectionViewCell : UICollectionViewCell
{
    unsigned long long _numberOfColumns;
    unsigned long long _numberOfLines;
    unsigned long long _cellType;
    DataScroller *_dataScroller;
    unsigned long long _startIndex;
    unsigned long long _numberOfBytes;
    long long _selectedIndex;
    long long _highlightedIndex;
    long long _editedIndex;
    id <UIBytesCollectionViewCellDelegate> _delegate;
}

@property(nonatomic) __weak id <UIBytesCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long editedIndex; // @synthesize editedIndex=_editedIndex;
@property(nonatomic) long long highlightedIndex; // @synthesize highlightedIndex=_highlightedIndex;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) unsigned long long numberOfBytes; // @synthesize numberOfBytes=_numberOfBytes;
@property(nonatomic) unsigned long long startIndex; // @synthesize startIndex=_startIndex;
@property(nonatomic) __weak DataScroller *dataScroller; // @synthesize dataScroller=_dataScroller;
@property(nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
@property(nonatomic) unsigned long long numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property(nonatomic) unsigned long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void *)dataPtrAtCellIndex:(long long)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

