//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface XPCUUID : NSObject
{
    struct __CFUUID *_uuidRef;
}

+ (id)uuidWithXPCObject:(id)arg1;
+ (id)uuid;
@property(readonly, nonatomic) struct __CFUUID *uuidRef; // @synthesize uuidRef=_uuidRef;
- (void)dealloc;
- (id)initWithUUIDRef:(struct __CFUUID *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
@property(readonly, nonatomic) NSString *string;
- (id)newXPCObject;

@end

